### ISSUE TITLE
undo button is initialized enabled despite no changes

### ISSUE THREAD

**Issue by dpistoleKUBRA** [mkhstar/suneditor-react#103]
In 2.13.2 the editor loads with the `setContents` value, but the undo button is enabled and clicking it reverts the text editor to blank state. The 12.12.5 release does not have this issue (undo is disabled until a change happens), so it seems like it was probably something recent. I will take a look at the code and see if I can identify the cause.

[2.13.2 Sanbox Here](https://codesandbox.io/s/unruffled-tereshkova-7it2v) has undo enabled.

[2.12.5 Sandbox Here](https://codesandbox.io/s/hardcore-surf-zz09j) has undo disabled.

**Comment by dpistoleKUBRA** [comment]
the code in the commit 9004f4d sync with latest suneditor version seems to work until i run npm build, then the error is introduced 🤔

**Comment by dpistoleKUBRA** [comment]
I think it was [this change](https://github.com/mkhstar/suneditor-react/commit/def8db88f0d10467a88d30354ec96098e58ca2fd#diff-bb7dcc5ad068a3381484aab0f08e6228L139) that did it, the onLoad get's called twice (once with `reload = true`) resulting in setContents getting called twice. If I rebuild locally with the `reload === false` conditional I don't have the issue with the undo button being enabled.

**Comment by mkhstar** [comment]
Thanks man for opening this issue. I think i forgot to wrap that block with reload === false. It will be fixed in the next release

**Comment by mkhstar** [comment]
I just fixed the bug in the latest version. Please confirm and close the issue

**Comment by dpistoleKUBRA** [comment]
looks good, thank you for the release (and your work on the library) 🥂
