### ISSUE TITLE
Doubt : Latest Code not updated in Suneditor react

### ISSUE THREAD

**Issue by vijayaragavan95** [mkhstar/suneditor-react#104]
I am using Suneditor react.

I got some issues, reported it in Suneditor and got fixed in milestone https://github.com/JiHong88/SunEditor/milestone/13

But the code is not reflected to Sundeditor react.

I also newly reported a issue. 

So kindly can you let me know how frequently latest code will get updated. 

And also confirm should i have to report bugs here or in that repository.

Thanks in advance.

**Comment by mkhstar** [comment]
Hi @vijayaragavan95 
Yes the milestone has been updated but it has not been published to npm yet. As soon as it is, I will sync it.
Also for the bugs the one relating to the editor itself should be reported at the suneditor repository but the one relating to react can be posted here

**Comment by vijayaragavan95** [comment]
@mkhstar ,
Thanks a lot for your info :)
I am closing this issue.
