### ISSUE TITLE
Can you upgrade SunEditor 2.33.1 ?

### ISSUE THREAD

**Issue by GaeTaeng** [mkhstar/suneditor-react#106]
안녕하세요.
먼저, 좋은 에디터의 배포에 깊은 감사의 인사를 드립니다.

며칠 전 SunEditor의 버그 이슈를 발견 후 등록하여 해당 버그가 수정되었는데,

혹 같이 업그레이드가 가능하신지 여쭤보기위해 이슈로 등록해봅니다.

제가 npm 라이브러리의 숙련도가 낮아서 npm install 과 같은 방식으로만 버젼을 관리 중인데,
혹 제가 혼자서 버젼관리가 가능하다면 
코멘트 주시면 감사합니다!

확인부탁드립니다.
감사합니다.

Can you upgrade SunEditor 2.33.1 ?

![image](https://user-images.githubusercontent.com/41108735/92670904-fb29ad80-f34f-11ea-84ca-97ccfe6ab3a6.png)

**Comment by mkhstar** [comment]
Hi @GaeTaeng ,
Just upgraded. Thanks
