### ISSUE TITLE
ctr+b, ctrl+i and ctrl+u doesn't apply necessary formatting for selected text when it is selected by mouse from the last

### ISSUE THREAD

**Issue by vijayaragavan95** [mkhstar/suneditor-react#107]
Kindly refer this issue for detailed description of the issue

https://github.com/JiHong88/SunEditor/issues/464

Actually it got fixed in last release. I cannot reporduce it in http://suneditor.com/sample/index.html

But still i can reproduce the same issue in Suneditor react

Kindly check and confirm me.

Thanks in advance

**Comment by mkhstar** [comment]
Hi @vijayaragavan95 
just updated the package to the latest version.
