### ISSUE TITLE
null is shown in width / height input field when constraint proportion checked with 0 in one of the input #463

### ISSUE THREAD

**Issue by vijayaragavan95** [mkhstar/suneditor-react#108]
Similarly this issue too.
https://github.com/JiHong88/SunEditor/issues/463
I raised this issue in parent component.

It cannot be reproduced in http://suneditor.com/sample/index.html

But still i can reproduce the same in Suneditor react

Kindly check the below issue and confirm me.
https://github.com/JiHong88/SunEditor/issues/463

Thanks in advance.

**Comment by mkhstar** [comment]
Hi @vijayaragavan95 
just updated the package to the latest version.
