### ISSUE TITLE
Parent component updated for issue imageAccept

### ISSUE THREAD

**Issue by vijayaragavan95** [mkhstar/suneditor-react#109]
In last release they launched an option to define accepted image formats.

But it was not working as accepted.

So another issue was reported and issue was fixed and a new release was given.

Kindly refer below issue.
https://github.com/JiHong88/SunEditor/issues/498

Can you please update it our Suneditor react npm package.

Thanks in advance.

**Comment by mkhstar** [comment]
Hi @vijayaragavan95 
just updated the package to the latest version.
