### ISSUE TITLE
onChange the content and setContent rerender editor component

### ISSUE THREAD

**Issue by itokun99** [mkhstar/suneditor-react#11]
i use this editor and try to setContent from API data like this

`
                  <SunEditor
                    onChange={this.onEditorChange}
                    setContents={postState.content}
                    setOptions={editorOptions}
                    width="100%"
                    lang="en"
                  />
`

when the content change, component rerender with input line back to first line of editor,

**Comment by mkhstar** [comment]
`setContents` and `onChange` state variables must be different.
setContents is used to set the default text content and onChange must be used to handle editor changes

**Comment by sawanmakwana** [comment]
I am also facing the same issue, onChange in Editor the cursor moves back to the first line automatically.

**Comment by mkhstar** [comment]
Please make sure you read the documentation concerning how to use setContents and onChange

**Comment by setesolutions** [comment]
Hey man, great work! 

I've a doubt, I need to drag a card of a list and drop the content of it inside editor, it's possible? Do you have some example for it?
Thanks a lot!

**Comment by mylastore** [comment]
"suneditor-react": "^2.14.4" for me setContents is triggering onChange and yes I am using different variables as suggested on the documentation. 

`Note setContents is used to set the initial contents of the editor. If you are setting the contents with a state variable, make sure that you are not using the same variable to handle the onChange event.`

**Comment by mylastore** [comment]
> "suneditor-react": "^2.14.4" for me setContents is triggering onChange and yes I am using different variables as suggested on the documentation.
> 
> `Note setContents is used to set the initial contents of the editor. If you are setting the contents with a state variable, make sure that you are not using the same variable to handle the onChange event.`

This is how I got it to work for anyone else that may have this issue.

My issue was form formData not been set yet. So I initialize an api call to get the initial data and after data is received I set the formData: new Formdata() and so I render the editor only if formData is not empty.
