### ISSUE TITLE
not being able to append the same content twice in a row

### ISSUE THREAD

**Issue by ali-garajian** [mkhstar/suneditor-react#110]
I'm trying to change the editor's content by code, and so far the only solution seems to be using the "appendContent" prop.
Since we can only pass a string variable down to appendContent, and its value is being compared with its previous value to only append new values, some restrictions are implied; One that I bumped into was not being able to add the same string twice, like in the examples section of the SunEditor package: http://suneditor.com/sample/html/examples.html#functions

If this is really an issue and I'm not missing anything, I can think of 2 solutions for it:
1) provide a ref to the SunEditor instance so we can have direct access to the core package's api
2) provide access to user functions such as appendContents through props

Thanks in advance =)

**Comment by ali-garajian** [comment]
Well I finally found a way around this! It was kinda super obvious :)
I was passing a state down to appendContent, and all I did was to set the state to null after every time I appended something

**Comment by mkhstar** [comment]
> I'm trying to change the editor's content by code, and so far the only solution seems to be using the "appendContent" prop.
> Since we can only pass a string variable down to appendContent, and its value is being compared with its previous value to only append new values, some restrictions are implied; One that I bumped into was not being able to add the same string twice, like in the examples section of the SunEditor package: http://suneditor.com/sample/html/examples.html#functions
> 
> If this is really an issue and I'm not missing anything, I can think of 2 solutions for it:
> 
> 1. provide a ref to the SunEditor instance so we can have direct access to the core package's api
> 2. provide access to user functions such as appendContents through props
> 
> Thanks in advance =)

Hi @ali-garajian,
You suneditor-react already allows you to attach ref to the component to get the underlining methods.

**Comment by mkhstar** [comment]
> Well I finally found a way around this! It was kinda super obvious but still doesn't work as it should :)
> I was passing a state down to appendContent, and all I did was to set the state to an empty string after every time I appended something.
> The problem is that I also get a new line appended, which is inconvenient. Also the cursor jumps backs to the beginning.
> 
> Any help would be much appreciated

For the cursor jumping to the beginning, It has been fixed in version 2.14.1. 
For the new line been appended everytime, I would have to look to that. But i think it might be coming from the core suneditor package
