### ISSUE TITLE
Pasting from a Word Document

### ISSUE THREAD

**Issue by snappa** [mkhstar/suneditor-react#116]
I've integrated this editor into a React app I'm building.  It works great.  Very easy to configure and integrate.

I have one issue I'm trying to solve.  When I paste from a Word doc it turns it into an image.  I found the onPaste event that I was able to hook into but have not been able to figure out how to just drop the text into the location in the document and prevent the image.  Looking for a pointer to help solve this.  Thank you,

**Comment by mkhstar** [comment]
Hi @snappa 
Sorry for the late reply. The new suneditor version has the same onPaste and onDrop parameter signatures. I have not yet implemented it in suneditor-react because there are some few issues with it. Immediately it is resolved, I will update the suneditor-react package.
Thanks

**Comment by snappa** [comment]
Thank you.  That doesn’t answer my question though.  Can you tell me why a paste from MS Word into the editor on Chrome ends up turning the pasted in content into an image as opposed to pasted in text?  I am able to get it pasted in as text if I paste it Shift-Command-V.

Yes, I see the API fix in the main Suneditor onDrop method.

-Bill

**Comment by mkhstar** [comment]
Sorry @snappa can you ask this at the main suneditor repository?
