### ISSUE TITLE
appendContents prop append content in a paragraph but it is more useful to append the text in the current paragraph.

### ISSUE THREAD

**Issue by rajparmar7879** [mkhstar/suneditor-react#117]

**Comment by mkhstar** [comment]
@JiHong88 appendContents just works fine but every time a content is appended it puts the cursor to the next line

**Comment by AliBayatMokhtari** [comment]
You can use ref to put content at the cursor position: ```editorRef.current?.insertHTML("Some text or html elements", false, false, false);```
