### ISSUE TITLE
Unable to type single quote ' into text

### ISSUE THREAD

**Issue by xlthor** [mkhstar/suneditor-react#118]
Editor does not accept ' as input char. Once I type in ' the char isn't shown.
The behavior is also in the SunEditor demos on http://suneditor.com/sample/index.html

Any Idea?

(it is not about ` or ´, its the single quote ' )

**Comment by mkhstar** [comment]
@xlthor I think this issue should be opened at the man [suneditor](https://github.com/JiHong88/SunEditor) repository

**Comment by xlthor** [comment]
@mkhstar right, sorry for bothering you.
