### ISSUE TITLE
Editor and Editor toolbars are not enabled, but after loading controller is enabled

### ISSUE THREAD

**Issue by soulcactus** [mkhstar/suneditor-react#121]
Hello.
I'm developing using NextJS.
This is my Setting.

```
<Editor
        disable={!editable}
        enableToolbar={editable}
        height="100%"
        lang="ko"
        name="content"
        onImageUpload={handleImageUpload}
        onImageUploadBefore={handleImageUploadBefore}
        setContents={content}
        setOptions={{
                buttonList: [...],
                imageUrlInput: false,
                resizingBar: false,
        }}
        showToolbar={editable}
        width="100%"
/>
```

There is a problem that the initial load controller is activated once while editable is false.
But click somewhere else, and it is not enabled immediately.
Did I miss something?
Waiting for your answer, Thank you.

![bug](https://user-images.githubusercontent.com/44562005/96960790-3833b300-153e-11eb-84fa-84878c8571c3.gif)

**Comment by soulcactus** [comment]
Also, I knew from the gif image, I think there is a problem with the toolbar blinking.

**Comment by mkhstar** [comment]
Hi @soulcactus 
Pardon me for the late reply. But can you explain what the loading controller is. Also it will really help if you could produce this same kind of issue in a codesandbox

**Comment by soulcactus** [comment]
@mkhstar Sorry I'm late. This is my codesandbox url(https://codesandbox.io/s/nice-shamir-nm4bw). I think there's something wrong with setOptions.

**Comment by mkhstar** [comment]
@soulcactus 
Please can you check this issue on the latest version?
