### ISSUE TITLE
Display problems in CodeView mode

### ISSUE THREAD

**Issue by yuera5196** [mkhstar/suneditor-react#122]
In CodeView mode, when writing < style > < / style >, the style setting is useless. Is the embedded style automatically ignored during conversion?

**Comment by yuera5196** [comment]
In CodeView mode, when writing < style > < / style >, the style setting is useless. Is the embedded style automatically ignored during conversion?

**Comment by mkhstar** [comment]
Hi @yuera5196 can you open this issue in the main suneditor package?
