### ISSUE TITLE
Can you upgrade SunEditor to version 2.34.X?

### ISSUE THREAD

**Issue by GaeTaeng** [mkhstar/suneditor-react#126]
I need the previewTemplat option.

![image](https://user-images.githubusercontent.com/41108735/98185366-d7e63d80-1f4f-11eb-9567-6f67b8a21e68.png)

**Comment by mkhstar** [comment]
Hi @GaeTaeng 
I am still working on it and besides there is an incompatible feature in the new release that i mentioned in this [issue](https://github.com/JiHong88/SunEditor/issues/548#issue-738266155). When it is fixed i will release the new version.
