### ISSUE TITLE
onImageUploadBefore

### ISSUE THREAD

**Issue by Saeeed-B** [mkhstar/suneditor-react#128]
@mkhstar 
hi 
Hi, I used the upload [onImageUploadBefore](http://suneditor.com/sample/html/out/document-user.html#onImageUploadBefore)
I uploaded the photo first and then called uploadHandler .
As follows : 
```
onImageUploadBefore(files , info , core ,uploadHandler){

            // Upload image to Server

            const src = UploadToServer(files[0]);

            // result
            const response = {
                // The response must have a "result" array.
                "result": [
                    {
                        "url": src,
                        "name": files[0].name,
                        "size": files[0].size
                    },
            ]}
            
            uploadHandler(response);
        }
```

In this case, the address is correct but the previous (base64) photo is not removed. And in fact two photos appear in the editor.

1 . A photo with the server address
2 . Photo with data address image / jpeg; base64

And after executing the following code, two photos with the two addresses I mentioned will be placed in the editor .
What should we do so that only the image with the server address is included ?

I also mentioned this in [the main source , JiHong88/SunEditor/issues/551](https://github.com/JiHong88/SunEditor/issues/551) and I do not think the problem will go back there.
????

**Comment by Saeed-Bahrami** [comment]
@mkhstar 
Of course, if you look at this, it's great.
And that makes me think the problem is not from the original source
[https://github.com/JiHong88/SunEditor/issues/414](https://github.com/JiHong88/SunEditor/issues/414)

**Comment by Saeed-Bahrami** [comment]
please see :
> [How do I do this in ReactJS & ExpressJS ??](https://github.com/JiHong88/SunEditor/issues/414#issuecomment-660094416)

[>"SunEditor" can be used as below from the latest version. ex
> 
> onImageUploadBefore(files, info, core, uploadHandler) {
>  const response = {..};
>  uploadHandler(response);
> }
> "suneditor-react" doesn't seem to have been updated yet.
> It will be available when the version is updated.
> 
> :React does not provide "core" object.
> 
> onImageUploadBefore(files, info, uploadHandler) {
>   const response = {..};
 >  uploadHandler(response);
> }
](https://github.com/JiHong88/SunEditor/issues/414#issuecomment-660418723)

**Comment by mylastore** [comment]
Mystery solved but for me with a little hack this is my code
```  const handleImageUploadBefore = (files, info, uploadHandler) => {
    const formData = new FormData()
    formData.append('avatar', files[0])

    apiForm('POST', 'blog/images', formData, getCookie('token'))
      .then((res, err) => {
        if (res) {
          setTimeout(() => {
            uploadHandler(res)
          }, 200)
        }
        return flash(err)
      })
  }```

**Comment by niltonxp** [comment]
@mylastore thx, works here: 
```
const handleImageUploadBefore = (files, info, uploadHandler) => {
    let response = {}
    request(api.upload(files[0])).then(img => {
      response = {
        result: [
          {
            url: img.location,
            name: img.originalName || 'Imagem',
            size: img.size
          }
        ]
      }

      uploadHandler(response)
    })
  }
```

**Comment by changyeamoon** [comment]
> @mylastore thx, works here:
> 
> ```
> const handleImageUploadBefore = (files, info, uploadHandler) => {
>     let response = {}
>     request(api.upload(files[0])).then(img => {
>       response = {
>         result: [
>           {
>             url: img.location,
>             name: img.originalName || 'Imagem',
>             size: img.size
>           }
>         ]
>       }
> 
>       uploadHandler(response)
>     })
>   }
> ```

What exactly are you sending back to `api.upload` to save the image? I dont see any encoded data @JiHong88 @niltonxp @Saeeed-B

**Comment by niltonxp** [comment]
![image](https://user-images.githubusercontent.com/22125059/122472290-c6115200-cf96-11eb-8ee7-97b125a6008c.png)

@changyeamoon just a file!

**Comment by changyeamoon** [comment]
> ![image](https://user-images.githubusercontent.com/22125059/122472290-c6115200-cf96-11eb-8ee7-97b125a6008c.png)
> 
> @changyeamoon just a file!
> ![image](https://user-images.githubusercontent.com/22125059/122472489-0b358400-cf97-11eb-834f-829517279e25.png)
> 
> When you do an upload, the function handleImageUploadBefore get an array of **Files**.

I see.. we dont need to send back an encoded64 string? I'm unfamiliar with the process of saving images 🥴

**Comment by niltonxp** [comment]
In my case, the backend is waiting for a file, so I do a POST like this:
`
 const upload = file => {
    const form = new FormData()
    form.append('file', file)
    const headers = {
      'Content-Type': 'multipart/form-data'
    }
    return api.post('/media', form, { headers })
  }
`

**Comment by changyeamoon** [comment]
Thanks @niltonxp ! I was def just confused because I never saved an image before.

**Comment by YanCamiloDev** [comment]
Full implementation with axios

`const handleImageUploadBefore = async (files, info, uploadHandler) => {
    Object.defineProperty(files[0], 'name', {
      writable: true,
      value: 'upload'
    });
    try {
      const formData = new FormData();
      formData.append('file', files[0])
      const res = await apiIntra.post('/conteudo/saveImgBody', formData, {
        headers: {
          'content-type': 'multipart/form-data'
        }
      });
      uploadHandler({
        result: [
          res.data
        ]
      })
    } catch (error) {
      console.log(error.response);
    }
  }`

**Comment by YanCamiloDev** [comment]
Full implementation with axios:

const handleImageUploadBefore = async (files, info, uploadHandler) => {
    Object.defineProperty(files[0], 'name', {
      writable: true,
      value: 'upload'
    });
    try {
      const formData = new FormData();
      formData.append('file', files[0])
      const res = await apiIntra.post('/conteudo/saveImgBody', formData, {
        headers: {
          'content-type': 'multipart/form-data'
        }
      });
      uploadHandler({
        result: [
          res.data
        ]
      })
    } catch (error) {
      console.log(error.response);
    }
  }

**Comment by YanCamiloDev** [comment]
### Full implementation with axios:
#
```
const handleImageUploadBefore = async (files, info, uploadHandler) => {
    Object.defineProperty(files[0], 'name', {
      writable: true,
      value: 'upload'
    });
    try {
      const formData = new FormData();
      formData.append('file', files[0])
      const res = await apiIntra.post('/conteudo/saveImgBody', formData, {
        headers: {
          'content-type': 'multipart/form-data'
        }
      });
      uploadHandler({
        result: [
          res.data
        ]
      })
    } catch (error) {
      console.log(error.response);
    }
  }
```

**Comment by niltonxp2** [comment]
> Hello, I know this is a closed issue but I am new to using this editor and I have followed each step in the solution presented here. The issue I'm facing is that I get the `uploadHandler is not a function` error. Can anyone please advice me on this?

Can you show your code?

**Comment by niltonxp2** [comment]
> > > Hello, I know this is a closed issue but I am new to using this editor and I have followed each step in the solution presented here. The issue I'm facing is that I get the `uploadHandler is not a function` error. Can anyone please advice me on this?
> > 
> > 
> > Can you show your code?
> 
> Thank you for replying! Here's my code:
> 
> Heres the ImageUploadBefore handler:
> 
> ```
> onImageUploadBefore =  (file, info, core, uploadHandler) => {
>         console.log("file: ", file[0]);
>         const fd = new FormData();
>         fd.append('file', file[0]);
>         fd.append('entityId', 123);
>         fd.append('docType', "PRODUCT_IAMGE");
>         const token = sessionStorage.getItem("token");
> 
>         const config = {
>             headers: {
>             Authorization: "Bearer " + JSON.parse(token).replaceAll('"', ""),
>             "ChannelKey" : "026bdbcea67670ef6a413c0f6309014efb17f0c96ee53faef8a80285c947371d"
>             },
>         };
> 
>         const url = endpoints.uploadImage;
> 
>         post(url, fd, config)
>             .then((res) => {
>                 console.log(res);
>                 const response = {
>                     "result" : [
>                         {
>                             "url" : endpoints.downloadImage + res.data.body.docId,
>                             "name" : res.data.body.docId,
>                         }
>                     ]
>                 }
>                 return uploadHandler(response);
>             })
>             // .catch(function () {
>             //     alert("Something went wrong!")
>             // });
>     }
> ```
> 
> and here is how I call the editor in the render method:
> 
> ```
> <SunEditor 
>                                 setOptions={{buttonList: buttonList.complex}} 
>                                 onInput={this.handleInput} 
>                                 onChange={this.handleChange}
>                                 setContents={this.state.content} 
>                                 onImageUploadBefore={this.onImageUploadBefore}
>                                 // placeholder="Please type here..."
>                             />
> ```

UploadHandler is the third param that you get onImageUploadBefore, you put as four!
Must be like:
onImageUploadBefore =  (file, info, uploadHandler) => {...

**Comment by umawani** [comment]
Ahh it works perfectly now. Stupid mistake on my end. Thank you so much for your help @niltonxp2 ! :)

**Comment by rahulkushwah-siliconithub** [comment]
> Mystery solved...
> 
> I am using this with nextjs
> 
> When I use async await the editor was inserting 2 images, but then switch to the format below and that work for me.
> 
> Hope it helps someone else here ;)
> 
> ```
>   const handleImageUploadBefore = (files, info, uploadHandler) => {
>     const formData = new FormData()
>     formData.append('avatar', files[0])
>     apiForm('POST', 'blog/images', formData, getCookie('token'))
>       .then((res)=>{
>         if (res.status >= 400) {
>           return flash(res.message)
>         }
>         uploadHandler(res)
>       })
>   }
> ```

thanks bro now it will work
