### ISSUE TITLE
getText in onChange

### ISSUE THREAD

**Issue by Saeeed-B** [mkhstar/suneditor-react#129]
hi @mkhstar .
how to use [getText ](http://suneditor.com/sample/html/out/document-user.html#getText)method In onChange Event ?

 or about other method . like [getContext](http://suneditor.com/sample/html/out/document-user.html#getContext) ,  [getContents](http://suneditor.com/sample/html/out/document-user.html#getContents)  ,  [getCharCount](http://suneditor.com/sample/html/out/document-user.html#getCharCount)

**Comment by mkhstar** [comment]
Hi @Saeeed-B attach a ref to the component to get the underlining value.
