### ISSUE TITLE
Core Support in Events !

### ISSUE THREAD

**Issue by Saeeed-B** [mkhstar/suneditor-react#130]
In some methods, **Core** is also entered as input, but this input is undefined in suneditor-react.

Core use in like this methos ;
[onChange(contents, core)](http://suneditor.com/sample/html/out/document-user.html#onChange)
[onFocus(contents, core)](http://suneditor.com/sample/html/out/document-user.html#onFocus)
[onBlur(contents, core)](http://suneditor.com/sample/html/out/document-user.html#onBlur)
[onPaste(contents, core)](http://suneditor.com/sample/html/out/document-user.html#onPaste)
and etc

**Comment by mkhstar** [comment]
Hi @Saeeed-B 
core can be easily gotten by attaching a ref to the Suneditor component

**Comment by OlehRb** [comment]
@mkhstar it looks like the type definition for `ref` property is missing

![image](https://user-images.githubusercontent.com/24420540/101051052-b8155a00-358d-11eb-8e73-cdb62a9890bb.png)

**Comment by novikov1337danil** [comment]
@mkhstar the previous comment describes the problem
