### ISSUE TITLE
Insert image - link not working for me

### ISSUE THREAD

**Issue by mylastore** [mkhstar/suneditor-react#132]
Version:   "suneditor-react": "^2.14.4"
I am using next version 10.0.0
Tryin to insert an image link from the insert image button is not working for me.
Does anyone have this issue? 
![localhost_3000_login](https://user-images.githubusercontent.com/8906338/98858701-e8962800-2415-11eb-8750-643b53d4196d.png)

**Comment by pakindessama** [comment]
Same issue here!!! Any solution??

**Comment by nltd101** [comment]
yes. can you resolve?

**Comment by tomislav-arambasic** [comment]
@mylastore @nltd101 

If I understand correctly, you're trying to insert an image using URL.
Your screen shows a link that wraps inserted image - when user clicks your image, it'll open that link.

To insert image via URL, use `Image URL` input, on `Image` tab of the popup.

<img width="496" alt="Screenshot 2021-04-27 at 21 38 49" src="https://user-images.githubusercontent.com/57353746/116302004-f7dd1800-a7a0-11eb-9bd6-0be969043a21.png">
