### ISSUE TITLE
please give me advice on how to handle input objects that exceed the fixed editor size.

### ISSUE THREAD

**Issue by GaeTaeng** [mkhstar/suneditor-react#133]
After fixing the size of the editor (using minHeight, maxHeight),
I need the ability to delete words that exceed the editor size when typing or pasting on the keyboard.

Please give me advice

I don't want to hide, I want to erase.

![image](https://user-images.githubusercontent.com/41108735/98916086-11014d80-250e-11eb-9602-8d0153fd9c87.png)

**Comment by mkhstar** [comment]
Hi @GaeTaeng 
You can open this issue at the main suneditor repository
