### ISSUE TITLE
RTL option not Support

### ISSUE THREAD

**Issue by Saeeed-B** [mkhstar/suneditor-react#135]
The original package has an option for rtl that apparently does not support your package .

**Comment by mkhstar** [comment]
@Saeeed-B I think you must be using typescript
Even though it supports it under the hood but i didn't specify typings for it.

**Comment by mkhstar** [comment]
I will fix that in the next release

**Comment by mkhstar** [comment]
Hi @Saeeed-B 
I added the type definition in the latest version 2.14.8
