### ISSUE TITLE
Insert image - use HEIC image files is not working

### ISSUE THREAD

**Issue by boruei-brc** [mkhstar/suneditor-react#136]
Version: "suneditor-react": "^2.14.4"

I used the HEIC image file to change the extension to .png and uploaded it but the photo cannot be displayed,
Is there a solution?

![image](https://user-images.githubusercontent.com/34204654/99228364-79f70700-2827-11eb-8294-b96060252382.png)

**Comment by mkhstar** [comment]
i @boruei-brc HEIC image is not supported as far as I know for more information open an issue at the main suneditor repository
