### ISSUE TITLE
Custom plugins not working

### ISSUE THREAD

**Issue by aderaHenry** [mkhstar/suneditor-react#137]
Hello @mkhstar . Custom plugins (submenus) are not working. Is there a specific way to add them, apart from the laid down way on the SunEditor website?

**Comment by mkhstar** [comment]
Hi @aderaHenry 
custom plugins can be added to the setOptions prop. To learn how to define a custom plugin please visit [here](http://suneditor.com/sample/html/customPlugins.html)
