### ISSUE TITLE
Question/Issue placeholder do not update

### ISSUE THREAD

**Issue by popoleeMaster** [mkhstar/suneditor-react#140]
Hello,
Sorry, I also created an issue here, but it concern react so I created also one in this repo. Please close whichever you want 

https://github.com/JiHong88/SunEditor/issues/568
 
I am using this nice editor in my rect app, with the react-i18next package.
I am calling rich text editor as follow :

const RichEditor = (props: RichEditorProps) => {
  const { t, i18n } = useTranslation();
  const { title, isRequired, help, note, value, error, disable, readOnly, placeholder } = props;
  
  return (
    <StyledContent disabled={disable}>
      <Label title={t(`TextForm.${title}`)} isRequired={isRequired} help={help} />
      {note && <Note title={note} />}
      <EditorContainer error={error}>
        <SunEditor
          {...props}
          setContents={value}
          placeholder={t(placeholder || '')}
          lang={i18n.language}
          disable={readOnly || disable}
          setOptions={{ buttonList: DEFAULT_BUTTON_LIST, ...props.setOptions }}
        />
      </EditorContainer>
    </StyledContent>
  );
};
the problem is, when the language is changed in the app, lang={i18n.language} this will change the button language, but placeholder={t(placeholder || '')} the placeholder will never change (I need to hard reload or refresh my component entirely).

I believe the Editor should update when the placeholder language is changed, and there is no content written.

I will setup a demo if needed

thanks

**Comment by mkhstar** [comment]
Hi @popoleeMaster 
Thanks for opening this issue. I just added that feature in version 2.14.7.
