### ISSUE TITLE
Custom plugins do not work after v.2.14.3

### ISSUE THREAD

**Issue by KallirroiZarkadoula** [mkhstar/suneditor-react#143]
I'm trying to add a custom plugin and with version 2.14.9 (latest) I get the following error: 
**[SUNEDITOR.core.callPlugin.fail] The called plugin does not exist or is in an invalid format**
I tried to replicate a simple plugin as developed in https://www.techighness.com/post/add-dropdown-list-suneditor-react-custom-plugin/.

Here is the code  with version 2.14.3 where it works: https://codesandbox.io/s/awesome-mccarthy-i0nn2?file=/src/App.js
If you change the dependency to any version later than that it fails with the message above.  Similar problem here https://codesandbox.io/s/suneditor-image-gallery-forked-tojxi with the same versions.

**Comment by mkhstar** [comment]
@KallirroiZarkadoula 
Thanks a lot man for opening this issue. Someone changed the name in a pull request from plugins to customPlugins. I will change the name back in the latest version

**Comment by mkhstar** [comment]
Fixed in version 2.14.10
