### ISSUE TITLE
Improper performance of setContents

### ISSUE THREAD

**Issue by Saeeed-B** [mkhstar/suneditor-react#145]
@mkhstar 
Hi, I want to use the editor to edit a text.
That is, I want to give the already prepared text to the editor, and work on it.
Like editing an article
Of course, this text is not empty text, but it is text that the same editor has already written, so this text comes with style and tags.

**I came to the conclusion that I should use [setContents ](url)with my search**

I transferred the previous text to the editor component with props.
And I set that prop in the editor with **[onLoad](url)**, but I get an error.

![image](https://user-images.githubusercontent.com/36485982/102588321-84f0d000-4122-11eb-82d5-5f3937a3b6d0.png)

![image](https://user-images.githubusercontent.com/36485982/102588359-92a65580-4122-11eb-912e-51eae1533c46.png)

@mkhstar But I get this error : 

![image](https://user-images.githubusercontent.com/36485982/102588446-b36eab00-4122-11eb-80a1-14540c439387.png)

And the value is not set

**Comment by mkhstar** [comment]
Hi @Saeeed-B 
 I wonder why you are using the underlining suneditor.
 There is already a setContents prop to achieve this.
`setContents={this.props.value}
`You do not need the onLoad for that as well
