### ISSUE TITLE
suneditor-react component is changing parent state property

### ISSUE THREAD

**Issue by aibolorazbekov** [mkhstar/suneditor-react#149]
I'm using `suneditor-react` library as a text editor. I have a component that renders `suneditor-react` wrapper component several times depending on state variable:
1. In first case, the component renders `suneditor-react` wrapper component 5 times.
2. In second case, the component renders `suneditor-react` wrapper component 8 times.
The content of the textareas are saved in parent states and the state handlers are passed to the editor wrapper as a property:
`const [answers, setAnswers] = useState([]);`

`answers` - values saved in textarea.

Here is the method that renders editors depending on variable `typeID`:
```
  const options = (typeID) => {
    if (typeID === 1) {
      return <EditorComp1 answers={answers} setAnswers={setAnswers} />;
    }
    if (typeID === 2) {
      return <EditorComp2 answers={answers} setAnswers={setAnswers} />;
    }
    return null;
  };
```
While `typeID` is changed, the `answers` state is also changed:
```
 useEffect(() => {
    let items = [];
    let numbers = [1, 2, 3, 4, 5];
    if (typeID === 2) numbers = [1, 2, 3, 4, 5, 6, 7, 8];
    numbers.map((ind, i) => {
      let item = {
        value: i,
        body: ''
      };
      items.push(item);
    });
    setAnswers(items);
  }, [typeID]);
```

Finally, the Editor component render method looks like this:
```
   {answers.map((answer, i) => (
        <Box mb={2} key={i}>
          <Grid container spacing={3}>
            <Grid md={1} item>
              <Checkbox checked={isChecked(answer.value)} onChange={(e) => onAnswered(e, answer.value)} />
            </Grid>
            <Grid md={11} item>
              <Editor setContents={answer.body} onChange={content => onContentChange(content, answer.value)} />
            </Grid>
          </Grid>
        </Box>
      ))}
```
The problem is that when `<Editor> `component onChange is called, the answers state is changed.

I don't know why it's changing because i'm not mutating any states here. Please, if you have any suggestions, help me!

**Comment by bar10** [comment]
I have a similar issue where after submitting value from Sun Editor back through the parent component it somehow the parent state is set back to the version before the editor was loaded/rendered. If I use a regular text area component this does not happen.

**Comment by mkhstar** [comment]
Hi @bar10 and @aibolorazbekov 
Can you please provide a demo using codesandbox? It will really help me to debug

**Comment by bar10** [comment]
> Can you please provide a demo using codesandbox? It will really help me to debug

https://codesandbox.io/s/distracted-forest-6296v

Steps the reproduce

1. Enter a value in the "Something else" field.
2. Enter a value in the "Name" field. (remember this one).
3. Click the "Toggle editor" to show the SunEditor.
4. Change the value in the editor by writing something.
5. Change the "Name" field value to a new name.
6. Add a single character to emit an on change event from the SunEditor.
7. Verify the name field value has jump back to it's value before the SunEditor was rendered, but the something else value has stayed untouched.

- If you use a normal textarea element instead of the editor everything works fine.
- If you set the value of "show_editor" to "true" and never toggle the editor everything works fine.
- My theory is that the conditional rendering of the editor and the fact that it is based on the contenteditable attribute screws with React's state management.

**Comment by bar10** [comment]
My colleague found a solution, by keeping track of the state in the parent component closer to the Editor

https://codesandbox.io/s/mutable-sound-py67u

Not sure if this can still be considered an issue with the Sun Editor.

**Comment by mkhstar** [comment]
Hi @bar10 and @aibolorazbekov 
 I don't think this is suneditor's problem.
@bar10 thanks for providing an example at codesandbox. When I reviewed the code I realized that the problem you encountered has got to do with the concept of closures. When you fed the DataManager function the value at that time, it stored that value. So when the suneditor is re-rendered again it used the value stored and passed to the state once again to reupdate it.

**Comment by mkhstar** [comment]
I will provide a solution to the it here

**Comment by mkhstar** [comment]
```jsx
import React, { Component } from "react";
import SunEditor from "suneditor-react";
import "suneditor/dist/css/suneditor.min.css";

import "./styles.css";

function DataManager({ description, onUpdate }) {
  function updateDescription(value) {
    onUpdate(value);
  }

  return (
    <MyEditor
      name="description"
      value={description}
      onChange={(value) => {
        updateDescription(value);
      }}
    />
  );
}

function MyEditor({ name, onChange, value }) {
  return (
    <SunEditor
      setOptions={{
        height: 200,
        buttonList: [
          ["undo", "redo"],
          ["formatBlock"],
          ["bold", "italic", "removeFormat"],
          ["link"],
          ["list"],
          ["showBlocks", "codeView"],
          ["fullScreen"]
        ]
      }}
      setContents={value}
      onChange={onChange}
    />
  );
}

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      show_editor: false,
      somethingelse: "",
      data: {
          name: "",
          description: ""
        }
      
    };
  }

  updateName = (event) => {
   
    this.setState({
      data: {
        ...this.state.data,
        name: event.target.value
      }
    })
  };

  updateSomethingElse = (event) => {
    this.setState({
      somethingelse: event.target.value
    });
  };

  handleUpdate = (description) => {
    this.setState({
      data: {
        ...this.state.data,
        description: description
      }
    });
  };

  toggleEditor = () => {
    this.setState({
      show_editor: !this.state.show_editor
    });
  };

  render() {
    console.log(this.state.data);
    return (
      <div>
        <div>
          <label>Something Else</label>
          <input
            name="somethingelse"
            value={this.state.data.somethingelse}
            onChange={this.updateSomethingElse}
          />
        </div>
        <h2>Combined data fields</h2>
        <div>
          <label>Name</label>
          <input
            name="name"
            value={this.state.data.name}
            onChange={this.updateName}
          />
        </div>
        <div>
          <button onClick={this.toggleEditor}>Toggle editor</button>
          {this.state.show_editor && (
            <DataManager description={this.state.data.description} onUpdate={this.handleUpdate} />
          )}
        </div>
      </div>
    );
  }
}

export default App;


```
