### ISSUE TITLE
Align CSS property removed

### ISSUE THREAD

**Issue by vladigubler** [mkhstar/suneditor-react#150]
<element style="text-align: XXX"> - style property is set by the editor, when re-opening the same HTML in the editor, the property is removed (it is still there first time Render is called, but it's gone on the second call, happening right away. 
Version 2.14.10. Rolling back to 2.13.1 solves the issue.

**Comment by mkhstar** [comment]
Hi @vladigubler 
I couldn't get the question. Please it will be really beneficial if you provide an example at codesandbox

**Comment by vladigubler** [comment]
What we experienced:
1. Add some text, use text align buttons on the toolbar to align it to the right
2. Value is saved, we can see that the element has text-align: right property set
3. Load value again, text is aligned to the left, property is gone. If I track the value, it loads with the property set, then on the second call to render() it's gone. We don't have any of our own code that changes the value. Problem is solved by downgrading the version back. Unfortunately, I won't be able to create a sandbox for this.

**Comment by UpadhyayPooja** [comment]
I am also facing the same issue.... @vladigubler could you please help me how you have resolved the issue...which version you have used ????

It would be really very helpful,  thank you in advance.

**Comment by mkhstar** [comment]
Hi @vladigubler 
It has been added to the milestone of 3.0.0 of the core suneditor package
