### ISSUE TITLE
add custom drop down in editor?

### ISSUE THREAD

**Issue by jainal09** [mkhstar/suneditor-react#151]
Hi,
I want to add a functionality in which when a user types in @ there should a drop down appear and in it names appear just like github eidtor here.

I am using this suneditor-react lib and want to achieve the following functionality with it.
Is it possible to do this using the same?

**Comment by mkhstar** [comment]
Hi @jainal09 
This feature is not available in suneditor at the moment but you can request it in the  [core package](https://github.com/JiHong88/SunEditor)
