### ISSUE TITLE
Has anyone succeed in using syntax highlighting ?

### ISSUE THREAD

**Issue by sanjampreet-singh** [mkhstar/suneditor-react#153]

**Comment by mkhstar** [comment]
Hi @sanjampreet-singh 
You can use the setOptions prop to set the codeMirror property as specified in the main suneditor [page](https://github.com/JiHong88/SunEditor#options)

**Comment by sanjampreet-singh** [comment]
I wanted syntax highlighting inside html rendered by editor not inside code view
How to highlight syntax in html

**Comment by mkhstar** [comment]
Hi @sanjampreet-singh 
I am sorry but this feature is not available in Suneditor

**Comment by sanjampreet-singh** [comment]
> Hi @sanjampreet-singh
> I am sorry but this feature is not available in Suneditor

Sir Could you just please help me out how i could append <code> tag inside <pre> tag which are generated when we use code blocks
