### ISSUE TITLE
Bug with tables in Firefox browser!

### ISSUE THREAD

**Issue by PouRiaBG** [mkhstar/suneditor-react#154]
In the Chrome browser, when I use the table and then click on the page, the mouse cursor goes on it, but when I use Firefox, clicking on the content page does not change the mouse cursor and remains on the table.
in chrome : 

https://user-images.githubusercontent.com/34285373/104038523-7a3dce00-51ea-11eb-9ee7-0bfb2356887e.mov

in firefox : 

https://user-images.githubusercontent.com/34285373/104038608-95104280-51ea-11eb-9888-5c6a9689feb0.mov

**Comment by mkhstar** [comment]
Hi @PouRiaBG 
I think this issue has to do with the main suneditor core package. @JiHong88
