### ISSUE TITLE
Justify alignments are getting removed.

### ISSUE THREAD

**Issue by UpadhyayPooja** [mkhstar/suneditor-react#155]
### Justify alignment is  getting removed.
alignment style property is set by the editor, when re-opening the same HTML in the editor, these property are getting removed it is still there first time Render is called, but it's gone on the second call.
can anyone help me to resolve this

**Comment by UpadhyayPooja** [comment]
As per [issue 150](https://github.com/mkhstar/suneditor-react/issues/155)  Version 2.14.10. Rolling back to 2.13.1 solves the issue, but other style related and formatting issues are getting arise. for example - small dialog box for table cell customization and image  customization  are not coming and some other styles are not that much good as it is in latest version

**Comment by SiddAjmera** [comment]
@mkhstar, Here'e a Sample [StackBlitz](https://stackblitz.com/edit/react-sun-editor-sample?file=index.tsx) Replicating the Issue.

I'm storing the rich text in localStorage every time there's a change. And then when I reload the page, I'm taking that default value back from the localStorage. But it's getting rid of the alignment properties of the paragraph.

To replicate, try aligning the text in the Editor to center and then refreshing(reloading) the page.

**Comment by s-kris** [comment]
We need to whitelist it explicitly for now. 
https://github.com/JiHong88/SunEditor/issues/609#issue-796247462

**Comment by mkhstar** [comment]
Thanks @s-kris

**Comment by whybein** [comment]
Text alignment is fixed but image alignment especially to the right is not working fine. It is aligned to center.
I fixed this by code below on react(NEXTjs)

```
if (typeof window !== 'undefined') {
    const { width } = document.getElementsByClassName('__se__float-right')[0].firstChild.firstChild;
    document.getElementsByClassName('__se__float-right')[0].firstChild.style.removeProperty('margin');
    document
      .getElementsByClassName('__se__float-right')[0]
      .firstChild.setAttribute('style', `width:${width}px; margin-left:auto!important;`);
}
```

and then It shows peroperly
```
<div class="... __se__float-right">
<figure style="width: 200px; margin-left:auto;">
...
```
