### ISSUE TITLE
Fonts are not getting applied to every row of selected plain text....if created using copy paste

### ISSUE THREAD

**Issue by UpadhyayPooja** [mkhstar/suneditor-react#156]
### Fonts size and family are not getting applied to every row of selected plain text

- multiple line of text is there ( created using copy paste, firstly  paste 1 or more lines then press enter and again press 1 or more line)
- then select all row of text
- try changing font family or size
- it is not going to applied on all rows

basically I have observed this issue after pasting text and pressing enter button and again pasting text, in this case some lines are not getting updated with selected font family

can anyone help me to resolve this

**Comment by mkhstar** [comment]
Hi @UpadhyayPooja 
Can you try the latest suneditor-react version? If the issue persists please reopen the issue and do us a favour in providing a demo
