### ISSUE TITLE
Paste html as a plain text

### ISSUE THREAD

**Issue by Grouft** [mkhstar/suneditor-react#157]
Hi, is there any way to paste html as a plain text?
I've found onPaste event, but can't figure it out. How can I use it to dynamically change pasted html and return it without any styles? Please, can anyone help me?

**Comment by s-kris** [comment]
Looking for the same @mkhstar 

Thank you!

**Comment by NandhiniVishwanath** [comment]
Have similar issue @mkhstar I have content with spaces and new line content. When I copy paste, not able to paste content as it is. Can you please help?

Thanks you

**Comment by rishabhBuyerassist** [comment]
i am also working on the same kind of task. to remove style you can use regex and then 
you have to **return the desired string from onPaste function**.

**Comment by guido-visser** [comment]
It seems to me that this is not a feature request for this package as it's just a wrapper. This is a feature request for the main `[suneditor](https://github.com/JiHong88/SunEditor)` package.

**Comment by dacoten** [comment]
@rishabhBuyerassist : Hi, I have a question. How can I hold the previous data after pasting another one?
