### ISSUE TITLE
render the result

### ISSUE THREAD

**Issue by c7nasr** [mkhstar/suneditor-react#158]
is there's a way to render the results? i save the HTML in my db when I use react-render-html to retrieve it styles like "BlockQuote and Code" is broken!
so what's the best idea to render what I typed!

**Comment by mkhstar** [comment]
@c7nasr what is the version of suneditor-react you are using

**Comment by c7nasr** [comment]
Latest 1mo ago. With NextJs

**Comment by mkhstar** [comment]
Hi @c7nasr 
Can you try it with the latest version
