### ISSUE TITLE
update suneditor to 2.35.0

### ISSUE THREAD

**Issue by s-kris** [mkhstar/suneditor-react#159]
Suneditor is updated
https://github.com/JiHong88/SunEditor/commit/c2740391d79f4a166b30b7a712deb68a600ad67f

**Comment by s-kris** [comment]
https://github.com/mkhstar/suneditor-react/pull/160

**Comment by mkhstar** [comment]
Hi @s-kris 
I will be updating it in just a moment. Some issues have to be fixed prior to that

**Comment by s-kris** [comment]
Fantastic! Thank you.
