### ISSUE TITLE
Failed to create production build (UglifyJs Unexpected token)

### ISSUE THREAD

**Issue by Danielks92** [mkhstar/suneditor-react#16]
Hi, 

If I use 'npm start' suneditor works just fine for me.
However, if I try to create a production build I get the following error:

`static/js/main.31f4794a.js from UglifyJs
SyntaxError: Unexpected token: name (n) [./~/suneditor-react/dist/main.js:13,1199]`

Any idea why?

React: 16.8.6
suneditor-react: 2.5.0

**Comment by mkhstar** [comment]
Hi @Danielks92  can you try again since we switched to webpack

**Comment by Danielks92** [comment]
Hi, 
unfortunately it's still not working for me. 
However I'm not quite sure why. It fails with:
child_process.js634 throw err;

Error: Command failed: node ./node_modules/react-scripts/scripts/build.js
    at checkExecSyncError (child_process.js:591:13)
    at execSync (child_process.js:631:13)
    at Object.<anonymous> (C:\...\run-with-environment.js:22:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)

run-with-environment file: 

`const execSync = require('child_process').execSync;
const argv = require('minimist')(process.argv.slice(2));

const ENV = require('./config/environment')(argv.environment, argv.brand, argv.usermanagement, argv.youtubeFeature);

const exportEnv = {};

Object
  .keys(ENV)
  .forEach((key) => {
    if (key === 'PUBLIC_URL') {
      exportEnv[key] = ENV[key];
    } else {
      exportEnv[`REACT_APP_${key.toUpperCase()}`] = ENV[key];
    }
  });


const generateCommand = command => `node ./node_modules/react-scripts/scripts/${command}.js`;
const command = generateCommand(argv.command);

execSync(command, { env: exportEnv });`

**Comment by juanjosuem** [comment]
I have the same problem

**Comment by DavidFernandezPuentes** [comment]
I have the same problem, we need help!

**Comment by AllexxT** [comment]
After minification all editor styles is gone

**Comment by karthik-js** [comment]
@mkhstar 

I am using suneditor-react ---> v2.14.2 with next js

It is working fine in development. When we deploy it, all the suneditor styles are gone.

Can we get a solution for this as to why this is happening? Or any alternate to load styles in the production environment.

**Comment by karthik-js** [comment]
> @mkhstar
> 
> I am using suneditor-react ---> v2.14.2 with next js
> 
> It is working fine in development. When we deploy it, all the suneditor styles are gone.
> 
> Can we get a solution for this as to why this is happening? Or any alternate to load styles in the production environment.

I am using work around by using suneditor cdn for styles. Hope you guys resolve the issue in the package soon

**Comment by rahulborah** [comment]
@karthik-js I am also facing the same issue. Can you provide the details about how did you resolved it with CDN?

**Comment by s-kris** [comment]
@rahulborah I imported the css file in _app.tsx to solve this

**Comment by mkhstar** [comment]
Hi everyone can you try it with the latest version
