### ISSUE TITLE
'/' added before links even if I start link with 'mailto:...'

### ISSUE THREAD

**Issue by EvgenPastushek** [mkhstar/suneditor-react#163]
Hello!

When I try to paste link without protocol but with 'mailto:...' it still recognized as relative link (http://localhost:8080//mailto:some@email.ex)

issue is already fixed in https://github.com/JiHong88/SunEditor/releases/tag/2.36.0 (report: https://github.com/JiHong88/SunEditor/issues/608)

could you update version of suneditor dependency please?

Thank you!

**Comment by mkhstar** [comment]
fixed in version 2.15.2

**Comment by EvgenPastushek** [comment]
all works!
thanks a lot
