### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by Adarsh1999** [mkhstar/suneditor-react#164]
Hi I have a question I want to add dark mode in sun editor but I dont know how to do it like do i have to overwrite css class for the purpose ? So can anybody give me a head start for the same?

**Comment by mkhstar** [comment]
@JiHong88 is there a dark mode feature

**Comment by JiHong88** [comment]
@Adarsh1999 You can create it by modifying css. [EX](https://huro.cssninja.io/components-plugins-editor-sun.html)
Currently, there is no pre-made theme file.
I will update it later.

**Comment by nickelaos** [comment]
Any updates?

**Comment by AnmolVerma404** [comment]
@mkhstar SunEditor v3 (Exact release version is [3.0.2](https://github.com/JiHong88/suneditor/releases/tag/3.0.2)) supports dark mode, but I don’t see any updates in this repo regarding v3 compatibility.
Should I assume it will work correctly with the latest version of SunEditor?
cc: @JiHong88

**Comment by JiHong88** [comment]
@AnmolVerma404 
This repository does not support v3.
I will be releasing the official "react" version soon.
