### ISSUE TITLE
HTML attributes being removed while it shouldn't

### ISSUE THREAD

**Issue by guido-visser** [mkhstar/suneditor-react#167]
I'd like to let people edit HTML emails in the Sun Editor, when I paste the HTML via the Code View, it works good and shows the correct layout (with all the inline-styles and attributes). However, if I take the same string of HTML and set is as the defaultValue, it removes a lot of the markup. 

Playground:
https://codesandbox.io/s/unwanted-html-removal-on-load-7mpmm?file=/Editor.js

https://user-images.githubusercontent.com/16164800/107387571-414c8e00-6af5-11eb-9331-2f6c1b7d288b.mp4

**Comment by gabrielhrp31** [comment]
can you solve it? when i set the content for property defaultValue, inline styles disappear from html code!

**Comment by guido-visser** [comment]
I looked at the code. The SunEditor is initialized without any `setOptions`. It seems to me that the `setOptions` that are passed need to be initialized together on [line 22](https://github.com/mkhstar/suneditor-react/blob/56eb15f29c17cb20825ba8fbf30bbb9aa1d1f6a9/SunEditor.js#L22)

I could create a PR with a simple spread of the `setOptions` to resolve this quickly. Let me know @mkhstar

**Comment by guido-visser** [comment]
PR created

**Comment by mkhstar** [comment]
Hi @guido-visser 
Thanks for raising this issue and sorry for replying late.
The problem has got to do with some little inconsistencies with the main suneditor package's setOptions method. For example if you use suneditor@2.34.0 or below you wouldn't encouter these issues.

**Comment by mkhstar** [comment]
You can follow the issue i opened at [https://github.com/JiHong88/SunEditor/issues/639](https://github.com/JiHong88/SunEditor/issues/639)

**Comment by guido-visser** [comment]
Thanks, I'll keep an eye out for a fix
