### ISSUE TITLE
onChange does not work when you change the alignment using the button "align"

### ISSUE THREAD

**Issue by subrahmanyaadiga** [mkhstar/suneditor-react#17]
onChange is not invoked when you change the alignment using the toolbar button align. The content is changing but the onChange method is not invoked. Please check this.

**Comment by subrahmanyaadiga** [comment]
onChange is not invoked when you change the alignment using the toolbar button align. The content is changing but the onChange method is not invoked. Please check this.

**Comment by mkhstar** [comment]
Can you please check the latest versions. I think it invokes by now
