### ISSUE TITLE
lang prop not working

### ISSUE THREAD

**Issue by ValentinGitHuber** [mkhstar/suneditor-react#170]
I expected the tooltips language to correspond to prop lang.

"suneditor-react": "^2.15.2",
"next": "^10.0.6",

![suneditor](https://user-images.githubusercontent.com/19436522/107488780-81148380-6b90-11eb-868e-b7921fd7fd11.png)
![Screen Shot 2021-02-10 at 11 06 36 AM](https://user-images.githubusercontent.com/19436522/107488787-8376dd80-6b90-11eb-877b-f0711dc5d380.png)

**Comment by mkhstar** [comment]
Hi @ValentinGitHuber 
sorry for the late reply. The problem comes from the suneditor package since version 2.35.0. I just opened an issue at [https://github.com/JiHong88/SunEditor/issues/639](https://github.com/JiHong88/SunEditor/issues/639)

**Comment by mkhstar** [comment]
When it is fixed I will surely update it. Thanks

**Comment by mkhstar** [comment]
Hi @ValentinGitHuber 
fixed in version 2.16.0, thanks
