### ISSUE TITLE
Set content based on state

### ISSUE THREAD

**Issue by guido-visser** [mkhstar/suneditor-react#173]
There is a defaultValue that can set the content at the moment the component is mounted. However, is it possible to programmatically add a string once the component is mounted.

I'd like to see a `value` prop that can be set to state, so that if the state changes, the content changes.

**Comment by mkhstar** [comment]
Hi @guido-visser 
setContents prop should be used for this effect

**Comment by guido-visser** [comment]
My bad! Sorry for overlooking this, however I do have a question, you note: `onChange` is used to handle changes to the editor. Make sure that you are not using the same variable for `setContents`. 

My logic was to set the state in `onChange` and use that variable in `setContents`, but this note suggests not to do that. Is that because of performance issues? If so, what would you suggest?
