### ISSUE TITLE
Add functionality for the save button

### ISSUE THREAD

**Issue by conrad-scherb** [mkhstar/suneditor-react#179]
Is there a callback for the save function/any way to script what happens on save?

**Comment by WTKersten** [comment]
@conrad-scherb you can add the callBackSafe on the options you pass to the setOptions attribute. 

<img width="288" alt="Screenshot 2021-03-11 at 16 17 38" src="https://user-images.githubusercontent.com/6919938/110764337-8515ed00-8285-11eb-995e-a3fef3f79d60.png">
