### ISSUE TITLE
Add manual focus instructions on docs 

### ISSUE THREAD

**Issue by icaroscherma** [mkhstar/suneditor-react#180]
After exposing the `ref` I found that to manually trigger focus (i.e. click on a Label and it focuses the suneditor input) all we have to do is:

```JSX
import React, {useCallback,useRef} from 'react';
import SunEditor from 'suneditor-react';

const inputRef = useRef();
const focusInput = useCallback(() => inputRef.current.editor.core.focus(), []);

return <>
  <label onClick={focusInput} >my wysiwyg</label>
  <SunEditor ref={inputRef} />
</>;
```

I would be nice to add this for other users who might need it so they save a bit of time.

**Comment by mkhstar** [comment]
Hi i could add that to the docs but it would make the it very lengthy and difficult to follow. There is a separation of concern with the main suneditor core. Everything exposed in the ref is in the documentation of the main suneditor package

**Comment by mkhstar** [comment]
Thanks
