### ISSUE TITLE
Code view events

### ISSUE THREAD

**Issue by ScottWager** [mkhstar/suneditor-react#181]
Events that are used to get contents of the editor don’t run while in code view mode.

1. onChange
2. onBlur

If a user makes changes in the code view mode and then saves their changes before switching back to WYSIWYG mode, their changes are lost because we rely on both of these events to update our useRef state.

**Comment by mkhstar** [comment]
Hi @ScottWager 
For now suneditor only responds to events such as onChange and onBlur when the editor is not in code view. Even when the codeview is editor you have to switch back to the wysiwyg mode to trigger those events. I think this could be a feature request. You could open it in the main suneditor repository

**Comment by coffee3k** [comment]
I really need this functionality. Is there a way to switch back real quick to WYSIWYG before submiting the form? That would really help.
