### ISSUE TITLE
className attribute is removed from tags while using attributeWhitelist

### ISSUE THREAD

**Issue by alex-bordea** [mkhstar/suneditor-react#185]
Hello

While trying to use suneditor-react, we've noticed the following issue: class and className attributes are removed from tags. This does not occur for other attributes (such as alt, style, etc.). Using attributeWhitelist does not solve this issue.

We've prepared the following code sand box to underline the issue. After initialization, check code view. The className tags will be removed.

https://codesandbox.io/s/competent-framework-l20yg?file=/src/App.js

We've searched for others that might've encountered the issue but couldn't find anything other than adding the '__se__tag' class to the parent div but this didn't work either.

Is there something that we're missing to use attributeWhitelist or is this an issue/bug?

Thank you.

**Comment by mkhstar** [comment]
Hi @alex-bordea 
I think you might have made a typo
The option's name is **attributesWhitelist** not **attributeWhitelist** you forgot to add 's'

**Comment by alex-bordea** [comment]
@mkhstar you are right, sorry to bother. Thank you!!
