### ISSUE TITLE
Focus automatically set to Image even when auto focus in set to false

### ISSUE THREAD

**Issue by vijayaragavan95** [mkhstar/suneditor-react#186]
Issue Detail:
I kept suneditor react component in my project in register and its corresponding update screen.
I uploaded an image in register screen. When I again open it with Update screen, focus is automatically set to Image which I kept.
I also did document.activeElement.blur() and also tried setting focus to another input element still not wokring.
Image is highlighted with blue color border showing resizing container div.

Note : Initially on opening update screen, i passed content to setContents prop, this which in return invokes onChange method.

Kindly help me with this issue.

**Comment by mkhstar** [comment]
Hi @vijayaragavan95 
Please use the defaultValue prop to set the initial contents of the editor. The default value prop is used when you don't want the onChange method to invoke on init. Hope this helps
