### ISSUE TITLE
Add content at cursor position

### ISSUE THREAD

**Issue by saiyamjain143** [mkhstar/suneditor-react#188]
I have scenario where, on click of button, I need to add some text, on current cursor location in the editor. How can I achieve this?
Also, for using ref, it is giving me error:
I am using react with typescript)
![112375586-77db1280-8d09-11eb-8dba-e2bd0ed208fd](https://user-images.githubusercontent.com/31028359/112414600-4fbed400-8d48-11eb-9a13-0f9f0ff6fcf5.png)

**Comment by mkhstar** [comment]
Hi @saiyamjain143 
I just updated the package. 
The ref problem has been fixed. If you would like the 'cursor position feature' to be implement, please open an issue at the main suneditor repository. To learn how to correctly type the ref, please refer to the documentation
