### ISSUE TITLE
Get plain text instead of HTML

### ISSUE THREAD

**Issue by gaurav3017** [mkhstar/suneditor-react#189]
Is there a way to get only the text in `onChange` method? Currently, the editor only returns an HTML snippet.

**Comment by gaurav3017** [comment]
I am able to achieve this with the below code but it would be nice to have a simpler solution.

```
const removeHtmlTags = str => {
	if (str === null || str === '') return false
	else str = str.toString()

	return str
		.replace(/(<([^>]+)>)/gi, '')
		.replace('&amp;', '&')
		.replace('&gt;', '>')
		.replace('&lt;', '<')
		.replace('&apos;', "'")
}
```

**Comment by mkhstar** [comment]
Hi @gaurav3017 
I think you can make a feature request at the main suneditor repository

**Comment by mkhstar** [comment]
Hi @gaurav3017 
I just realized that you can get plain text using the getText function. You have to attach ref to the component in order to get the editor's instance
```javascript
editorRef.current.editor.getText()
```
