### ISSUE TITLE
setContents에 markup string 삽입시 오류.

### ISSUE THREAD

**Issue by kimcoder** [mkhstar/suneditor-react#19]
안녕하세요.
에디터 사용 중 아래와 같은 이슈가 있어 확인해주시면 좋을 것 같아 글 남깁니다 :)

에디터의 초기 컨텐츠 데이터 삽입을 위한 setContents props에 
아래와 같은 형식의 문자열을 주입하면 destory 속성이 undefined라는 오류가 납니다.
이미지 태그가 있을시에 오류가 발생하는 것으로 추축되는데.. 확인해주시면 좋을 것 같아요!
그럼 수고하세요~

`<p><img src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" style="width: 900px;"><br></p>`

```
Cannot read property 'destroy' of undefined
TypeError: Cannot read property 'destroy' of undefined
```

**Comment by mkhstar** [comment]
Can you explain the problem you are facing please

**Comment by kimcoder-bm** [comment]
> 안녕하세요.
> 에디터 사용 중 아래와 같은 이슈가 있어 확인해주시면 좋을 것 같아 글 남깁니다 :)
> 
> 에디터의 초기 컨텐츠 데이터 삽입을 위한 setContents props에
> 아래와 같은 형식의 문자열을 주입하면 destory 속성이 undefined라는 오류가 납니다.
> 이미지 태그가 있을시에 오류가 발생하는 것으로 추축되는데.. 확인해주시면 좋을 것 같아요!
> 그럼 수고하세요~
> 
> `<p><img src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" style="width: 900px;"><br></p>`
> 
> ```
> Cannot read property 'destroy' of undefined
> TypeError: Cannot read property 'destroy' of undefined
> ```

Hi,
Sorry for my explain language.

`Cannot read property 'destroy' of undefined` error occurred this code.
```
const initialContent = `<p><img src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" style="width: 900px;"><br></p>`;

return <SunEditor setContents={initialContent}/>;
```
I guess `<img>` has problem. Just try.
Thanks

**Comment by yonggwan** [comment]
In detail..
an error occurs when the 'image' and the 'img tag of the markup of the button list of `setOption` props are combined.

```
const initialContent = `<p><img src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" style="width: 900px;"><br></p>`;

return <SunEditor setContents={initialContent} setOptions={
  {
    buttonList: [['image']]
  }
}/>;
```

**Comment by mkhstar** [comment]
I didn't get any problem when I tried can you please post the full code here

**Comment by yonggwan** [comment]
the full code is here. thanks!

```
import React from 'react';
import SunEditor from 'suneditor-react';
import 'suneditor/dist/css/suneditor.min.css';

const TextEditorOptions = {
  buttonList: [
    ['image']
  ]
};

const App = () => {
  const initialContent = `<img src="https://picsum.photos/200/300">`;

  return (
    <div>
      <p> My Other Contents </p>
      <SunEditor setOptions={TextEditorOptions} setContents={initialContent} />
    </div>
  );
};

export default App;

```


version info.
```
{
"suneditor": {
      "version": "2.25.0",
      "resolved": "https://registry.npmjs.org/suneditor/-/suneditor-2.25.0.tgz",
      "integrity": "sha512-HOh7XixP1G6DNlgALprQcEJvU1FrCZdPcaqy5BAD+Pu6cU5vCotMmR9UXQzHHYwSWbvEMc3dsvVGFP68FPPokQ=="
    },
    "suneditor-react": {
      "version": "2.4.0",
      "resolved": "https://registry.npmjs.org/suneditor-react/-/suneditor-react-2.4.0.tgz",
      "integrity": "sha512-ELw7nRspn+2CEA0RejclHHIqHxUIuuGTJlO3PGhn5CiOZ6cZlhSrdjUsNtS5Ww0ILovORg2D/m9/K8bDMAqv6A==",
      "requires": {
        "prop-types": "^15.7.2",
        "suneditor": "^2.23.0"
      }
    }
}
```

**Comment by yonggwan** [comment]
https://codesandbox.io/s/red-dew-54m5n?fontsize=14&hidenavigation=1&theme=dark

**Comment by conorstrejcek** [comment]
We are experiencing the exact same issue. When we set the `setContents` prop to a string which contains an `img` tag, the component crashes if the image button is included in the `buttonList`. We didn't realize it was coming from the image button before, as we had been using the `buttonList.complex` preset, but the crash does not occur if the image button is removed.

**Comment by mkhstar** [comment]
Yes i think the main suneditor package has a bug at inserting two images and using image in the buttonList @JiHong88 I used it i a pen and got all the buttons rendered back.

**Comment by JiHong88** [comment]
Hi : )

By default, image tags are not enclosed in p tags at suneditor.
If you put an image in a format tag, you can't put more than one, and any other text or tags in the format tag are deleted.

If an image is inserted at editor, check the image tag of the editor and modified the image according to the format of the editor.
When there are two or more images in the format tag such as 'p', 'div', the first image is re-rendered and the second image is erased, resulting in an error.

I'll add exception handling.

Put the image like this:
```javascript
const initialContent = '<img src="https://picsum.photos/200/300"><img src="https://picsum.photos/200/300"><p><br></p>'
```

Thank you.

**Comment by mrezaei8** [comment]
> 
> 
> Hi : )
> 
> By default, image tags are not enclosed in p tags at suneditor.
> If you put an image in a format tag, you can't put more than one, and any other text or tags in the format tag are deleted.
> 
> If an image is inserted at editor, check the image tag of the editor and modified the image according to the format of the editor.
> When there are two or more images in the format tag such as 'p', 'div', the first image is re-rendered and the second image is erased, resulting in an error.
> 
> I'll add exception handling.
> 
> Put the image like this:
> 
> ```js
> const initialContent = '<img src="https://picsum.photos/200/300"><img src="https://picsum.photos/200/300"><p><br></p>'
> ```
> 
> Thank you.

hi,when using this:
TypeError: Argument 1 of Node.appendChild is not an object.

**Comment by JiHong88** [comment]
Hi @mrezaei8 
In the latest version, multiple images in the p tag are rendered normally.

@mkhstar 

> TypeError: Argument 1 of Node.appendChild is not an object.

This error does not occur in SunEditor.
Do you know anything?

**Comment by mkhstar** [comment]
hi @JiHong88  when does this error occur

**Comment by mkhstar** [comment]
I just checked this and it is displaying correctly
