### ISSUE TITLE
Google docs text indentation

### ISSUE THREAD

**Issue by raulhinojosa** [mkhstar/suneditor-react#190]
Hello, I've noticed an issue. 

I have a document in Google Docs - with many different forms to indent paragraphs. When I'm pasting it into `SunEditor`, the last paragraph doesn't get the indent (when you select all then this last one does not highlight that indent). 
This behavior only happens with this kind of indent since the value onPaste or the value itself get's no relevant HTML like spaces or spans with spaces.

I've searched for similar issues but can't find anything about it.

Link to Google Doc: https://docs.google.com/document/d/1dsg3T9CXqqurP0sOO2ITRslkzAaq13ueRXGyexL1faE/edit?usp=sharing
Video: https://www.loom.com/share/6f798ed7a26e4b4697b734c4fdc9edfd

Best regards,

Raul

**Comment by raulhinojosa** [comment]
The solution is now on the last version: [2.37.3](https://github.com/JiHong88/SunEditor/releases/tag/2.37.3). Could you sync to latest build please?

https://github.com/JiHong88/SunEditor/issues/687#issuecomment-810069013

I tested and it works:

https://jsfiddle.net/raulhinojosa/0qt5mf7c/2/

**Comment by raulhinojosa** [comment]
@mkhstar please let me know when ever you sync with latest sun editor

**Comment by raulhinojosa** [comment]
@JiHong88 maybe we can sync up here to latest

**Comment by mkhstar** [comment]
Hi @raulhinojosa 
Sorry for been late. I had a busy schedule. I just updated the package. Fixed in 2.16.2
