### ISSUE TITLE
Placeholder does not scale with fontSize

### ISSUE THREAD

**Issue by sm3sher** [mkhstar/suneditor-react#192]
When I modify the editors `font-size` by setting the `defaultStyle` option, the placeholder does not scale.
It keeps its default `font-size` and I didn't find a way to set the placeholders `font-size`.

Here is an example:
````
 <SunEditor
    setOptions={{
      defaultStyle: "height: 35vh;font-size:16px",
      placeholder: "Write your message...",
    }}
  />
````
<img width="719" alt="Bildschirmfoto 2021-04-09 um 13 07 50" src="https://user-images.githubusercontent.com/39101755/114171478-a0335580-9934-11eb-9f90-3d04db04a2c8.png">

**Comment by sm3sher** [comment]
I wanted to pin this because I still can't find a way to increase the placeholders `font-size`.
It gets more extreme with higher font-sizes, like `24px`:

<img width="274" alt="Bildschirmfoto 2021-05-06 um 09 00 14" src="https://user-images.githubusercontent.com/39101755/117255589-1a7acb00-ae4a-11eb-8595-d7ba8567281d.png">

<img width="274" alt="Bildschirmfoto 2021-05-06 um 09 00 40" src="https://user-images.githubusercontent.com/39101755/117255642-2d8d9b00-ae4a-11eb-8ed2-2a19cc423678.png">

@JiHong88 is there really no way of modifying the placeholder?

**Comment by JiHong88** [comment]
@sm3sher For issues about the basic package, please register in https://github.com/JiHong88/SunEditor
