### ISSUE TITLE
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by sawanmakwana** [mkhstar/suneditor-react#194]
when there is an image inside the anchor tag then it is giving an error of dom exception and in react it is falling to Error Boundary Page.

`<a><img src="http://g-ec2.images-amazon.com/images/G/31/x-locale/common/amazon-logo._V13" /></a>`

Is there any workaround? @JiHong88 @mkhstar

**Comment by JiHong88** [comment]
@sawanmakwana This issue will be resolved at the [SunEditor-milestone3.38.2](https://github.com/JiHong88/SunEditor/milestone/29)
https://github.com/JiHong88/SunEditor/issues/714

**Comment by JiHong88** [comment]
The [2.38.2](https://github.com/JiHong88/SunEditor/releases/tag/2.38.2) version has been updated.
Thank you.

**Comment by mkhstar** [comment]
Fixed in version 2.16.3
