### ISSUE TITLE
Update with latest suneditor (version 2.38.3)

### ISSUE THREAD

**Issue by johnnyoshika** [mkhstar/suneditor-react#196]
May I request an update with the latest suneditor version? I'd like to this enhancement added.

https://github.com/JiHong88/SunEditor/issues/716

Thanks!

**Comment by mkhstar** [comment]
Hi @johnnyoshika 
I just released a new version 2.16.3

**Comment by johnnyoshika** [comment]
@mkhstar Fantastic, thank you so much!
