### ISSUE TITLE
Move suneditor to devDependencies?

### ISSUE THREAD

**Issue by johnnyoshika** [mkhstar/suneditor-react#197]
@mkhstar What do you think about moving `suneditor` to `devDependencies` instead of `dependencies` in `package.json`? You're packaging `suneditor` as part of your build process so the core library isn't used in released versions of `suneditor-react`. However, because it's listed as a dependency, everyone who installs `suneditor-react` also downloads `suneditor`. It also had me confused because `suneditor` in my node_modules folder was different from the code that was running in my browser when using `suneditor-react`. I documented my confusion here: https://github.com/JiHong88/SunEditor/issues/716#issuecomment-821916109

I think this will be solved if you move `suneditor` to `devDependencies`. What do you think?

**Comment by mkhstar** [comment]
You are right man @johnnyoshika.  In the early stages of suneditor-react we needed that as a dependency but for now webpack is bundling everything together. I will resolve that in the next release

**Comment by johnnyoshika** [comment]
@mkhstar  Great, thank you!

**Comment by guido-visser** [comment]
I see that you updated this in version 2.16.4. However, this is a breaking change! I didn't have `suneditor` in my `package.json`, because I relied on `suneditor-react` to do so. This is no big deal, as we can just import `suneditor`, but shouldn't the version number change to 3.0.0 and clearly state this in de readme? Or aren't you using Semantic Versioning?

**Comment by mkhstar** [comment]
Hi man you are very right i will include it again in dependencies

**Comment by guido-visser** [comment]
Okay. I don't think it's a bad idea to move it to `devDependencies`, as users themselves can update to the latest version of `suneditor` and saves you lots of time to constantly keep in sync. However, this should be planned and should be major version update as it's a breaking change.

**Comment by mkhstar** [comment]
Hi @guido-visser 
After careful examination i thought it fit to move it back to the dependencies. This is because I want users using the package to use the same suneditor version that I specify in the package.json.

**Comment by mkhstar** [comment]
Also since the suneditor used in the package is pre built with webpack. Users cannot use a different version other than whatever i specify in the package.json

**Comment by mkhstar** [comment]
But I will consider your suggestion in the future.

**Comment by johnnyoshika** [comment]
OK, thank you
