### ISSUE TITLE
How to submit SunEditor Input together with other form data via React-Hook-Form?

### ISSUE THREAD

**Issue by yelnyaface** [mkhstar/suneditor-react#199]
Hi, how to submit SunEditor Input together with other form data via React-Hook-Form?

**Comment by mkhstar** [comment]
Thanks a lot @nasatome

**Comment by roker15** [comment]
>            <Editor
>               name="description"
>               defaultValue={description}
>               control={control}
>               placeholder="Write a Description..."
>             />

> ```
new value is updated only on second click... i tested in console as well as in alert both triggered in second click only

**Comment by dmanaster** [comment]
This is working for me, except I am getting a warning that "Function components cannot be given refs."

It looks like the ref is being passed in inputProps. 

It seems to be working anyway, but I am afraid that it will cause problems in the future.

How I can fix this?

**Comment by kiriti999** [comment]
Still doesn't work. I am not able to see button list options

![image](https://user-images.githubusercontent.com/13074074/233584224-4c559ab7-1239-4858-a33b-f67bfc881aed.png)
