### ISSUE TITLE
All events do not work

### ISSUE THREAD

**Issue by hauph** [mkhstar/suneditor-react#2]
Hello,

First of all, thank you for your time and hard work on making this component.

I am using it to integrate SunEditor to my React App. However, it seems all your component's React events (onChange, onScroll, onClick, onKeyUp, onKeyDown, etc) do not work. I downloaded your source and tested right on it and all events does not work either

The following are from your file **App.js** (/example/src/App.js), I added **handleChange** just like you wrote on your [document](https://github.com/mkhstar/suneditor-react) but it did not console.log the content

```
import React, { Component } from 'react'
import "suneditor/dist/css/suneditor.min.css";

import SunEditor from 'suneditor-react'


export default class App extends Component {
	handleChange(content){
	    console.log(content); //Get Content Inside Editor
	}

  render () {
    return (
      <div>
        <SunEditor onChange={this.handleChange} />
      </div>
    )
  }
}
```
Do you have any opinion on this matter or did I miss something here that make the events does not work?

**Comment by mkhstar** [comment]
Hi I just checked it and you are right. I think there is a bug in my recent update. Please use version 1.0.17. Until I  fix it. Thanks a lot for noticing me

**Comment by hauph** [comment]
Sorry, where can I get version 1.0.17?

**Comment by mkhstar** [comment]
https://www.npmjs.com/package/suneditor-react/v/1.0.17

**Comment by hauph** [comment]
Right, silly me~~
It seems to work fine on version 1.0.17.
I think I will stick with this version now. Thank you for your help!

**Comment by mkhstar** [comment]
Hi,
The bug has been fixed. I recommend you to use the latest version.
Hope you enjoy. If it ok you can close the issue. Thanks
