### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by felipe-vicente** [mkhstar/suneditor-react#20]
First of all: thanks, for the react adaptation for suneditor. It works great!

I'm using it on a Next.js application and just got a confusing situation:

When I access the page that uses the suneditor-react, it breaks when bundling due to a `ReferenceError: document is not defined`, even when using NoSsr.

Any idea on why is this happening?

**Comment by mkhstar** [comment]
Do you use the window variable `document` in your application

**Comment by yonggwan** [comment]
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr
I hope this helps @felipe-vicente

**Comment by Divlo** [comment]
Yes I did something like that when using Next.js :
```
import dynamic from 'next/dynamic';

const SunEditor = dynamic(
    () => import('suneditor-react'),
    { ssr: false }
);
```

**Comment by felipe-vicente** [comment]
Thanks for the responses, and sorry for taking so long to comment here. I'm not using suneditor-react on the project anymore. My team and I decided to take the "this is not and IDE" way removed the editor from the project. But it is relevant to comment that I ended up using the dynamic import from `next/dynamic`. Actualy, the real question I had at the time was:
My project was  "clientside render only". It failed on bundling becase node has no window and document, when trying to bundle. Right? I tried to mount to component only when window and document were available, but even on this situation, the problem happened.

Any idea why? Or was I just being crazy about it? Anyways, thanks for the atention. Cheers

**Comment by AleksaCupic** [comment]
If you use dynamic imports in useEffect it will work. Next js always pre-renders your page on the server.

**Comment by nitink66** [comment]
@AleksaCupic how can you import dynamically something like 
`import {buttonList} from "suneditor-react";`     in nextjs

**Comment by AleksaCupic** [comment]
@nitink66  First you need to import suneditor component and then select its named export. In this case buttonList. 

`const SunEditorDynamic = dynamic(
    () => import('suneditor-react').then((mod) => mod.buttonList),
      { ssr: false }
    );`

**Comment by nitink66** [comment]
> @nitink66 First you need to import suneditor component and then select its named export. In this case buttonList.
> 
> ```js
> const SunEditorDynamic = dynamic(
>     () => import('suneditor-react').then((mod) => mod.buttonList),
>       { ssr: false }
>     );
> ```



Doing that gives back `ReferenceError: document is not defined`

**Comment by AleksaCupic** [comment]
@nitink66 Oh I see what you're doing. You can only import components dynamically. So, in your case you could do something like this: 
```javascript
import {buttonList} from "suneditor-react";
import dynamic from 'next/dynamic';

const Test = () => {
    const SunEditorDynamic = dynamic(
      () => import('suneditor-react'),
        { ssr: false }
    );

    return (
      <SunEditorDynamic 
        // ... your config 
        setOptions={{
          buttonList: buttonList.basic //.complex .formatting
        }}
      />
    )
}
```

There's no need to import buttonList dynamically anyways, since it is a module.

**Comment by mkhstar** [comment]
Thanks @AleksaCupic 
I am not experienced with nextjs so i couldn't help @nitink66 earlier on. I hope this solved his problem
