### ISSUE TITLE
HTML-content as defaultValue does not render since version 2.16.3

### ISSUE THREAD

**Issue by sm3sher** [mkhstar/suneditor-react#201]
I am using suneditor as an HTML-viewer at some point. Everything was working as expected until version 2.16.3.

I pass in HTML-snippets  like these
```html
<p>This is just an example</p>
````
as **defaultValue** into suneditors react component:
````html
<SunEditor
  ...
  defaultValue={htmlContent}
/>
````
Version 2.16.1 and 2.16.2 do render HTML-snippets appropriately, however the latest version 2.16.3 renders HTML-snippets as plain/text. All HTML-tags become visible to the user, which is unwanted.

@JiHong88 can you confirm this issue?

**Comment by JiHong88** [comment]
@sm3sher Please tell me more detail.
You mean HTML tag  is rendering to text?

**Comment by sm3sher** [comment]
Exactly, I see  `<p>Example</p>` instead of `Example`.

Same goes with all HTML tags, for instance `<strong>I am bold</strong>` was **I am bold**, but is `<strong>I am bold</strong>` now since ver. 2.16.3

**Comment by JiHong88** [comment]
@sm3sher This issue is not reproduced at the basic package and also the "suneditor-react".
Please tell us more detail.
@mkhstar Can you check on this issue?

**Comment by sm3sher** [comment]
@JiHong88  I have to make a correction. I have snippets like these
````html
<html>&lt;p&gt;Test&lt;/p&gt;</html>
````
and they rendered like that before version 2.16.3

<img width="295" alt="Bildschirmfoto 2021-05-06 um 08 52 11" src="https://user-images.githubusercontent.com/39101755/117254193-63ca1b00-ae48-11eb-882a-9d63e3ae5725.png">

and like that after version 2.16.3

<img width="280" alt="Bildschirmfoto 2021-05-06 um 08 54 49" src="https://user-images.githubusercontent.com/39101755/117254482-bc011d00-ae48-11eb-95c3-f05a77e26210.png">

Now you should be able to reproduce that issue.

**Comment by JiHong88** [comment]
@sm3sher This is the correct behavior now.
This is a fix for a bug.
Please edit the snippet.
`<p>Test</p>`

**Comment by sm3sher** [comment]
Okay, now I know that I have to explicitly use HTML-Tags instead of encoded ones
