### ISSUE TITLE
expose ref prop

### ISSUE THREAD

**Issue by devkral** [mkhstar/suneditor-react#202]
Currently the ref prop is not specified in the props and for using it (with typescript), a typecast is required.
It would be nice if the ref prop would be specified in the props.
Something like:
SunEditorReactProps {
...
ref: React.Ref<whatever applies>
...
}

**Comment by mkhstar** [comment]
Hi @devkral 
Can you provide an example of your code. Please make sure to follow how it is done in the documentation because typecast is not required

**Comment by mkhstar** [comment]
Reopen the issue if the problem still persists

**Comment by devkral** [comment]
https://github.com/devkral/secretgraph/blob/suneditor-bugreport/assets/js/Client/components/SunEditor.tsx

I have to typecast to use your library.
The reason for this default is that not every component can hold a ref. So you have to explicitly expose it
