### ISSUE TITLE
editor.getContents() doesn't update when writing in the editor

### ISSUE THREAD

**Issue by wiktoriavh** [mkhstar/suneditor-react#203]
I have the following code  
```js
  useEffect(() => {
    const core = editorRef.current.editor.core;
    const editor = editorRef.current.editor;
    console.log(editor.getContents(true));
  }, [editorRef.current]);
```
I want to grab the updated version of the content inside of texteditor. But ti doesn't return anything. I must be doing something wrong.

**Comment by wfelipe99** [comment]
I'm new to SunEditor, but is there any difference from using .getContents() and this approach? https://github.com/mkhstar/suneditor-react/issues/198#issuecomment-832372153

**Comment by mkhstar** [comment]
Hi guys the best way to get the current contents of the editor is by using the `onChange` prop

**Comment by mkhstar** [comment]
check out the documentation to learn more
```jsx
handleChange(content){
	console.log(content); //Get Content Inside Editor
}
render() {
	return <SunEditor onChange={handleChange} />
}

```

**Comment by Braweria** [comment]
thank you both for the swift answer @mkhstar @wfelipe99
