### ISSUE TITLE
expose ref prop - with example

### ISSUE THREAD

**Issue by devkral** [mkhstar/suneditor-react#204]
sry for spamming, I have no right to reopen issue #202.

https://github.com/devkral/secretgraph/blob/suneditor-bugreport/assets/js/Client/components/SunEditor.tsx

If you remove the ugly typecast and directly use SunEditorTyped the compilation crashes.

The reason for this default is that not every component can hold a ref.
So React requires to explicitly expose it.

**Comment by mkhstar** [comment]
Can you try with the latest version
