### ISSUE TITLE
unable to import css with monorepo

### ISSUE THREAD

**Issue by jsonpj3wt** [mkhstar/suneditor-react#205]
Hi All,

I am able to include the cdn for suneditor and it works fine, but given the structure of our codebase, I am unable to do the following:

`import 'suneditor/dist/css/suneditor.min.css'; // Import Sun Editor's CSS File`.

If I do not use the cdn, no styles are applied.  I assumed it was webpack but I am not seeing anything glaring in there:

```
test: /\.css$/i,
use: ['style-loader', 'css-loader', 'postcss-loader'],
```

Anyone have an idea how to resolve this?

Thanks!

**Comment by pedroposada** [comment]
I am having similar issue
```
Cannot find module: 'suneditor/dist/css/suneditor.min.css'. Make sure this package is installed.
```
