### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by fateme-ezzati** [mkhstar/suneditor-react#208]
I install suneditor several times but my node module have a SyntaxError error:
SyntaxError: Cannot use import statement outside a module

it happened for 
module.exports = require("suneditor-react");

**Comment by mkhstar** [comment]
Hi @fateme-ezzati 
suneditor-react is used in only browsers. Can you mention your environment and also paste the code that is causing the  problem

**Comment by samuelgoldenbaum** [comment]
I am seeing the same now in a [Next.js](https://nextjs.org/) page with when using SSR. Navigating client-side all is fine and the editor loads correctly, but reloading the page causes the same error. Same error if trying to build the project using _next build_

_package.json:_
```
    "suneditor": "^2.39.0",
    "suneditor-react": "^3.0.0",

    "next": "^10.2.1",
```
_page:_
```
import React from 'react';
import SunEditor from 'suneditor-react';
import 'suneditor/dist/css/suneditor.min.css';

const Page = () => {
  return (
    <>
      <SunEditor />
    </>
  );
};

export default Page;
```

_error:_
```
/someproject/src/node_modules/suneditor-react/dist/index.js:1
import * as buttonList from "./misc/buttonList";


 1 of 1 unhandled error
Server Error
SyntaxError: Cannot use import statement outside a module

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///someproject/src/node_modules/suneditor-react/dist/index.js (1)
wrapSafe
internal/modules/cjs/loader.js (984:16)
Module._compile
internal/modules/cjs/loader.js (1032:27)
Object.Module._extensions..js
internal/modules/cjs/loader.js (1097:10)
Module.load
internal/modules/cjs/loader.js (933:32)
Function.Module._load
internal/modules/cjs/loader.js (774:14)
Module.require
internal/modules/cjs/loader.js (957:19)
require
internal/modules/cjs/helpers.js (88:18)
Object.suneditor-react
file:///someproject/src/.next/server/pages/admin/articles/create.js (99:18)
__webpack_require__
file:///someproject/src/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///./pages/admin/articles/create.tsx (8:73)
Object../pages/admin/articles/create.tsx
file:///someproject/src/.next/server/pages/admin/articles/create.js (22:1)
__webpack_require__
file:///someproject/src/.next/server/webpack-runtime.js (33:42)
__webpack_exec__
file:///someproject/src/.next/server/pages/admin/articles/create.js (109:52)
<unknown>
file:///someproject/src/.next/server/pages/admin/articles/create.js (110:170)
Function.__webpack_require__.X
file:///someproject/src/.next/server/webpack-runtime.js (116:21)
<unknown>
file:///someproject/src/.next/server/pages/admin/articles/create.js (110:47)
```

**Comment by mkhstar** [comment]
Hi @samuelgoldenbaum  and @fateme-ezzati 
Nextjs expects a common js module system while doing ssr. If I change suneditor-react to commonjs, the suneditor module system would still be in es module. which will result in the same error. So what I recommend you do is to disable ssr. Eg. below:
```tsx
import dynamic from "next/dynamic";
import "suneditor/dist/css/suneditor.min.css";

 const SunEditor = dynamic(() => import("suneditor-react"), {
   ssr: false,
 });

const Page = () => {
  return (
    <>
      <SunEditor />
    </>
  );
};

export default Page;

```

**Comment by samuelgoldenbaum** [comment]
> Hi @samuelgoldenbaum and @fateme-ezzati
> Nextjs expects a common js module system while doing ssr. If I change suneditor-react to commonjs, the suneditor module system would still be in es module. which will result in the same error. So what I recommend you do is to disable ssr. Eg. below:
> 
> ```tsx
> import dynamic from "next/dynamic";
> import "suneditor/dist/css/suneditor.min.css";
> 
>  const SunEditor = dynamic(() => import("suneditor-react"), {
>    ssr: false,
>  });
> 
> const Page = () => {
>   return (
>     <>
>       <SunEditor />
>     </>
>   );
> };
> 
> export default Page;
> ```

@mkhstar thanks for the quick feedback. I can confirm that works -- except it breaks if we try to set basic options.

```
Unhandled Runtime Error
TypeError: Cannot read property 'bold' of undefined

Call Stack
Object._defaultButtons
node_modules/suneditor/src/lib/constructor.js (590:0)
Object._createToolBar
node_modules/suneditor/src/lib/constructor.js (720:0)
Object.init
node_modules/suneditor/src/lib/constructor.js (39:0)
Object.create
node_modules/suneditor/src/suneditor.js (67:21)
eval
node_modules/suneditor-react/dist/SunEditor.js (29:25)
```

Example:
```
<SunEditor
  setContents={content}
  onChange={handleChangeCallback}
  setOptions={{
    lang: 'en',
    width: '960px',
    height: '100%',
    templates: [{
      name: 'quote',
      html: '<blockquote><p>A quote.</p><footer><cite>An author</cite></footer></blockquote>'
    }],
    callBackSave: handleSaveCallback,
    buttonList: [
      ['formatBlock'],
      ['bold', 'underline', 'italic'],
      ['align', 'horizontalRule', 'list'],
      ['table', 'link', 'image', 'video'],
      ['showBlocks', 'codeView'],
      ['preview', 'save', 'undo', 'template']
    ],
  }}
 />
```

**Comment by mkhstar** [comment]
Hi @samuelgoldenbaum, 
This time you are receiving a different error. The setOptions lang option doesn't support string. This is a typescript type bug that will be removed later. If you want to set lang use the prop. Eg. 
```jsx
<SunEditor lang="en" />
```

**Comment by fateme-ezzati** [comment]
@mkhstar @samuelgoldenbaum  Thank you for your helpfull  feedback .I had the same issue and it solved ♥♥
