### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by itartpro** [mkhstar/suneditor-react#209]
> Build error occurred
/app/front/node_modules/suneditor-react/dist/index.js:1
import SunEditor from "./SunEditor";

SyntaxError: Cannot use import statement outside a module

I got this during an attempted build with next.js

**Comment by mkhstar** [comment]
Hi @itartpro 
Refer to #208

**Comment by itartpro** [comment]
Thank you so much! I confirm it's working on a production build, in a docker node:alpine container.

**Comment by itartpro** [comment]
wait no...its flickering like crazy and console keeps outputting
TypeError: Cannot read property '_buttonTray' of undefined
and
TypeError: Cannot read property 'charCounter' of undefined



`import 'suneditor/dist/css/suneditor.min.css'
import {useRef, useState} from 'react'
import DropImages from './dropzone/drop-images'
import dynamic from 'next/dynamic'

export default function Wysiwyg({drop_name, content, setContent, imageLocation, instructions}) {
    const editor = useRef();
    const dropRef = useRef();
    const [showDrop, setShowDrop] = useState(false);

    const SunEditor = dynamic(() => import('suneditor-react'), {
        ssr: false,
    });

    const handleChange = e => setContent(e);

    const editWYSIWYGGallery = () => {
        if(!imageLocation) return false;
        if(!showDrop) setShowDrop(true);
        const st = dropRef.current.style;
        if(st.maxHeight === 'initial') {
            st.maxHeight = '600px';
            setTimeout(() => {st.maxHeight = '0px'}, 300);
            st.overflow = 'hidden';
        } else {
            st.maxHeight = '600px';
            st.transition = 'all .3s'
            st.overflow = 'hidden';
            setTimeout(() => {st.maxHeight = 'initial'}, 300);
        }
    }

    const getSunEditorInstance = sunEditor => {
        editor.current = sunEditor;
    };

    if(instructions && imageLocation) instructions.location = imageLocation;

    const edit_gallery = {
        name: 'edit_gallery',
        title: 'Редактировать галерею',
        display: 'command',
        add: (core, targetElement) => {
            const context = core.context;
            context.customCommand = {
                targetButton: targetElement
            };
        },
        innerHTML: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">'+
            '<path fill="none" stroke="#000" stroke-linecap="round" stroke-width="6" d="M31 48V3M16 20L31 3l15 16"/>'+
            '<path fill="none" stroke="#000" stroke-linecap="round" stroke-width="6" d="M8 46v16h46V46"/></svg>',
        action: editWYSIWYGGallery
    };

    const sunOptions = {
        height: '300px',
        pasteTagsBlacklist: 'span|pre|style|&nbps;',
        charCounter: true,
        imageFileInput: false,
        placeholder: "Напишите эпос...или хотя бы 3000 символов для SEO. Вы ведь молодца...Вам ведь нужен SEO.",
        buttonList: [
            ['codeView', 'showBlocks'],
            ['formatBlock', 'list', 'bold', 'underline', 'italic', 'strike', 'subscript', 'superscript'],
            ['outdent', 'indent'],
            ['align', 'horizontalRule'],
            ['table', 'link'],
            ['removeFormat', 'preview']
        ]
    };

    if(imageLocation) {
        const imageStuff = ['video', 'image', 'imageGallery', 'edit_gallery']
        sunOptions.imageGalleryUrl = '/api/sungallery/'+imageLocation.split('/').join('-')
        sunOptions.buttonList[4].push(...imageStuff)
        sunOptions.plugins = [edit_gallery]
    }

    return (
        <>
            <SunEditor
                lang="ru"
                getSunEditorInstance={getSunEditorInstance}
                setOptions={sunOptions}
                onChange={handleChange}
                setContents={content}
            />
            <style global jsx>{`
              .sun-editor {
                margin-bottom: 20px;
              }
            `}</style>
            {showDrop && <DropImages dropRef={dropRef} drop_name={drop_name} instructions={instructions} />}
        </>
    );
};`

**Comment by itartpro** [comment]
Hey, so if you ever get to reading this my issue was that I was setting the contents, from onChange, inside a state variable - and when state changed everything re-rendered and caused hiccups. Now I store my contents in a useRef and everything works just fine.

``
let text = useRef('');
const appendContent = textFromSunEditor => text.current = textFromSunEditor
``
