### ISSUE TITLE
Toolbar icons not show

### ISSUE THREAD

**Issue by pmsferreira** [mkhstar/suneditor-react#21]
Hello!

I try to use this library with a minimal configuration but when I tested, the result was a little strange:
![Screenshot 2020-02-03 at 16 35 49](https://user-images.githubusercontent.com/16557512/73671716-69fca500-46a3-11ea-8cd6-91cfd915e046.png)
Somehow, the toolbar didn't show options' icons, only characters (but it works anyway).

My file only have this:

<img width="870" alt="Screenshot 2020-02-05 at 12 42 10" src="https://user-images.githubusercontent.com/16557512/73842686-f67aa500-4814-11ea-8e80-d24b9219267e.png">

Any idea?

Thanks, 
Pedro

**Comment by mkhstar** [comment]
This means your icons are not downloading. Which browser are you using

**Comment by pmsferreira** [comment]
> This means your icons are not downloading. Which browser are you using

I tested on Google Chrome

**Comment by mkhstar** [comment]
Are there any errors logged to the console?

**Comment by pmsferreira** [comment]
<img width="603" alt="Screenshot 2020-02-11 at 09 15 55" src="https://user-images.githubusercontent.com/16557512/74223748-46db8200-4caf-11ea-9376-a326bcfc3a5e.png">

**Comment by randywgreen** [comment]
Thanks for the great editor!  I am experiencing this same issue on Chrome 79.0.3945.130.

**Comment by mkhstar** [comment]
@JiHong88  the fonts are not parsing correctly on some browsers. Do you have any idea why?

**Comment by JiHong88** [comment]
I think it could be a configuration problem with the bundle module you are using. (with webpack)

**Comment by mkhstar** [comment]
https://github.com/mkhstar/suneditor-react/blob/master/webpack.config.js

**Comment by JiHong88** [comment]
I plan to change the web font to "inline svg"
When complete, similar issues will no longer occur.

**Comment by JiHong88** [comment]
@pmsferreira @randywgreen  @mkhstar 
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
Removed the web font and replaced it with Inline svg
Thank you.

**Comment by proggrkim** [comment]
@JiHong88 I'm using "suneditor-react": "^2.7.2", icons for toolbar aren't shown up. I do not get any console errors related to this, so I'm guessing it just doesn't know where/how to get those icons. 

<img width="795" alt="Screen Shot 2020-03-22 at 12 11 18 AM" src="https://user-images.githubusercontent.com/62181959/77242147-b196ac00-6bd1-11ea-90a4-7716f8195c9e.png">
`const SunEditor = dynamic(
  () => import('suneditor-react'),
  { ssr: false }
)`
`import '../../node_modules/suneditor/dist/css/suneditor.min.css'; `
`<div className='form-group'><SunEditor/></div>`

Am I missing some configuration here? 
Thank you.

**Comment by JiHong88** [comment]
Hi @proggrkim 
It looks not load web font.
Is the rendered `<i>` tag in the button?

**Comment by proggrkim** [comment]
Thanks for your reply. Yes, I do see i tag as below. However, I don't find se-icon* in ./dist/css/suneditor.min.css. Am I using a wrong file somehow?

<img width="615" alt="Screen Shot 2020-03-22 at 10 46 14 AM" src="https://user-images.githubusercontent.com/62181959/77252503-9310cf00-6c2a-11ea-88a3-ea743fb6861d.png">

**Comment by JiHong88** [comment]
It seems that the versions of "suneditor" and "suneditor-react" do not match.
As of "suneditor" version 2.27.0, the web font has been removed and replaced with 'inline svg'.
Use the version of "suneditor-react" to 2.8.0.

**Comment by proggrkim** [comment]
@JiHong88  It looks like the issue is fixed under suneditor@2.27.0, but npm i suneditor-react pulls down 2.7.2 which depends on the older version of suneditor. When npm i suneditor-react@2.8.0, everything works, and I do see <svg> tag instead of <i> tag. So I assume there was a bit of changes made, but dependency wasn't caught up.  Thank you for your help!
