### ISSUE TITLE
Module parse failed: Unexpected token (from dist/index.js file in JS environment)

### ISSUE THREAD

**Issue by lukwallace** [mkhstar/suneditor-react#210]
Hi there!

I am running into an issue setting up with a webpack build -- I'm sure I'm missing some prerequisite. Would it be possible to update the README to reflect this?

My guess is that `export as * namespace` isn't currently supported -- an initial search on the issue shows someone using Vue running into the same problem, so I assume this is TS related: https://stackoverflow.com/questions/64045868/vue-module-parse-failed-when-using-export-as-in-typescript

```
ERROR in ./node_modules/suneditor-react/dist/index.js 2:9
Module parse failed: Unexpected token (2:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import SunEditor from "./SunEditor";
> export * as buttonList from './misc/buttonList';
| export default SunEditor;
|
```

**Comment by AhmedElywa** [comment]
me to using with nextjs

```
error - ./node_modules/suneditor-react/dist/index.js
Module parse failed: Unexpected token (2:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import SunEditor from "./SunEditor";
> export * as buttonList from './misc/buttonList';
| export default SunEditor;
|
/Users/ahmed/Sites/TatarGame/node_modules/suneditor-react/dist/index.js:1
import SunEditor from "./SunEditor";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

with version under 3 it's working good

**Comment by mkhstar** [comment]
Hi @AhmedElywa and @lukwallace 

There is a breaking change since version 3. Disable ssr to make it work. Check this issue #209

**Comment by mkhstar** [comment]
You can also refer to the readme

**Comment by AhmedElywa** [comment]
if we work with web pack 4 will see the error. Even if we use dynamic, we must use web pack 5

**Comment by mkhstar** [comment]
Hi guys can you confirm if the problem still persists? This is because the i have change the module to commonjs

**Comment by AhmedElywa** [comment]
Yes fixed for me
