### ISSUE TITLE
Losing focus after pausing to type

### ISSUE THREAD

**Issue by guido-visser** [mkhstar/suneditor-react#212]
I noticed that when upgrading from version `2.16.5` to `3.0.0`, the editor loses focus 0.5 seconds after you've stopped typing. This renders the package completely unusable in my case. Can you please look at this issue?

The scenario is reproducable here:
https://codesandbox.io/s/hungry-allen-wez4b

Reproduce in this way:
https://user-images.githubusercontent.com/16164800/119631845-8da3ab80-be10-11eb-9cd3-1f1e773a11cf.mp4

**Comment by mkhstar** [comment]
@guido-visser 
I have realized that you are using two way binding (using setContents and onChange) Though it is not needed. I will fix that in the next version. Thank you

**Comment by guido-visser** [comment]
Thanks! Can you explain what I'm doing wrong, or how it's supposed to be?

**Comment by mkhstar** [comment]
Hi @guido-visser 
You could do it this way
```jsx
import SunEditor from "suneditor-react";
import "suneditor/dist/css/suneditor.min.css";
import "./styles.css";

export default function App() {
  return (
    <div className="App">
      <SunEditor
        defaultValue="Henk"
        setOptions={{
          addTagsWhitelist: "table|thead|tbody|tr|td|title|html|body",
          mode: "classic",
          attributesWhitelist: {
            all:
              "style|bgcolor|border|cellpadding|colspan|cellspacing|align|width|allow|allowfullscreen|frameborder",
            input: "checked"
          },
          //callBackSave: handleSave,
          templates: []
        }}
      />
    </div>
  );
}
```

There is no need to use setContents and onChange in this scenario. When the value of setContents changes the editor looses focus. This will be fixed in the next version

**Comment by guido-visser** [comment]
It's not necessary In the particular example, but it is needed in another project I'm working on which caused me to see the bug. Thanks! Will be looking forward to the new version. Good work!

**Comment by guido-visser** [comment]
Any progress indication on this?

**Comment by mkhstar** [comment]
Hi @guido-visser 
I will be updating the package during the weekend

**Comment by mkhstar** [comment]
I just updated the version @guido-visser

**Comment by mkhstar** [comment]
Reopen the issue if the problem still persists

**Comment by Gabsys** [comment]
@guido-visser are you still facing the issue? I am still facing this issue with the following version:
```
"suneditor": "^2.41.3",
    "suneditor-react": "^3.2.0",
```
