### ISSUE TITLE
Getting error: Module not found

### ISSUE THREAD

**Issue by saiyamjain143** [mkhstar/suneditor-react#213]
Module not found: Error: Can't resolve 'react/jsx-runtime'
How to fix this, if using older version of react and typescript
 "react": "16.8.6",
"typescript": "3.4.5",

**Comment by EdgarKisman** [comment]
@saiyamjain143 try updating React to version 16.14, this worked for me. My React version was 16.9.0.
Looks like this is a known problem https://github.com/facebook/react/issues/20235

**Comment by mkhstar** [comment]
Thanks @EdgarKisman

**Comment by FarzanKhan009** [comment]
Any solution so far?
