### ISSUE TITLE
instance of the editor is undefined (Editor.current)

### ISSUE THREAD

**Issue by ghilaslinz** [mkhstar/suneditor-react#215]
hi @mkhstar, 

I'm coming from this issue https://github.com/JiHong88/SunEditor/issues/769#issue-906857931
I want to enable disable a plugin with my keyword, so i created a function for that in `handleKeyDown`, but i have this error :

`TypeError: Cannot read property 'core' of undefined`

When i investigate and search for the value of the editor.current, i found it is "undefined" in the `handleKeyDown` (so it seems that it lost it's context).

Is there a way to have the instance of the editor inside the `handleKeyDown` function.

Ps : customCommand is the name of the plugin that i copied from the suneditor's website, i didn't wrote it here to avoid you to read a big code.
```

import React, { useState,useEffect,  useRef } from 'react';
import SunEditor from 'suneditor-react';
import 'suneditor/dist/css/suneditor.min.css'; // Import Sun Editor's CSS File

const MyComponent = props => {

 

 

 /**
   * @type {React.MutableRefObject<SunEditor>} get type definitions for editor
   */
  const editor = useRef();

  // The sunEditor parameter will be set to the core suneditor instance when this function is called
  const getSunEditorInstance = (sunEditor) => {
      editor.current = sunEditor; 
 
      
  };

  const handleKeyDown = (e) => {
    const { key, shiftKey } = e;
    const keyCode = e.which || e.keyCode;
   
    if (key === 'Enter' || keyCode === 13) {
      console.log(editor.current);
      e.preventDefault();
         editor.current.core.actionCall("customCommand", "command", editor.current.core.context.customCommand.targetButton);
    
      return false;
    }
 }

   
  return (
    
    <div>
   
      <SunEditor  
            getSunEditorInstance={getSunEditorInstance}
            onKeyDown={handleKeyDown}
            setDefaultStyle={`
     
                    width: 100%;
                   
                    height: 700px;
                    
                 
                `}
              
                    setOptions={{
                       
                  
                
                 plugins: [
                  
                   plugin_command,
             
                ],
                
  
                 
                    buttonList: [  
                        ['bold'],
                        [ 'underline', 'italic'],
                        ['formatBlock', 'align', 'list'],
                        [ 'table','image','preview','fullScreen', 'lineHeight', 'fontSize','blockquote'],
                        ['undo', 'redo', 'customCommand'],    
                    ],
                }}
       />

     <div>
   
  
 </div>

    </div>
  );
};

export default MyComponent;

```

**Comment by mkhstar** [comment]
Hi @ghilaslinz 
I have tried but I am not getting this error in anyway.
I did a demo here [https://codesandbox.io/s/aged-sky-khwuf?file=/src/MyComponent.js](https://codesandbox.io/s/aged-sky-khwuf?file=/src/MyComponent.js)

**Comment by ghilaslinz** [comment]
@mkhstar 
I would like to thank you.

Thanks of your demo i understood that my version of react-suneditor was old, so I update with the new version, and now it's working.

Big thanks also for @JiHong88  for all his advices and his patience with me.

You can close the issue.

Best regards
