### ISSUE TITLE
How to submit SunEditor Input via Formik?

### ISSUE THREAD

**Issue by EdgarKisman** [mkhstar/suneditor-react#216]
Hello,
I have a problem submitting input data from SunEditor via Formik, the onChange event is not fired even after I added a name property (also tested adding id).  The onBlur event is triggered, but I get the following warning:
`react_devtools_backend.js:2560 Warning: Formik called `handleBlur`, but you forgot to pass an `id` or `name` attribute to your input:
   `Warning: Formik called `handleBlur`, but you forgot to pass an `id` or `name` attribute to your input:
   ` <div class="se-wrapper-inner se-wrapper-wysiwyg sun-editor-editable" contenteditable="true" scrolling="auto" style="height: 30vh;" spellcheck="false" data-gramm="false"><p>Test Beschreibung</p></div>`
    Formik cannot determine which value to update. For more info see https://github.com/jaredpalmer/formik#handleblur-e-any--void`

and the value does not update.
Any Ideas how to fix this problem, or someone with a similar problem ?

**Comment by mkhstar** [comment]
Please @EdgarKisman can you post a small demo demonstrating the problem?

**Comment by EdgarKisman** [comment]
@mkhstar I will post a some example code later if you need, but I think I found the problem. According to the post here https://stackoverflow.com/questions/23892547/what-is-the-best-way-to-trigger-onchange-event-in-react-js/46012210

The problem is because of react 16.x. It does not handle .value= properly so an onChange event never triggers. The fix would be to change the line 57 and maybe 47 in /src/SunEditor.tsx

I tested the same behavior with a plain textarea and got the same result, if I use .value=foo then onSubmit the value is empty but if I use the example code from stackoverflow it works.

This is how my example code looks like:
```
const textAreaRef = useRef<HTMLTextAreaElement>(null)

const foo =  () => {
   const nativeTextAreaValueSetter = Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, "value")!.set
    nativeTextAreaValueSetter!.call(textAreaRef.current, 'react 16 value');

    const ev2 = new Event('input', { bubbles: true });
    textAreaRef.current!.dispatchEvent(ev2);
}

<textarea name={props.name} ref={lsl} />
```

**Comment by EdgarKisman** [comment]
@mkhstar did you have time to analyze this bug? I would appreciate it if you could fix this asap, because I need to enroll this to our production build. I could create a pull-request if you need.

**Comment by mkhstar** [comment]
Hi @EdgarKisman 
The idea of the name prop is to be used in forms that are going to be submitted with an html form. I don't want to trigger any event with respect to that.

**Comment by theasifimam** [comment]
One possible solution will be this.

`<SunEditor
                  defaultValue={values.content}
                  onChange={(val) => {
                    var e = { target: { value: val, name: "content" } };
                    handleChange(e);
                  }}
                 />`
