### ISSUE TITLE
Readonly mode

### ISSUE THREAD

**Issue by krAlena** [mkhstar/suneditor-react#217]
Hello,
I am using editor like an editor and like a html-viewer (If display content as pure inner html it looks different than in editor).
My issue is next: when I set prop disabled=true 

`<SunEditor
      disable={true}
      hideToolbar={true}
  />`

its perfect viewer but lost ability to copy content.

I try another way:

`<SunEditor
                    hideToolbar={true}
                    onCut={this.noop}
                    onPaste={this.noop}
                    onKeyDown={this.noop}
 />`
 
 noop = (event) => {
      let cKey = 67;

      if (event.ctrlKey && event.keyCode == cKey) {
          // allow Ctrl + C
      }
      else {
          event.preventDefault();
          return false;
      }
  };
  
  Now I can copy content, but embeded elements (iframe with video) is overlaped by `<figure></figure>` tag and its lock clickable area.
  
  Then I have override some styles and it worked

```
  .viewer-sun-editor-parent
    .se-line-breaker
        display: none !important
    .sun-editor-editable[contenteditable=true]
        figure
            z-index: 0
            a,
            iframe,
            img,
            video
                z-index: 100
```
  
What is the right way to implement readOnly option?
Thanks

**Comment by mkhstar** [comment]
Hi @krAlena 
Right now there is no readme mode in suneditor. It could be a cool new feature @JiHong88. 
Thank you

**Comment by JiHong88** [comment]
@krAlena @mkhstar It's good idea.
I'll add this feature next version.

**Comment by krAlena** [comment]
@JiHong88 Thank you! I am looking forward &#128522;

**Comment by JiHong88** [comment]
@krAlena @mkhstar
The [2.41.0](https://github.com/JiHong88/SunEditor/releases/tag/2.41.0) version has been updated.
A readOnly method has been added.

**Comment by krAlena** [comment]
@JiHong88 Thank you! I have updated version and it works fine except clicking on the links (expectation: open the link).
Additional handler onClick has helped:
```
<SunEditor  
  readOnly={true}
  hideToolbar={true}
  onClick={this.tryOpenLink} 
/>

tryOpenLink = (event) => {
    let eventTarget = event.target;
    if (eventTarget.tagName == "A"){
        let url = eventTarget.href;
        window.open(url, eventTarget.target)
    }
}
```

**Comment by mkhstar** [comment]
hi @krAlena 
readOnly prop is not available to SunEditor react component yet. I have to update suneditor-react to reflect that.

**Comment by krAlena** [comment]
Hi @mkhstar!
Yes indeed 😅, hidden toolbar looks like readOnly mode, but content is able to edit. 
I will wait for the SunEditor's  readOnly prop.
Thanks

**Comment by alp4031** [comment]
If it is readOnly, will users be able to select and copy?

**Comment by krAlena** [comment]
I think yes, similar attribute "readonly" of textarea or input.
In a readOnly text area, the content cannot be changed, but a user can tab to it, highlight it and copy content from it.

**Comment by JiHong88** [comment]
@mkhstar There is a bug where copying does not work in read-only mode.
I will update the version today.

**Comment by JiHong88** [comment]
@mkhstar The [2.41.1](https://github.com/JiHong88/SunEditor/releases/tag/2.41.1) version has been updated.
Thank you.

**Comment by mkhstar** [comment]
@krAlena 
I just added the readOnly prop. Thank you

**Comment by krAlena** [comment]
Hi! I have some issue
    suneditor: 2.41.2,
    suneditor-react: 3.2.0
    
 readOnly  props stopped working.
 Is able to make editor block's contenteditable=false in readOnly  mode? Plugins like Grammarly detect contenteditable blocks and allow edit them, I don't think it's right...
