### ISSUE TITLE
Highlighting search text results

### ISSUE THREAD

**Issue by krAlena** [mkhstar/suneditor-react#218]
Is there some plugin for highlighting and replacing text in the editor when searching with RegExp?

![decorators](https://user-images.githubusercontent.com/26471239/122825186-46fb8100-d2ea-11eb-9c64-320d4587f8f4.gif)

Thanks

**Comment by mkhstar** [comment]
@JiHong88

**Comment by JiHong88** [comment]
@krAlena It will be added maybe few month later..

**Comment by krAlena** [comment]
@JiHong88  That would be great, thank you!

> @krAlena It will be added maybe few month later..
