### ISSUE TITLE
defaultTag is not working in nextjs

### ISSUE THREAD

**Issue by iatulb** [mkhstar/suneditor-react#220]
I am using SunEditor with below syntax.

Here i am still getting default tag as "p".
I would like to change it "div" but its not working

<SunEditor
            placeholder="Please type here..."
            setContents={props.value}
            setOptions={{
                // Other option
                maxCharCount: 299,
                'defaultTag': 'div',
                "buttonList": [
                    [
                        "undo",
                        "redo",
                        "font",
                        "fontSize",
                        "paragraphStyle",
                        "bold",
                        "underline",
                        "italic",
                        "fontColor",
                        "hiliteColor",
                        "removeFormat",
                        "list",
                        "link",
                        "image",
                        "video",
                        "audio",
                        "imageGallery"
                    ]
                ],

            }}

**Comment by JiHong88** [comment]
The "defaultTag" option does not replace existing tags.
Check the "props.value" value.

**Comment by mkhstar** [comment]
Hi @iatulb ,
I have tested this on nextjs but it was working fine. If you think this issue still persists please provide a demo

**Comment by iatulb** [comment]
![image](https://user-images.githubusercontent.com/23653187/123797516-e11f8280-d903-11eb-9433-d7712e247ebf.png)

You can see "p" tag even after i have replace it with "div".

Could you please give me what you did?

**Comment by JiHong88** [comment]
Tags that already exist are not changed.
Did you put the "P" tag as the initial value?
Please tell me the exact reproduce method.
