### ISSUE TITLE
Will you update latest suneditor for XSS attack problem

### ISSUE THREAD

**Issue by okandavutosf** [mkhstar/suneditor-react#221]
Hi, for iframe xss attacks i opened issue to suneditor and @JiHong88  solved it. Will you update suneditor-react to 2.41.1 for this solution. Thanks for the component. @mkhstar 

https://github.com/JiHong88/SunEditor/issues/784

**Comment by mkhstar** [comment]
Hi @okandavutosf 
From now you don't need to wait for suneditor-react to sync with suneditor. You can just install the latest version of suneditor

**Comment by okandavutosf** [comment]
I updated the sun editor but i doesn't work that iframe attack problem

**Comment by okandavutosf** [comment]
Can you help me about this issues because i updated but it didnt effect that iframe attack solution @mkhstar  @JiHong88
