### ISSUE TITLE
html pasted style and images removed

### ISSUE THREAD

**Issue by RAMKUMARDANE** [mkhstar/suneditor-react#222]
I copied this

![image](https://user-images.githubusercontent.com/6815283/124209420-219b1e00-db07-11eb-9438-f96eff275d9a.png)

as I paste it appears like this
![image](https://user-images.githubusercontent.com/6815283/124209364-06301300-db07-11eb-9cd4-bb0b91f12a37.png)

and after a few second it appears like this
![image](https://user-images.githubusercontent.com/6815283/124209595-72127b80-db07-11eb-9a51-b53612c9cae1.png)

And 
i tried 
++++++++++++++++++
const sePaste = (event, cleanData, maxCharCount) => {
  let cad = cleanData.replace(/style="[a-zA-Z0-9:;\.\s\(\)\-\,]*"/gi, '');
  cad = cleanData.replace(/<figure *"/gi, '<figure class="__se__float-none" ');
  cad = cleanData.replace(/<img *"/gi, '<img class="__se__float-none" ');
  // console.log("cad : " + cad);
  return cad;
}
++++++++++++++++++++++
<SunEditor
                ref={CompanyDescriptionRef}
                onBlur={(e, editorContents) => {
                  setCompanyDescription(editorContents);
                }}
                onPaste={sePaste}
                setOptions={{
                height: 200,
                    "attributesWhitelist": {
                      "all": "style|alt|data-src|src",
                      "input": "checked"
                    },
++++++++++++++++++++++++++++++++
can any one help me out to fix this

**Comment by mkhstar** [comment]
Please can you open this issue at the core suneditor package
