### ISSUE TITLE
suneditor src included in bundle

### ISSUE THREAD

**Issue by AsheshL** [mkhstar/suneditor-react#223]
Is there a way to exclude the plugins (which are not being used) of suneditor from the bundle.
suneditor document provides loading what you need for proper tree shaking.

Even though react-suneditor dist is tiny, loading the suneditor src has a major footprint.

Any help in resolving this is appreciated.

**Comment by mkhstar** [comment]
Alright @AsheshL i will try to clean up that the next version

**Comment by mkhstar** [comment]
Hi @AsheshL,
in the latest version, you can now choose only the plugins you would like to use by overriding the plugins option in setOptions
