### ISSUE TITLE
Issue with SSR

### ISSUE THREAD

**Issue by Adityacs001** [mkhstar/suneditor-react#224]
# What happened ?
In latest version, Editor throws error while building project in Nextjs.

Error message  "SyntaxError: Cannot use import statement outside a module in suneditor.js".

Possibly suneditor issue. Tried setting "type":"module" , module setting in tsconfig.js file though nothing worked.

# Version 
3.2.0

# Workaround 
Downgrade to version @2.16.3 worked.

**Comment by mkhstar** [comment]
Hi @Adityacs001 there was a breaking change regarding next js. Please refer to #208

**Comment by Adityacs001** [comment]
Hi @mkhstar , Thanks for your prompt reply and library. Great work.

Regarding issue , i'm doing exactly as your suggestion on threaf #208. Below is code snipper :

> const SunEditor = dynamic(() => import("suneditor-react"), { ssr: false });

Issue is that while running Dev it works well . When we are getting syntax error while next build and next export. Downgrading works both while in dev mode and while build mode.

Though i'm going through thread #208 and will try fix. I will keep you posted with test.

Thanks for your time.

**Comment by mkhstar** [comment]
Hi @Adityacs001 
I didn't face any issues when I run the build script as well. Possible you are importing something from the suneditor package at another place inside you pages directory. If you could post a demo I would be really glad

**Comment by Adityacs001** [comment]
Hi @mkhstar , to confirm issue is resolved and you were right it was due to wrong import.

Thanks again for plugin and response.
