### ISSUE TITLE
TypeError: this._iframeAutoHeight is not a function

### ISSUE THREAD

**Issue by Gabsys** [mkhstar/suneditor-react#225]
I am using SunEditor with NextJS. Upon pasting content into the editor, the following error will popup:
![image](https://user-images.githubusercontent.com/23636171/125198519-c8fd1b00-e294-11eb-8e51-de8e12ccd739.png)

This is my SunEditor setup:
```
 <SunEditor name="content" setContents={content} onChange={(text) => setContent(text)} setOptions={{ height: 200,
                      buttonList:[
                        ['formatBlock', 'font', 'fontSize', 'fontColor', 'align', 'paragraphStyle', 'blockquote'],
                        ['bold', 'underline', 'italic', 'strike', 'subscript', 'superscript'],
                        ['removeFormat'],
                        ['undo', 'redo'],
                        ['outdent', 'indent'],
                        ['table', 'list'],
                        ['link', 'image', 'video']] }}
                        height={300} />
```

P/S:  Not only pasting, using other formatting like Bold, Underline, Italic etc. will also pop this error.

Also, Bold is not showing its effect on the editor. The word bolded doest not appears to be bolded although I can see `<strong>` tag is surrounding the bolded word. Refer to img below:

![image](https://user-images.githubusercontent.com/23636171/125199374-83425180-e298-11eb-834b-406b124bbd52.png)

As you can see, the word 'Want' has `<strong>` tag surrounded but it does not appear to be bold

**Comment by mkhstar** [comment]
Hi @Gabsys 
I didn't encounter the issues you are facing. It would really help if you post a demo on codesandbox. By the way two-way binding shouldn't be used. This is because the setContents prop triggers the onChange event. If you want to set the initial value of the editor, use the defaultValue prop

**Comment by Gabsys** [comment]
> Hi @Gabsys
> I didn't encounter the issues you are facing. It would really help if you post a demo on codesandbox. By the way two-way binding shouldn't be used. This is because the setContents prop triggers the onChange event. If you want to set the initial value of the editor, use the defaultValue prop

Hi, you may test it here: https://codesandbox.io/s/suneditor-nextjs-error-demo-mpd77

**Comment by mkhstar** [comment]
Hi I have realized that you are importing suneditor-react inside your component itself. It should be outside instead.
Eg below
```jsx
import { useState } from "react";
import Link from "next/link";
import dynamic from "next/dynamic";
import "suneditor/dist/css/suneditor.min.css";
const SunEditor = dynamic(() => import("suneditor-react"), {
  ssr: false
});
export default function IndexPage() {
  const [content, setContent] = useState(" ");

  return (
    <div>
      <SunEditor defaultValue={content} onChange={(text) => setContent(text)} />
    </div>
  );
}

```

**Comment by Gabsys** [comment]
Oh lol, silly mistake. Thanks a lot!
