### ISSUE TITLE
Auto scroll up + change of typing location after pausing to type

### ISSUE THREAD

**Issue by Gabsys** [mkhstar/suneditor-react#226]
I am using `setContent` with `onChange` and I realise the editor will always scroll up with typing location moved to end of the paragraph after I made some changes in the middle of the paragraph.

My SunEditor setup:
```
   <SunEditor name="content" setContents={content} onChange={(text) => setContent(text)} setOptions={{ height: 200,
                      buttonList:[
                        ['formatBlock', 'font', 'fontSize', 'fontColor', 'align', 'paragraphStyle', 'blockquote'],
                        ['bold', 'underline', 'italic', 'strike', 'subscript', 'superscript'],
                        ['removeFormat'],
                        ['outdent', 'indent'],
                        ['table', 'list'],
                        ['link', 'image', 'video']] }}
                        height={300} />
```

Using version:
```
"suneditor": "^2.41.3",
"suneditor-react": "^3.2.0",
```

**Comment by Gabsys** [comment]
I realise I don't need to put `onChange` with `setContents`. I am able to access updated value with `event.target.content.value` afterwards without needing to use onChange, so I end up only using setContents to set its initial value.

**Comment by mkhstar** [comment]
Hi @Gabsys 
To set the editor's initial value please use the `defaultValue` prop.
eg.
```js
 <SunEditor defaultValue={content}/>
```

**Comment by Gabsys** [comment]
Hi, the issue still persist after using `defaultValue`, you may test it here: https://codesandbox.io/s/suneditor-nextjs-error-demo-mpd77

Step to reproduce:

1) Paste the following into the editor:
```
Test
Test
Test
Test
Test
Test
Test
Test
Test
CHANGE HERE
Test
Test
Test
Test
```

2) Type something at the 'CHANGE HERE' line

3) It will then automatically scroll to top & set the typing location to the last line
