### ISSUE TITLE
How to customize  'formatBlock'

### ISSUE THREAD

**Issue by noobnoobdc137** [mkhstar/suneditor-react#227]
![image](https://user-images.githubusercontent.com/55765209/125215928-59118380-e2da-11eb-8c16-5a0e9f25a913.png)

I want to remove `code` from the list 

it seems like it loads the module directly
```ts
 if (buttonList.indexOf("formatBlock") >= 0)
      pluginList.push(
        require("suneditor/src/plugins/submenu/formatBlock").default
      );
```

but in https://github.com/JiHong88/SunEditor/blob/master/src/plugins/submenu/formatBlock.js

```ts
    setSubmenu: function (core) {
        const option = core.options;
        const lang_toolbar = core.lang.toolbar;
        const listDiv = core.util.createElement('DIV');
        listDiv.className = 'se-submenu se-list-layer se-list-format';

        const defaultFormats = ['p', 'div', 'blockquote', 'pre', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'];
       /*
        * If there was a way i could pass on the value for formatList that would be cool
        */
        const formatList = !option.formats || option.formats.length === 0 ? defaultFormats : option.formats;
```

**Comment by admir4l** [comment]
Hi
I am working on a similar project and you can simply do this by passing the "formats" array inside "setOptions". see the sample below:

`
<SunEditor
         setOptions={{
          formats: ["h1", "h2", "h3", "p", "blockquote", "pre"],
        }}
      />
`

**Comment by noobnoobdc137** [comment]
> Hi
> I am working on a similar project and you can simply do this by passing the "formats" array inside "setOptions". see the sample below:
> 
> ```js
>       <SunEditor
>          setOptions={{
>           formats: ["h1", "h2", "h3", "p", "blockquote", "pre"],
>         }}
>       />
> ```

It worked thanks man 👊🏼

**Comment by 0papi** [comment]
export let customList = [
  ["undo", "redo", "fontSize", "formatBlock"],
  ["bold", "underline", "italic",],
  ["list"],
  "/",
];
const EditorSun = (props: any, ref: any) => {
  return (
    <SunEditor
      setDefaultStyle="font-size: 16px;"
      setOptions={{ height: "200", buttonList: customList, formats: ["h1", "h2", "h3", "h4", "p",] }}
      hideToolbar={true}
      {...props}
    />
  );
};

i know the issue has been closed but how come the "code" option still shows in the formats in the above?
