### ISSUE TITLE
Dropdown not displaying selected value

### ISSUE THREAD

**Issue by jeevansai502** [mkhstar/suneditor-react#229]
The dropdown for font, size and formats is not showing the value selected, it's always showing static text.

<img width="782" alt="image" src="https://user-images.githubusercontent.com/18240504/126051861-f4c81987-058a-4e8c-b8fe-ef7a58678853.png">

Issue can be seen from version 3.0.0, before that it's working fine.

**Comment by mkhstar** [comment]
Hi @jeevansai502 
Thanks so much for opening this issue. I think the problem has got to do with the core suneditor package.
@JiHong88 please check this codepen [https://codepen.io/mkhstar/pen/YzVxbrL](https://codepen.io/mkhstar/pen/YzVxbrL)

This problem occurs when the setOptions function is called

**Comment by mkhstar** [comment]
@jeevansai502 
I just fixed your problem in the latest version of suneditor-react 3.3.0.
Although if you change the language, placeholder, height or the width of the editor you might encouter this problem. This is what i have pointed above. @JiHong88 will take a look at it in the core suneditor package.

**Comment by jeevansai502** [comment]
@mkhstar 
Is this issue raised in the suneditor repository?
