### ISSUE TITLE
I can't enable scrolling = "no" for iframe :(

### ISSUE THREAD

**Issue by aleksaav** [mkhstar/suneditor-react#230]
Hi @mkhstar,
**How can I enable scrolling = "no" when paste iframe, because the editor does not recognize it?**
Editor recognizes allowfullscreen and frameborder but scrolling = "no" can't, is there a way to fix it?
I would be very grateful for an answer :)
-
And in version 3.2.0 when I want to pull some bigger content from the database in setContents it will not display, but in 3.1.1 it displays. Can this be fixed, or when you fix the iframe just to add those files to version 3.1.1?

**Comment by mkhstar** [comment]
Hi @aleksaav 
currently there is no scrolling option. You can request this feature in the core suneditor package. Also to set the initial content, please use the `defaultValue` prop
