### ISSUE TITLE
Error: Can't resolve 'react/jsx-runtime' when I install in NextJS

### ISSUE THREAD

**Issue by quynhnhu01** [mkhstar/suneditor-react#232]
I'm using:
node version : v14.15.4
npm version : 6.14.10
React: 16.8.6
Typescript: 3.7.4

![image](https://user-images.githubusercontent.com/54101819/127095105-8f9cb899-d367-4c69-b3dc-48720bdc45a0.png)

**Comment by changyeamoon** [comment]
@JiHong88 bump. Same is happening outside of NextJS

**Comment by AjiTae** [comment]
> https://github.com/mkhstar/suneditor-react/blob/master/tsconfig.json#L20
`"jsx": "react-jsx"` requires minimal react version 16.14.0.

**Comment by TheDarkStrix** [comment]
This might help you , in `tsconfig.json` or `jsconfig.json`
```
{
  "compilerOptions": {
    "jsx": "react",
  },
}
```

**Comment by mkhstar** [comment]
@quynhnhu01 can you please check on the latest version. If there are any issues please draw my attention
