### ISSUE TITLE
How to import buttonList in NextJS?

### ISSUE THREAD

**Issue by Braweria** [mkhstar/suneditor-react#234]
I want to import the `buttonList`, to customise my toolbar, but I am already stuck at importing it. I was following the README, but it didn't tell me how to import buttonList for NextJS, only for `SunEditor`, which I am importing dynamically.

I have tried both versions.  
## 1. dynamicaly
```js
const buttonList = dynamic(
  () => import('suneditor-react').then((mod) => mod.buttonList),
  {
    ssr: false, // also tried true
  }
);
```

Console logging `buttonList` then gives me a react forward ref, and console logging `buttonList.complex` just gives me undefined.

## 2. normally
```js
import { buttonList } from 'suneditor-react';
```
This just gives me `SyntaxError: Cannot use import statement outside a module`.

I have also updated to the latest version.
```js
    "suneditor": "^2.41.3",
    "suneditor-react": "^3.3.0"
```

**Comment by Braweria** [comment]
I have also tried `require`, which didn't work either and gave me the same error as `import`.

**Comment by mkhstar** [comment]
@Braweria 
I have realized this issue. I have to find another way of solving this problem. For version 3 i want users to use any suneditor version of their choice and this is bringing up these issues.  The problem is the main suneditor package ships its module in esmodule but nextjs supports commonjs (nodejs)

**Comment by mkhstar** [comment]
@Braweria 
For now you can import it like below
```jsx
const buttonList = require("suneditor-react/dist/misc/buttonList");
```

**Comment by mkhstar** [comment]
I will include this in the documentation later

**Comment by Braweria** [comment]
awesome, thank you for letting me know @mkhstar.

**Comment by TheDarkStrix** [comment]
@Braweria You can do this, no need for dynamic imports 

```
const SunEditor =
  typeof window === "object" ? require("suneditor-react").default : () => false;

const buttonList =
  typeof window === "object"
    ? require("suneditor-react").buttonList
    : () => false;
```

**Comment by mkhstar** [comment]
@TheDarkStrix 
You can use the above example. It is shorter and cleaner
