### ISSUE TITLE
Custom plugins

### ISSUE THREAD

**Issue by aderaHenry** [mkhstar/suneditor-react#24]
Is there a way of adding custom plugins as described in http://suneditor.com/sample/html/customPlugins.html?

**Comment by mkhstar** [comment]
Hi @aderaHenry  you can use the `setOptions `prop to specify a custom plugin.

**Comment by aderaHenry** [comment]
> Hi @aderaHenry you can use the `setOptions `prop to specify a custom plugin.

Sure @mkhstar , I did that before and it worked, but for the OK button. I think this is not the suneditor-react package's problem though:- the `onClick` object property of the custom plugin is not fired upon clicking the OK button. It must be something to do with React's virtual DOM.

**Comment by BuiChiBach** [comment]
Hi @mkhstar , i'm facing the issue that adding more text when click the OK button but the onChange function isn't called, Do u have any solution to fix this! 

Thanks.
