### ISSUE TITLE
readOnly prop is not working

### ISSUE THREAD

**Issue by krAlena** [mkhstar/suneditor-react#241]
Hi! I have some issue
suneditor: 2.41.2,
suneditor-react: 3.2.0

readOnly props stopped working.

Improvement: Is able to make editor block's contenteditable=false in readOnly mode? Plugins like Grammarly detect contenteditable blocks and allow edit them, I don't think it's right...

**Comment by JoshuaSeth** [comment]
I have multiple issues as well with these updates.

**Comment by mkhstar** [comment]
I would like to fix these issues these weekend

**Comment by JoshuaSeth** [comment]
Hi @mkhstar no problem, thanks for your reaction and a beautiful editor! I should notify you that I cannot reproduce the readOnly error anymore, could be error from my side. 

What i still have when updating above 2.40 and 3.0 is an editor that is only approximately 200px high and as such has a tiny view on the scrollable content inside. Prior to this update the editor would stretch vertically to fit the contents. Am I missing a prop when setting op the editor?

**Comment by mkhstar** [comment]
@JoshuaSeth  you can use the `height` prop to set the preferred height of your choice, even thought setting it to a percentage is still and issue. Check out this thread https://github.com/JiHong88/SunEditor/issues/627

**Comment by mkhstar** [comment]
@krAlena can you please the latest version? If you encounter any issues please draw my attention
