### ISSUE TITLE
The exported html code contains the `br` tag not self closed.

### ISSUE THREAD

**Issue by dennisat** [mkhstar/suneditor-react#243]
The generated `html/xml` code, whenever contains the `<br/>` element is exported as not self closed.

### Is exported as `<br>` while should be exported `<br/>`.

Of course, this can be fixed on the `onChange` event but I want to use it as an unmanaged component, and the exported code on the dom is still wrong.

**How can we fix this?**

For example, this is the generated code for a very simple table: 

_BTW, the `<br>` here is completely useless._

```
<table>
  <tbody>
    <tr>
      <td>
        <div>First name<br>
        </div>
      </td>
      <td>
        <div>Last Name<br>
        </div>
      </td>
      <td>
        <div>Age<br>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div>John<br>
        </div>
      </td>
      <td>
        <div>Smith<br>
        </div>
      </td>
      <td>
        <div>32<br>
        </div>
      </td>
    </tr>
  </tbody>
</table>
```

**Comment by mkhstar** [comment]
@dennisat  please open this issue in the core suneditor package
