### ISSUE TITLE
Paste image behaviour

### ISSUE THREAD

**Issue by dennisat** [mkhstar/suneditor-react#244]
Currently, if you `Copy image`& `Paste` into the editor, a `data:image` is generated in the XML code like this:

```
<img src="data:image/png;base64,iVBORw0KGg...ANSUhEUgAAA5"/>
```

Some old editors, instead of this, create the `img` element with `src`the link of the image (instead the data of it) like this:

```
<img src="HTTP://www.example.com/image.png"/>
```

**Can we control what will be pasted somehow?**

**Comment by mkhstar** [comment]
@dennisat can you open this issue in the core suneditor package?
