### ISSUE TITLE
Language Object provided in readMe is not complete

### ISSUE THREAD

**Issue by BahaMagi** [mkhstar/suneditor-react#245]
The Editor Language Object provided in the appendix of the readme is incomplete. 

`"dialogBox"."audioBox"` 

is missing in the list. This leads to a crash when using a custom language obj. Just adding 
```
"dialogBox": {
  "audioBox": {}
  ...
 ```
 works as a hotfix.

**Comment by mkhstar** [comment]
Thanks @BahaMagi 
Fixed in the latest version
