### ISSUE TITLE
readOnly prop, hideToolbar and correct height stop working with 3.2.0

### ISSUE THREAD

**Issue by JoshuaSeth** [mkhstar/suneditor-react#247]
suneditor: 2.41.2,
suneditor-react: 3.2.0

From these versions on for the forementioned props stop working and the editor changes to a tiny scroll view instead of taking the height needed to display the contents without scrollbar.

**Comment by krAlena** [comment]
suneditor: 2.41.3,
   suneditor-react: 3.3.0
   
   Property "placeholder" doesn't work

**Comment by mkhstar** [comment]
@JoshuaSeth and @krAlena 
Can you please check on the latest version? If there are any issues please draw my attention
