### ISSUE TITLE
Default Font Size And Font Family/ Any Properties

### ISSUE THREAD

**Issue by sawanmakwana** [mkhstar/suneditor-react#25]
Is there any way or option to set default font or font family or any other properties when the editor is rendered?
like if default size is 16, and then if we want it more or less....so that we can change.
 @mkhstar

**Comment by mkhstar** [comment]
Hi sorry for the late reply within the `setOptions `props you can set the property `font` to an array of font names you would like to use by default. Eg below:
```jsx
<Suneditor setOptions={{font: ['Tahoma', 'Arial']}}/>
```

The font at the index 0 should render by default. Hope it helps.

**Comment by sawanmakwana** [comment]
Hi @mkhstar,
Thanks for the response.

I have tried as you have specified above but it is not working. Font properties are still the same as provided by default...
I am attaching images for the reference.

![Screenshot from 2020-03-03 15-32-52](https://user-images.githubusercontent.com/45915871/75765174-1b572f00-5d65-11ea-9596-c2341b65a860.png)
![example2](https://user-images.githubusercontent.com/45915871/75765200-2316d380-5d65-11ea-9af5-965b8f4242b1.png)

**Comment by mkhstar** [comment]
Yeah I have now got your question. As far as i know this feature is not yet implemented in Suneditor yet. @JiHong88 we could make it that the first font listed in the list will be the default font. What do you think?

**Comment by sawanmakwana** [comment]
Yeah. It would be a very good and helpful feature if we can implement it. But putting the first/ zeroth index of the array of the list as the default property would not be a good option. Yeah, definitely it will solve our problem but UX wise it would be a little bad. As mentioned in the above scenario, if we want to keep the default font size 100 then we have to keep '100' at 0th index and In ListView/ Dropdown '100'  will be coming at First Place, which would be little odd as it will mismatch ascending order of the list.

So I would suggest that you have already given the option like 'default and so if we can set the property of default then it would be great.

@mkhstar @JiHong88

**Comment by JiHong88** [comment]
@sawanmakwana 
You can set the default by defining the [sun-editor-editable](https://github.com/JiHong88/SunEditor/blob/master/src/assets/css/suneditor-contents.css#L9) class.
I think it's better to set the style with css
What do you think?

**Comment by sawanmakwana** [comment]
Hi @JiHong88 
In our application, we have a requirement like the 'Gmail setting page', where we can set the default font properties defined by the user. Like in my inbox, I want X font family and Y font size and it will be different for different users as set by them. So I am asking it would be helpful if we can change the properties dynamically.
And as suggested by you, we won't be able to change dynamically with CSS. 
A better option would be like passing the prop or something suggested by @mkhstar

**Comment by JiHong88** [comment]
Hi @sawanmakwana 
Yeah, It's a necessary option for the editor as well.
I'll add "defaultStyles" option and "setDefaultStyles" method.

**Comment by mkhstar** [comment]
@JiHong88  i just updated `suneditor-react` to include the latest features

**Comment by sawanmakwana** [comment]
Yeah! Thanks.. @JiHong88 @mkhstar 
It will be very helpful

**Comment by JiHong88** [comment]
Hi @sawanmakwana @mkhstar 
The [2.27.0](https://github.com/JiHong88/SunEditor/releases/tag/2.27.0) version has been updated.
Added a **defaultStyle** option and **setDefaultStyle** function
Thank you.

**Comment by mkhstar** [comment]
Hi @sawanmakwana can you confirm that your issue is now resolved and close this issue.

**Comment by sawanmakwana** [comment]
Hi, @JiHong88 @mkhstar 
Is this the correct way to write ? Because I am not able to see the difference... 
PFA
![Screenshot from 2020-04-02 15-33-05](https://user-images.githubusercontent.com/45915871/78236711-01da0c00-74f8-11ea-8e42-bc9feb21c0cc.png)

**Comment by JiHong88** [comment]
Hi, @sawanmakwana 
The defaultStyle option is string type `"font-size:100px;"`

**Comment by sawanmakwana** [comment]
I guess this is also string type, just bracket around it. I have written the way you suggested, but no difference @JiHong88 

![Screenshot from 2020-04-06 10-32-28](https://user-images.githubusercontent.com/45915871/78524664-2c76de00-77f2-11ea-97b3-8c672bc8d4e2.png)

**Comment by JiHong88** [comment]
Is the style you set in the ".sun-editor-editable" area?
<img width="759" alt="스크린샷 2020-04-06 오후 6 34 46" src="https://user-images.githubusercontent.com/13191953/78544613-5ef5fa80-7835-11ea-8ca5-c58677530360.png">

**Comment by sawanmakwana** [comment]
Yes, I guess it should be but I am not able to see the difference even when I inspect and change the properties of ".sun-editor-editable" class.
![Screenshot from 2020-04-06 18-30-52](https://user-images.githubusercontent.com/45915871/78561136-d7a88700-7834-11ea-8830-c712706b38e9.png)

**Comment by JiHong88** [comment]
Is the css file also using the latest version?
<img width="284" alt="스크린샷 2020-04-07 오전 2 31 18" src="https://user-images.githubusercontent.com/13191953/78587430-e4020380-7877-11ea-9e90-d07b860656c1.png">

**Comment by sawanmakwana** [comment]
No, I don't think. It is something like this - 
![Screenshot from 2020-04-07 09-44-17](https://user-images.githubusercontent.com/45915871/78629413-9e176080-78b4-11ea-8aba-00e8d063ecc6.png)

**Comment by JiHong88** [comment]
Please check the "sun-editor-editable * {.." section.

**Comment by sawanmakwana** [comment]
![Screenshot from 2020-04-07 13-54-38](https://user-images.githubusercontent.com/45915871/78646898-6241c280-78d7-11ea-8851-6b221c840be2.png)

it has only one property

**Comment by JiHong88** [comment]
Hi @sawanmakwana 
It looks a css file is not latest version.
"suneditor-react" needs to update the latest version of "suneditor". @mkhstar 

Until then, try putting the following code in your css file.
```css
.sun-editor-editable * {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    font-family: inherit;
    font-size: inherit;
    color: inherit;
}
```

**Comment by sawanmakwana** [comment]
No difference. I don't see anywhere "font-size:100px" applied, so I guess default style property is also not working.
And when I put this code in my css, then "sun-editor-editable * {.." section is gets lost.

**Comment by JiHong88** [comment]
It works well when tested on an [demo](http://suneditor.com/sample/html/options.html) site.
Check to see if there are any css giving directly the "font-size" value of `<p>`.

**Comment by JiHong88** [comment]
Other way, you can using the `ifram` option.
If you use `ifram` the page is not affected by other css.

**Comment by sawanmakwana** [comment]
but CSS is comping from sun-editor-editable. No, it is not using the p tag. I have gone through all my CSS. There is no property applied only to "P {  " 
Ya, I checked on demo site, it is working fine.

I have tried using Iframe and it is giving error


![Screenshot from 2020-04-09 11-49-10](https://user-images.githubusercontent.com/45915871/78864907-4ca8d600-7a5a-11ea-9cd6-15914dbe154c.png)

Error:Iframe

![Screenshot from 2020-04-09 12-12-15](https://user-images.githubusercontent.com/45915871/78865540-6dbdf680-7a5b-11ea-86ef-3aa2887be350.png)

Iframe code:
![Screenshot from 2020-04-09 12-13-34](https://user-images.githubusercontent.com/45915871/78865732-c8575280-7a5b-11ea-9d0c-2873bd594cf7.png)

![Screenshot from 2020-04-09 12-14-37](https://user-images.githubusercontent.com/45915871/78865704-b7a6dc80-7a5b-11ea-923e-a6002b73093b.png)

**Comment by JiHong88** [comment]
The css setting for the page is hard to understand unless you're doing it yourself.
It's means "iframe" option not tag.
`setOptions=({iframe: true})`

**Comment by mkhstar** [comment]
> Hi, @JiHong88 @mkhstar
> Sorry for the late reply.
> Is this the correct way to write? Because I am not able to see the difference... Output is same
> PFA
> ![Screenshot from 2020-04-02 15-33-05](https://user-images.githubusercontent.com/45915871/78236711-01da0c00-74f8-11ea-8e42-bc9feb21c0cc.png)

Hi @sawanmakwana `defaultStyle` is not a prop in `suneditor-react` and i think that is the reason why it is not working. Please set the `defaultStyle` option in the setOptions prop. Eg. below
```jsx
<SunEditor setOptions={{defaultStyle: 'font-size: 100px;'}}/>
```

**Comment by sawanmakwana** [comment]
Hi @mkhstar @JiHong88 ,
Thank you so much for your help and time. It is working

**Comment by sawanmakwana** [comment]
Hi @mkhstar @JiHong88,
I was working with default properties... As we discussed earlier default property is working but I got stuck with one scenario.
![Screenshot from 2020-05-28 20-03-06](https://user-images.githubusercontent.com/45915871/83155455-e1f14e00-a11e-11ea-9ca0-2a2e14b4510e.png)
Here, You can see that I have given default font-size and font-family from the state; like it is variable and it can change from anywhere at any time. In this case, it is not changing (properties remain the same as of initial render)
It is there anything that you can do, then it would be a great help!
