### ISSUE TITLE
How to use ImageUploadBefore w/o uploadHandler

### ISSUE THREAD

**Issue by UncleJ-CJH** [mkhstar/suneditor-react#251]
Hello, I have a question about uploadHandler.

I wan to use directly using URL after onImageUploadBefore w/o uploadHandler.

I guess onImageUploadBefore - uploadHandler, this flow is works to use raw images.
When I use big size Images, PayloadTooLarge error is occured.

onImageUploadBefore {
 imageUpload => return URL
 display Image using URL
}

JiHong88 said user core. (https://github.com/JiHong88/SunEditor/issues/414#issuecomment-649715918)
But I know, suneditor-react don't use core.

how to solve these problem?

**Comment by mkhstar** [comment]
Hi @UncleJ-CJH,
Learn more about how to use the core in suneditor-react here https://github.com/mkhstar/suneditor-react#about-core
