### ISSUE TITLE
One issue i facing is that i am able to select and delete image after 2-3 times click on image from suneditor, even though editor is in read only mode. I can do it even when editor is diabled

### ISSUE THREAD

**Issue by roker15** [mkhstar/suneditor-react#252]
One issue i facing is that i am able to select and delete image after 2-3 times click on image from suneditor, even though editor is in read only mode. I can do it even when editor is diabled

**Comment by mkhstar** [comment]
The latest version might fix this issue @roker15 can you check it out?

**Comment by roker15** [comment]
> The latest version might fix this issue @roker15 can you check it out?

yes it's fixed i think . I think you are the author of suneditor-react could you help me with https://github.com/JiHong88/SunEditor/issues/940
