### ISSUE TITLE
Uncaught Error: [SUNEDITOR.core.callPlugin.fail]

### ISSUE THREAD

**Issue by krAlena** [mkhstar/suneditor-react#254]
Hi!
Toolbar's actions used in dropdowns have stopped working
```
<SunEditor
                  placeholder="Placeholder doesn't work"
                  setOptions={{
                        codeMirror: CodeMirror,
                        fontSize: [ 8, 9, 10, 11, 12, 13, 14, 16, 18, 20, 22, 24, 26, 28, 36, 48, 72],
                        formats: ['h3', 'h4', 'h5', 'h6', 'p', 'div', 'blockquote', 'pre'],
                        katex: katex,
                        plugins: currentPlugins
                  }}
/>
```

Versions' info:
```
    "suneditor": "^2.41.3",
    "suneditor-react": "^3.3.1" 
```
![image](https://user-images.githubusercontent.com/26471239/144491416-92d5529f-c84e-4f0d-8631-cb54776b7841.png)

[related issue](https://github.com/JiHong88/SunEditor/issues/162#issuecomment-954561271)

**Comment by krAlena** [comment]
It is very strange, but property "placeholder" cause that errors (and placeholder isn't working by itself). 
Tools have worked when I've removed this property.

Please, fix placeholder's issue

**Comment by BahaMagi** [comment]
Any estimate when/if this is going to be fixed?

**Comment by DeepikaSharma5** [comment]
@mkhstar Can you please give use any update on this issue?

**Comment by mkhstar** [comment]
A new version has just been released which supports the latest suneditor. Can you check it out?

**Comment by DeepikaSharma5** [comment]
@mkhstar it is not fixed. I used 3.4.0 and still getting the same error

**Comment by JiHong88** [comment]
@DeepikaSharma5 @krAlena @kidar2 https://github.com/mkhstar/suneditor-react/issues/254#issue-1069934585
This error occurs when using a plugin that is not registered when creating the editor.
Does an error occur even if I register the plugin in the options?

**Comment by DeepikaSharma5** [comment]
> @DeepikaSharma5 @krAlena @kidar2 [#254 (comment)](https://github.com/mkhstar/suneditor-react/issues/254#issue-1069934585) This error occurs when using a plugin that is not registered when creating the editor. Does an error occur even if I register the plugin in the options?

Yes it occurring even after register the plugin in options

**Comment by JiHong88** [comment]
@DeepikaSharma5 Um.. Does the "suneditor" package get the same error?

**Comment by DeepikaSharma5** [comment]
> @DeepikaSharma5 Um.. Does the "suneditor" package get the same error?

@JiHong88  I have not checked with that because not using it. Better if you try to create a react project and check this issue. It will be helpful for everyone.

**Comment by mkhstar** [comment]
@DeepikaSharma5 it will be really helpful if you provide a demo on sandbox for this. Because I can't really reproduce this error

**Comment by JiHong88** [comment]
@DeepikaSharma5 This error is not reproduced.
Please provide more information so we can reproduce this problem.

**Comment by krAlena** [comment]
> @DeepikaSharma5 @krAlena @kidar2 [#254 (comment)](https://github.com/mkhstar/suneditor-react/issues/254#issue-1069934585) This error occurs when using a plugin that is not registered when creating the editor. Does an error occur even if I register the plugin in the options?

[JiHong88](https://github.com/JiHong88) Hi! This error occurs when I register the custom plugin in the options.  This issue came back with versions:
```
    "suneditor": "2.41.3",
    "suneditor-react": "3.2.0",
```
![image](https://user-images.githubusercontent.com/26471239/187233964-106cb591-8ab0-4c57-bd0a-94670a6103cb.png)

Example of using:
```
              <SunEditor
                    getSunEditorInstance={this.getSunEditorInstance}
                    onChange={this.tryContentChange}
                    toggleCodeView={this.toggleCodeView}
                    onImageUploadBefore={this.onImageUploadBefore}
                    imageUploadHandler={this.imageUploadHandler}
                    defaultValue={this.props.htmlContent}
                    setOptions={{
                        codeMirror: CodeMirror,
                        fontSize: [ 8, 9, 10, 11, 12, 13, 14, 16, 18, 20, 22, 24, 26, 28, 36, 48, 72],
                        formats: ['h3', 'h4', 'h5', 'h6', 'p', 'div', 'blockquote', 'pre'],
                        katex: katex,
                        plugins: currentPlugins,
                        buttonList: listBtns
                    }}
                />
```

**Comment by JiHong88** [comment]
@krAlena 
Custom options and default options are all treated the same.
Both the basic option and the custom option must be registered.
`plugins: {custom_plugin, ...plugins}`

**Comment by onyxcool** [comment]
Hi @JiHong88 ,

thank you for the editor - it's really nice and very customizable. 
I've similar problem described here, can you, please provide more details regarding your last answer? 

It's a bit unclear what should I do? I've bunch of plugins which do not work in latest 3.4.1 version.

**Comment by onyxcool** [comment]
> 
Hi again @JiHong88 ,

I've realized what you mean and now it works as expected.
So I had to import plugins and initialize it correctly.

Please, find an image below
![image](https://user-images.githubusercontent.com/11150186/204796718-c03385bf-147c-4d0b-80da-780733c8f6f5.png)
