### ISSUE TITLE
Can I setContents after render?

### ISSUE THREAD

**Issue by rogerbage** [mkhstar/suneditor-react#255]
I'm using next js and I want to reload the content dynamically when content change in the server. I dont have any idea how to do that. I'm get the content and put in the server with no problems using onchange, but how i put content in the editor?

**Comment by rogerbage** [comment]
I try something like that, but with no hope to work:

`async function getText(){
  const strEditor = await client.getFileContents("/files/makena/rogerbage/file.txt", { format: "text" });
  SunEditor.setContents("strEditor");
  return strEditor;
}`

**Comment by mkhstar** [comment]
Hi @rogerbage 
You need a ref to get the suneditor instance to do this. Eg. below:
```js
const editor = useRef(); //somewhere
editor.current.setContents(srcEditor); // after getting the data

```
