### ISSUE TITLE
<img> not shown when upgrading to suneditor 2.42.0

### ISSUE THREAD

**Issue by sm3sher** [mkhstar/suneditor-react#257]
I've upgraded from v2.41.3 to v2.42.0 and encountered a problem where all types of images are not shown.
My images were in base64-data format and I appended them through `appendContents`.

Could it be that the wrapper `suneditor-react` is not compatible with the latest suneditor?

**Comment by mkhstar** [comment]
Hi @sm3sher can you check out the latest version?

**Comment by sm3sher** [comment]
I've checked out the latest version for `suneditor` and `suneditor-react` and the problem still persists.

**Comment by sm3sher** [comment]
As of now the problem is fixed with currently used versions;
```js
    "suneditor": "^2.43.5",
    "suneditor-react": "^3.4.0",
```
