### ISSUE TITLE
Passing ref to text area

### ISSUE THREAD

**Issue by AliBayatMokhtari** [mkhstar/suneditor-react#258]
How can we pass ref to text area in `SunEditor` component in order to use react-hotkeys-hooks?

**Comment by mkhstar** [comment]
Hi @AliBayatMokhtari 
You could wrap it with another element and pass the ref to that element
```jsx
const ref = useHotkeys('shift+a', () => setCount(prevCount => prevCount + 1))
<div ref={ref}>
<Suneditor />
</div>
```
