### ISSUE TITLE
If there are n or more editor declarations, the focus movement does not work normally.

### ISSUE THREAD

**Issue by yeojihun** [mkhstar/suneditor-react#262]
Declare n editors within the same component and shift the focus to the editor first.

If you click another editor without entering a value, the focus will not move.

**Comment by andylwelch** [comment]
I see this issue in Chrome (but not Firefox) when I have multiple editors on the page.

Steps to reproduce,

1. click into an editor with no content
2. click into a different editor

Expected Outcome
- keyboard focus to be in the second editor

Actual outcome
- keyboard focus is still in the first editor (the onFocus is even triggered again!)

Notes
- works fine in Firefox and also if the first editor has content

**Comment by mkhstar** [comment]
This is also reproducable with the core suneditor package

**Comment by BahaMagi** [comment]
Maybe related to #272. We have similar problems with multiple instances on one page. We can only reproduce it on Chrome + Mac. Windows and all other browsers work for us. In general, blur and focus events seem all over the place with multiple instances on the same page.

**Comment by BahaMagi** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version fixed the focus movement behavior for us.
