### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module with Next.js

### ISSUE THREAD

**Issue by Sorok-Dva** [mkhstar/suneditor-react#263]
Hello, I tried you package for my next.js application but I've an error while trying to configure it.

The problem appears to be on the import `import SunEditor from 'suneditor-react'`
That gives me 
![image](https://user-images.githubusercontent.com/15158794/158652594-f3f2fd79-e589-43ab-bc68-7cdfd984140f.png)

If I remove the import, this error is changed by another (normal) one

Here is my code, really simple : 

```javascript
import React, { useCallback, useMemo, useState } from 'react'
import SunEditor from 'suneditor-react'

const ContactPage = () => {
  
  return (
    <div>
      <p>Nous contacter</p>
      <SunEditor />
    </div>
  )
}

export default ContactPage
```

Thanks

**Comment by WISUNGWON** [comment]
How did you resolve this issue? I have same problem my nextjs application. @Sorok-Dva

**Comment by Sorok-Dva** [comment]
> How did you resolve this issue? I have same problem on my nextjs application. @Sorok-Dva

I solved this issue with the documentation. I had to create a new file (Editor.js as an exemple)

```javascript
import React, { useRef } from 'react'
import dynamic from 'next/dynamic'
import 'suneditor/dist/css/suneditor.min.css'

const SunEditor = dynamic(() => import('suneditor-react'), {
  ssr: false
})

export default () => {
  const editor = useRef()
  const getSunEditorInstance = (sunEditor) => {
    editor.current = sunEditor
  }

  return (
    <SunEditor getSunEditorInstance={getSunEditorInstance} setAllPlugins={true} defaultValue="<p>The editor's default value</p>"
               setOptions={{
                 // your options
               }}/>
  )
}```
