### ISSUE TITLE
Suneditor  resets an object managed by useState hook

### ISSUE THREAD

**Issue by askuta** [mkhstar/suneditor-react#267]
I created a reusable wrapper component around Suneditor that manages its configuration (RteEditor.jsx) and the visibility of the toolbar.
In App.jsx I want to edit a `lesson` object, that has a simple `name` and a formatted `description` properties. The lesson object is managed by a useState() hook, the name property can be edited via an input HTML field and the description property can be edited via the RteEditor field. When I edit the name property, it's working fine. **When I edit the description property, the lesson object is somehow reset to it's initial state and then sets its description property.**

Steps to reproduce the issue:
- run the application and open your browser's console
- edit the name property and check the logs in the console (note that, you can see the lesson's "before-change" state in the logs, so you might want to edit the fields several times to see any changes)
- edit the description property and check the logs in the console; **you'll see that the application modifies the initial lesson object, saves its state instead of modifying the actual lesson object**
- if you edit the name property again, then the lesson object has the description property you typed earlier and the name property is changed properly

I'm a beginner in React, please bear with me.
I'm not sure if this is a real bug but the behavior is not what I would intuitively expect. You can find a simplified example in the attachment.
I'd appreciate any kind of help.

[suneditor-test.zip](https://github.com/mkhstar/suneditor-react/files/8425360/suneditor-test.zip)

**Comment by askuta** [comment]
I've found a similar issue [#149](https://github.com/mkhstar/suneditor-react/issues/149). In that case your solution worked fine on class-based components. Unfortunately, I couldn't make it work on functional components and useState hook.

**Comment by askuta** [comment]
As a temporary solution, I've added useEffect() to the wrapper class. It breaks the apparent entanglement between SunEditor (wrapper component) and the data managed by useState() (parent component).

[RteEditor.zip](https://github.com/mkhstar/suneditor-react/files/8461967/RteEditor.zip)

**Comment by mkhstar** [comment]
@askuta i couldn't really reproduce your problem. But one problem i noticed with your code is that you are binding the contents and setting again after onChange. 
The `setContents` of the RteEditor can be removed

**Comment by mkhstar** [comment]
Also i realized that you use the old value of your state while reseting the state. You need to use the current version (using the callback of the `setState`) of the lesson value to reset the state I have modified your two change functions below. Notice how i used the `setLesson`


```jsx
 const handleLessonChange = (event) => {
    // Everything looks fine when I edit lesson name. --> OK
    console.log("handleLessonChange - lesson: " + JSON.stringify(lesson));
    console.log(
      "handleLessonChange - content: " + JSON.stringify(event.target.value)
    );

    setLesson((l) => ({...l, name: event.target.value}))
  };

  // When I edit description, the description is updated but the lesson name is reset.
  // I tried useCallback() for the handleDescriptionChange function but it didn't help.
  const handleDescriptionChange = (content) => {
    console.log("handleDescriptionChange - lesson: " + JSON.stringify(lesson));
    console.log(
      "handleDescriptionChange - content: " + JSON.stringify(content)
    );

    setLesson((l) => ({...l, description: content}))
  };

```
