### ISSUE TITLE
The onChange function isn't called

### ISSUE THREAD

**Issue by BuiChiBach** [mkhstar/suneditor-react#27]
Hi @mkhstar ,

I added custom plugins as described in:
http://suneditor.com/sample/html/customPlugins.html

but when click the OK button ,the onChange function isn't called, Do u have any solution to fix this!

Thanks.

**Comment by aderaHenry** [comment]
> Hi @mkhstar ,
> 
> I added custom plugins as described in:
> http://suneditor.com/sample/html/customPlugins.html
> 
> but when click the OK button ,the onChange function isn't called, Do u have any solution to fix this!
> 
> Thanks.

Hello @BuiChiBach . You can easily get around the problem. In the add property, Add a `change` event listener to the input element that matters (if you have several), like so:

`listDiv.getElementsByTagName('INPUT')[index].addEventListener('change', this.onClick.bind(core))`

Change the index to the input element's index on your listDiv variable. You will achieve the same effect.

This workaround has a few cons, that won't hurt.

I think that React has problems setting a `change` event listener to any element before it is in the DOM. 

Another approach, a more effective one without cons, would be to make turn the plugin into a dumb component and register the `change` event listener to the button inside your `useEffect` hook.

Cheers buddy

**Comment by BuiChiBach** [comment]
![image](https://user-images.githubusercontent.com/44353566/75313429-59e57900-588f-11ea-9a5f-f31a7977871d.png)

Hi @aderaHenry , i custom from 'add more text' to 'add emoji' like this , so i must click , not change like input tag. And i have fixed it by add this line in onClick function:

this.history.push(true);

Btw , Thank you for your supports <3

**Comment by aderaHenry** [comment]
@BuiChiBach , you have saved me lots of trouble with `this.history.push(true)`! Thanks bruv
