### ISSUE TITLE
align left button not worked

### ISSUE THREAD

**Issue by lottopotato** [mkhstar/suneditor-react#271]
Hi Thank for contributors.

Left align button changes paragraph alignment to `<p>` not for `<p style = 'text=align:left;'>`. 
and my project, recognized `<p>` as just center alignment.

i think, it was affected by project css.
however being `<p style = 'text=align:left;'>` seems to be better clean then `<p>.`

**Comment by mkhstar** [comment]
The content for the style attribute is meant to be used in a css context. `text=align:left;` wouldn't work
