### ISSUE TITLE
Blur and Focus event propagation / bubbling cannot be stopped 

### ISSUE THREAD

**Issue by BahaMagi** [mkhstar/suneditor-react#272]
## Problem 
Calling `stopProgagation()` on focus and blur events does not cancel event bubbling. 

```
import Suneditor from "suneditor-react";
import "suneditor/dist/css/suneditor.min.css";
export default function App() {
  return (
    <div
      onBlur    = {(e) => console.log("container, blur")}
      onFocus = {(e) =>  console.log("container, Focus")}
    >
      <h1>Hello CodeSandbox</h1>
      <input
        onBlur={(e) => {
          console.log("test, blur");
          e.stopPropagation();
        }}
        onFocus={(e) => {
          console.log("test, Focus");
          e.stopPropagation();
        }}
      />
      <Suneditor
        onBlur={(e) => {
          console.log("editor, blur");
          e.stopPropagation();
        }}
        onFocus={(e) => {
          console.log("editor, Focus");
          e.stopPropagation();
        }}
      />
    </div>
  );
}
```

## Expected behavior
Clicking in the editor should cancel the propagation of the focus event and thus only print `editor, Focus"  and nothing else. 

## Actual behavior
Clicking in 
![image](https://user-images.githubusercontent.com/52032030/168621974-0f4f4521-4d66-43bc-a1b1-757e09ed54de.png)
Clicking in the suneditor, then in the input and then outside produces the above logs. 

Edit:
Forgot to add version info
```
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-helmet": "^6.1.0",
"suneditor": "^2.43.5",
"suneditor-react": "^3.4.0",
```
We tested this on Firefox, Chrome, Safari and on Win and Mac and all exhibited the same behavior.

**Comment by BahaMagi** [comment]
Update to version [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) did not help.

**Comment by mkhstar** [comment]
@BahaMagi it might be related to the main suneditor package but the workaround i found for this is to wrap the suneditor with a div. Eg below
```jsx
<div
   onBlur={(e) => e.stopPropagation()}
   onFocus={(e) => e.stopPropagation()}
>
  <SunEditor  />
</div>
```
