### ISSUE TITLE
Issues with setContents

### ISSUE THREAD

**Issue by andrew-joung** [mkhstar/suneditor-react#273]
I am calling `setContents()` with contents being something like `<p><a href="">John Doe</a></p>`.
`setContents()` gets called with the correct parameter the first time but is called again with the values `<p></br></p>` and resets the contents of the editor.

I can't seem to track the second call of `setContents()` is this a known behavior?

**Comment by mkhstar** [comment]
@andrew-joung can you provide an example? I couldn't really figure out the problem
