### ISSUE TITLE
How do I upload an image through s3?

### ISSUE THREAD

**Issue by choisuhyeok1255** [mkhstar/suneditor-react#279]
## Version
3.4.0

I want to upload an image using suneditor.
I want to know how to upload the image to s3.
Can I upload it using the input tag?

**Comment by mkhstar** [comment]
You can use `onImageUploadBefore` prop to handle the upload. Check https://github.com/JiHong88/suneditor docs for more info

**Comment by Anishadahal** [comment]
How do we delete the images from s3 when we remove image from editor? @mkhstar
