### ISSUE TITLE
onChange and setContents. Why is onChange getting called when there is no changes made?

### ISSUE THREAD

**Issue by srinivasjay** [mkhstar/suneditor-react#28]
Hey 
I am trying to use the suneditor-react. I am a react newbie and I am using this for my project. 
I would like to know why this handle Change is even called even when there is no change made to the editor?
Here is my code snippet.

**Comment by srinivasjay** [comment]
export default class BasicEditor extends Component {
  constructor(props){
    super(props)
    this.state ={
      comment: 'Hello'
    }
    this.handleChange = this.handleChange.bind(this)
  }
  handleChange(value){
    console.log(value); //its logging Hello
  }

  render(){
    **return <SunEditor
    setContents={this.state.comment}
    setOptions={editorOptions}
    onChange={this.handleChange}
    disabled={this.props.isAppReadOnly}
  />**
  }
}

**Comment by srinivasjay** [comment]
export default class BasicEditor extends Component {
  constructor(props){
    super(props)
    this.state ={
      comment: 'Hello'
    }
    this.handleChange = this.handleChange.bind(this)
  }
  handleChange(value){
    console.log(value); //its logging Hello
  }

  render(){
    return <SunEditor
    setContents={this.state.comment}
    setOptions={editorOptions}
    onChange={this.handleChange}
    disabled={this.props.isAppReadOnly}
  />
  }
}

**Comment by aderaHenry** [comment]
> export default class BasicEditor extends Component {
> constructor(props){
> super(props)
> this.state ={
> comment: 'Hello'
> }
> this.handleChange = this.handleChange.bind(this)
> }
> handleChange(value){
> console.log(value); //its logging Hello
> }
> 
> render(){
> return <...
> setContents={this.state.comment}
> setOptions={editorOptions}
> onChange={this.handleChange}
> disabled={this.props.isAppReadOnly}
> .../>
> }
> }

Hello @srinivasjay . When your `BasicEditor` component's `render` lifecycle hook is called, the content of the editor is set by `setContents`. That means the content of the editor has changed from its initial value of null to `this.state.comment`, and hence the `onChange` is fired.
