### ISSUE TITLE
Bug: after deleting all nodes, typing doesn't create a new node

### ISSUE THREAD

**Issue by zanzlender** [mkhstar/suneditor-react#281]
I believe this is a bug... If not then I would appreciate feedback on how to solve it :)

When you delete nodes individually then everything is ok, after you delete the last one a ```<p>``` node will be added for general text and you can do everything normally. However, if you select all nodes with CTRL+A then delete them, it will remove all nodes from the editor. Although you can type and see text, because of that if you type something right away and try to style it, it breaks the app.  
Pressing ```enter```solves this because it auto generates ```<divs>```.

Here's the video of what I mean: 

https://user-images.githubusercontent.com/44570474/182355910-1b5620a5-21cb-4fcd-8b88-d573a2e70089.mp4

I would propose an event listener or smth that would on delete nodes check if there are any, if not add a normal ```<p>``` node.

**Comment by mkhstar** [comment]
@zanzlender, I tried on the latest version, it seems to be working correctly
