### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'charCounter') 

### ISSUE THREAD

**Issue by web-veera** [mkhstar/suneditor-react#286]
Hi ,
when i use maxCharCount in my Nextjs project it shows error like following

**"Uncaught TypeError: Cannot read properties of undefined (reading 'charCounter')
    at eval (core.js?7467:5599:45)"**
I don't know how to resolve this error. could anyone help me?

component file

import React from 'react';
import dynamic from 'next/dynamic';
import 'suneditor/dist/css/suneditor.min.css';

const SunEditor = dynamic(() => import('suneditor-react'), {
  ssr: false
});

const TextEditor = ({ text, handleTextEditor, max_char }) => (
  <div>
    <SunEditor
      lang="en"
      name="my-editor"
      width="100%"
      height="200px"
      placeholder="Please type here..."
      autoFocus={false}
      setOptions={{
        charCounter:true,
        maxCharCount:max_char ? max_char : 1000,
        buttonList: [
          ['undo', 'redo'],
          ['bold', 'italic', 'underline', 'strike', 'subscript', 'superscript'],
          ['removeFormat'], ['indent', 'outdent'],
          ['align', 'list', 'table'], ['fullScreen']
        ],
        fullScreenOffset : '50px'
      }}
      onChange={handleTextEditor}
      setContents={text}
      onCopy={() => false}
      onCut={() => false}
      onPaste={() => false}
    />
  </div>
);
export default TextEditor;

**Comment by mkhstar** [comment]
@web-veera , the example you provided is not using SunEditor, can you please clarify it?

**Comment by samaniya** [comment]
Hi 
when i show count in bottom of editor using charCounter in react js ,i am getting error.
"Uncaught TypeError: Cannot read properties of undefined (reading 'charCounter')

i am using suneditor-react package
Pls advise or provide any solutions.
