### ISSUE TITLE
Font label, size label and format label not updating

### ISSUE THREAD

**Issue by kubuntux** [mkhstar/suneditor-react#287]
When new font, size or format has been selected, the label is not updating.

https://codesandbox.io/s/xenodochial-sky-3x51wp?file=/src/App.js

In the original package, it is working.

http://suneditor.com/sample/index.html

**Comment by mkhstar** [comment]
Again this is due to react 18's strict mode use effect, if you remove StrictMode it should work correctly until this bug is fixed. Check this issue https://github.com/mkhstar/suneditor-react/issues/296

**Comment by mkhstar** [comment]
@JiHong88 React.StrictMode makes cause this issue as well. Could you please take a look

**Comment by JiHong88** [comment]
@mkhstar This issue resolved to the v2.44.10

**Comment by mkhstar** [comment]
Hello @JiHong88 the latest version has fixed the resourceStateChange error bug. But this is still pending
