### ISSUE TITLE
Question : How can I hide navigation?

### ISSUE THREAD

**Issue by parkkiyoung0116** [mkhstar/suneditor-react#288]
Hello.
First of all , I want to tell you Thanks for this super sexy editor.👏👏👏

I saw the issue about the diffrence between editor text and HTML show.
so I want to make "sunEditor" to "fake textarea". And I applied "hideToolbar", "disable", "readOnly(?)"

but I couldn't hide undenline navigation. (class name se-navigation?)
![image](https://user-images.githubusercontent.com/106043239/191701594-d54bacc2-dd8e-43bf-9c74-cea8968c5884.png)

Is there other way to hide that navigation?
Maybe if I set style to that classname, It should be work. but If there are official way, please let me know.

thanks for this beautiful editor again :)

**Comment by mkhstar** [comment]
Hello @parkkiyoung0116 thanks
For now there is no official way to do that maybe you can open an issue at the core suneditor package
