### ISSUE TITLE
NextJS TypeError: core._resourcesStateChange is not a function

### ISSUE THREAD

**Issue by said7388** [mkhstar/suneditor-react#289]
I'm trying to use Sun editor with NextJs for the first time, But I've got these error
 
```
Unhandled Runtime Error
TypeError: core._resourcesStateChange is not a function

Call Stack
eval
node_modules\suneditor\src\lib\core.js (6186:0)
```

my code is: 
```
import SectionBlock from '@/components/ui/section-block';
import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import 'suneditor/dist/css/suneditor.min.css'; // Import Sun Editor's CSS File

const SunEditor = dynamic(() => import('suneditor-react'), {
  ssr: false,
});

const Post: NextPage = () => {
  return (
    <SectionBlock>
      <div>
        <p> My Other Contents </p>
        <SunEditor />
      </div>
    </SectionBlock>
  );
};

export default Post;

```

**Comment by MejanH** [comment]
yes, I am also facing this issue. I had to go back to the old versions.

**Comment by raiseerco** [comment]
Can confirm the same issue, tried every single version and the only one that works is the 2.16.5.

**Comment by hyen22** [comment]
just tried yesterday with latest version, having same problem

**Comment by said7388** [comment]
> 

This version is working........

**Comment by RajendraAVerma** [comment]
still facing same problem with next.js.

**Comment by ertu96** [comment]
same issue

**Comment by remaxmillennium** [comment]
yes, I am also facing this issue

**Comment by TheStarkster** [comment]
same here

**Comment by kimyoungtak2** [comment]
same here

**Comment by tzarger** [comment]
This seems to be an issue with `suneditor` itself. These two versions seem to work for me in React 18 and Next.js

    "suneditor": "^2.43.14",
    "suneditor-react": "^3.4.1",

Notice latest in `suneditor-react` and 2 versions back in `suneditor`.

**Comment by VHarastei** [comment]
> This seems to be an issue with `suneditor` itself. These two versions seem to work for me in React 18 and Next.js
> 
> ```
> "suneditor": "^2.43.14",
> "suneditor-react": "^3.4.1",
> ```
> 
> Notice latest in `suneditor-react` and 2 versions back in `suneditor`.

Thank you so much!
