### ISSUE TITLE
setContents is not working after update

### ISSUE THREAD

**Issue by musang33** [mkhstar/suneditor-react#290]
I used suneitor-react@2.8.0 and tried updating to 2.16.5.

However, setContents does not work.
The suneditor was initialized using setContents by importing data from the DB.
There is clearly data, but nothing is displayed.

And I googled this article out.
https://github.com/mkhstar/suneditor-react/issues/82
Is this the right cause?

But I don't understand that.
How do I fix it?

Attached is the source file.

[textEditor.txt](https://github.com/mkhstar/suneditor-react/files/9731966/textEditor.txt)

**Comment by mkhstar** [comment]
@musang33 you need to use the `defaultValue` prop to set initial contents of the editor. Also to change the contents of the editor programatically, you can use setContents. Please refer to the docs for more info
