### ISSUE TITLE
Change Email Editor content programmatically.

### ISSUE THREAD

**Issue by mariosknl** [mkhstar/suneditor-react#292]
I'm trying to find a way to change the content inside of an email editor programmatically. I've tried almost everything but unfortunately, I realize that it's not working as expected. I'm using ReactJS and SunEditor package. Can anyone please help me out with it?

**Comment by mkhstar** [comment]
@mariosknl could you provide an example?

**Comment by mariosknl** [comment]
@mkhstar well it seems that I found a way using the content of the component. Thanks for replying
