### ISSUE TITLE
Text behaviour change on copy paste

### ISSUE THREAD

**Issue by sreehari-cyberonics** [mkhstar/suneditor-react#293]
On copy pasting a content to preview, the style change according to text I copied.
I want only text not it's style

Example : 
const mycontent = <h1 Sun editor</h1 -> *tag not closed properly Github Problems
<SunEditor defaultValue={mycontent} / -> *tag not closed properly Github Problems

If the copied text is bold
Copied text  =>  **Bold Text**

output : <h1 style={{ fontStyle:'bold' }} >Bold Text </h1  ->  *tag not closed properly Github Problems

**Comment by mkhstar** [comment]
@sreehari-cyberonics you can paste and match styles. This behaviour is intentional to make migrating from one editor to suneditor easier
