### ISSUE TITLE
Selected font styles are getting resets to the default style when backspace is clicked

### ISSUE THREAD

**Issue by Albinvadakan** [mkhstar/suneditor-react#295]
@mkhstar 
Thank you for the amazing editor.

There is an issue I'm facing with the editor, the selected font styles are getting resets to the default style when multiple times the backspace is clicked.

Steps to reproduce the issue

* Select a font type and size in the editor and start typing.
* Then press 'enter' key 2 times
      
![image](https://user-images.githubusercontent.com/42968407/203514319-b70b89d8-7afd-4124-a2db-853d1cf4a36a.png)

* Click on the 'backspace'
* Now check the editor configuration. (font style, font size, color)
  
![image](https://user-images.githubusercontent.com/42968407/203514415-cc49358a-2ece-4fde-ae83-6b1617e2597d.png)

after clicking on backspace the selected styles are getting resets to the editor default style values.

Is there any way available to fix the issue by any configuration or what should be the fix for this issue? Please let me know.

Thanks.

**Comment by mkhstar** [comment]
@JiHong88 I tested it on the main suneditor package, the bug is over there as well. Thanks for opening the issue

**Comment by JiHong88** [comment]
The [2.45.0](https://github.com/JiHong88/suneditor/releases/tag/2.45.0) version has been updated.
Thank you.
