### ISSUE TITLE
Image setting does not work

### ISSUE THREAD

**Issue by tosenzzz** [mkhstar/suneditor-react#30]
Hi all,
First, many thank for wonderful editor.
I have issue with Image. Image setting buttons does not work for me.
Maybe I config wrong someth?
Thank you very much if you can help.
![image](https://user-images.githubusercontent.com/8873555/75898688-01087880-5e6d-11ea-90ed-105ceacaed8c.png)

**Comment by rbishal50** [comment]
same problem with me as well.

**Comment by mkhstar** [comment]
Fixed in version  [2.6.8](https://www.npmjs.com/package/suneditor-react/v/2.6.8)
@tosenzzz please confirm and close this issue

**Comment by rbishal50** [comment]
Working in version 2.6.8. Thank you.
