### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Rajat-1Stop** [mkhstar/suneditor-react#300]
Hi, Here I upload my issue regarding the editor. 

**Dependencies ->** 
![image](https://user-images.githubusercontent.com/104434530/216339961-7529181b-af53-4eec-818d-a26cc32a9cf6.png)

**Dev Dependencies ->**
![image](https://user-images.githubusercontent.com/104434530/216340202-f5a7db1d-773a-459c-84df-2b3d97266241.png)

**Error ->**
![image](https://user-images.githubusercontent.com/104434530/216338926-cb5b5372-9b51-4a9b-9ba9-e924fd872b58.png)

I am stuck here and I don't know how to fix this.

**Comment by xiaoshengaimm** [comment]
the same issue

**Comment by mkhstar** [comment]
Could you give a context of how you are using it in your code?

**Comment by 1337-5P34Ker** [comment]
the same issue

**Comment by patwadeepak** [comment]
This can be resolved by adding below to your package.json or to your jest config file if you have one -
`"jest": {
    "transformIgnorePatterns": ["node_modules/(?!(suneditor)/)"],
    }`
