### ISSUE TITLE
TypeError: core._resourcesStateChange is not a function

### ISSUE THREAD

**Issue by bbyomen** [mkhstar/suneditor-react#302]
![image](https://user-images.githubusercontent.com/103417892/223020768-26bc987c-1228-4fd4-95f5-3109b76cb802.png)

"suneditor": "^2.44.3",
"suneditor-react": "^3.4.1",

**Comment by Md-Anamul-Haque** [comment]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/82591214/223059906-83e2cbc5-cb11-4fa5-ad70-d6de65e8bda8.png">

**Comment by mkhstar** [comment]
Check this issue https://github.com/mkhstar/suneditor-react/issues/296

**Comment by mkhstar** [comment]
This should be fixed with the latest suneditor version
