### ISSUE TITLE
Not support dynamic onChange function

### ISSUE THREAD

**Issue by lnchit** [mkhstar/suneditor-react#303]
when i change the onChange function after Sun editor is on mounted, the sun editor still used the original onChange function.

I would like to suggest adding below code in the library to support dynamic onChange function.

```
useEffect(() => {
    if (editor.current) editor.current.onChange = (content) => {
      if (name && txtArea.current) txtArea.current.value = content;
      if (onChange) onChange(content);
    };
  }, [onChange]);
```

**Comment by mkhstar** [comment]
I want to make sure that functions are pure, if i do it like this, i would have to force people to wrap their onChange functions in a callback in order for this useEffect to not be called in every render
