### ISSUE TITLE
HTML generates weird characters

### ISSUE THREAD

**Issue by dev-brothers-bg** [mkhstar/suneditor-react#306]
I noticed that the editor generates sometimes weird characters inside the html tag tag

![image](https://user-images.githubusercontent.com/111856433/229538372-bb4e35e8-089f-4fd7-b957-07de82427320.png)

Here the generated HTML:

 ```HTML
 <div style="text-align: center" "=""><span style="font-size: 20px"><strong><span style="color: rgb(189, 189, 189)" "="">Unleash Your Sales Potential, Discover the Power of High-Performance</span>&nbsp;<span style="color: rgb(241, 241, 241)" "="">Online Shop</span></strong></span><br></div>
 ```

**Comment by mkhstar** [comment]
This should be opened in the core suneditor package
