### ISSUE TITLE
Photo edit tooltips show even if the editor is disabled

### ISSUE THREAD

**Issue by SorinGabriel02** [mkhstar/suneditor-react#307]
The image edit tooltips show in the <SunEditor /> component even though the component is disabled

**Related repository**
- [ ] [suneditor](https://github.com/JiHong88/SunEditor)
- [x ] This repository

**To Reproduce**
Have a list of disabled `SunEditor`s that contain images.
When the SunEditor components load first, these tooltips show. If I click anywhere else on the page, they dissapear.

**Expected behavior**
The tooltips do not show while the editors are disabled

**Screenshots**
![image](https://user-images.githubusercontent.com/53613432/232848088-4dd0a44b-43fa-42fc-b430-d74f652931c0.png)
![image](https://user-images.githubusercontent.com/53613432/232848128-ca35ee8e-392c-4d03-bfe6-b003fce7bad2.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [chrome]
 - Version: "suneditor": "^2.44.10",
    "suneditor-react": "^3.5.0",

**Additional context**
```
const setOptionsObj = {
    height: "80%",
    width: "90%",
    mode: "balloon",
    resizingBar: false,
  };
 
const postsList =
    posts &&
    posts
      .map(post => (
        <article key={post.id} className={"editorContainer"}>
          <NavLink
            style={{ textDecoration: "none" }}
            to={`/articol/${pageName}/${post.id}`}
          >
            <SunEditor
              lang={"ro"}
              hideToolbar={true}
              setContents={post.content}
              autoFocus={false}
              disable={true}
              setDefaultStyle={
                "background-color: rgb(240, 240, 230); overflow-x: hidden; overflow-y: hidden; max-width: 100%;"
              }
              setOptions={setOptionsObj}
            />
          </NavLink>
        </article>
      ));
```

**Comment by fkbeys** [comment]
I had the same issue. So i decided to use an other library to view the html content.
So, i had to install react-simple-wysiwyg library.
I use Sun editor for input,  wysiwyg for view html content.

**Comment by SorinGabriel02** [comment]
I tried using `react-simple-wysiwyg` but it does not center the photos that I have inserted into the posts. Funny thing is if I click anywhere on the screen besides the <SunEditor /> elements these tooltips dissapear.

**Comment by fkbeys** [comment]
Yes, you are right. 
If you save an image file in the center of the component , and then if you want to view it with the SunEditor component,it shows it in the center of the component.  There s no problem.

But other html renderers brings the image to the left. 
I also tried the code below. It also did the same thing.

        <div>
            <div dangerouslySetInnerHTML={{ __html: htmlContext }} />
        </div>
        
On the other hand, i tried to give a random key to the viewer <SunEditor key={Math.random()} like that, but it also did not work. 
I also could not solve it, but left aligned images are okey for me.

**Comment by SorinGabriel02** [comment]
My fix was adding this CSS inside the container class, were the list of disabled `SunEditor` was.
```
.sun-editor {
    .se-container {
      .se-controller {
        display: none !important;
      }
      .se-line-breaker-component {
        display: none !important;
      }
    }
  }
```

**Comment by mkhstar** [comment]
Maybe the core suneditor package could address this
