### ISSUE TITLE
Add Custom Dailog Not working

### ISSUE THREAD

**Issue by UnikoveNeeraj** [mkhstar/suneditor-react#313]
Add custom diloag code which is given in example is not working in latests versions-
Its suppoting only for version 2.16.3
I tried same code https://codesandbox.io/s/suneditor-custom-dialog-xx7he?file=/package.json:250-256 for others version but not working

Please help on this. 
Thanks in advanced

**Comment by mkhstar** [comment]
I tried on the latest version and couldn't find any issues 
https://codesandbox.io/s/suneditor-custom-dialog-forked-ln97l4?file=/src/App.js
