### ISSUE TITLE
onPaste prop not working in version 3.5.0

### ISSUE THREAD

**Issue by spxrtot** [mkhstar/suneditor-react#314]
**Describe the bug**
Starting from version 3.5.0 of suneditor-react, the onPaste prop is no longer being initialised. 
_functions.onPaste_ is always null, hence _typeof functions.onPaste === 'function'_ is always false on line 8032 of core.js

This works fine for versions <= 3.4.1.

**Related repository**
- [ ] [suneditor](https://github.com/JiHong88/SunEditor)
- [ ] This repository

**To Reproduce**
Steps to reproduce the behavior in version 3.5.0:
1. Add the onPaste prop to the component, i.e.: <SunEditor onPaste={handlePaste}/>
2. Define the handlePaste method, i.e. const handlePaste= () => console.log('test paste')

**Expected behavior**
Expected: 'test paste' printed in console
Actual: nothing printed in console because the handlePaste method is not called (seen as null I think) 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 113.0.5672.129

**Comment by mkhstar** [comment]
Latest version should fix, thanks
