### ISSUE TITLE
onPaste event is getting triggered when we cut the text , but not triggering on Paste

### ISSUE THREAD

**Issue by NishilSB** [mkhstar/suneditor-react#316]
**Describe the bug**
suneditor react is not triggering onPaste event when we do paste anything in the component, instead it is trigering onPaste event when we cut anything from it

**Related repository**
- [x] [suneditor](https://github.com/JiHong88/SunEditor)
- [ ] This repository

**To Reproduce**
1. Paste anything in the suneditor component

**Expected behavior**
1. It should trigger onPaste event when we do paste anything in the component

**Screenshots**
NA

**Code Sandbox Demo**
`const onChangeTrigger = function (e, core) {
    console.log(core.getContents());
    
  };

  const getSunEditorInstance = (sunEditor) => {
    refSunEditor.current = sunEditor;
  };
      <SunEditor
        id={id}
        setContents={value}
        onInput={onChangeTrigger}
        onCut={() => console.log('onCopy')}
        onPaste={(e, cleanData, maxCharCount, core) => onChangeTrigger(e, core)}
        setDefaultStyle='font-family:ZurichSans-Regular !important;  height: auto; min-height: 10vh; color: black;'
        getSunEditorInstance={getSunEditorInstance}
        showToolbar={true} />`

**Desktop (please complete the following information):**
 - Windows
 - chrome
 - 3.5.0

**Additional context**
NA

**Comment by mkhstar** [comment]
Latest version should fix these issues, thanks
