### ISSUE TITLE
Question: handling setContents and onChange

### ISSUE THREAD

**Issue by proggrkim** [mkhstar/suneditor-react#32]
Hi, I noticed that many had similar questions on usage of setContents and onChange. I also noticed that in the documentation, you clearly stated that setContents and onChange must use different variables. My question is on 'how'.  I would think something like that value={stateVariable} Then onChange={e =>setStateVariable(e)} should be available, but I guess that isn't.

Back to my question. I'm using a state variable to set initial value via setContents, which is obtained from browser's localStorage. Then inside of onChange, I need to update that variable as user types something. How do I achieve that when I can't use the same variable for setContents and modify it in onChange? 
Thank you!

**Comment by proggrasb** [comment]
Hi there.
I think you can use useCallback or useMemo to store initial state and then do something like:

`const initialContent = useCallback(() => {
    return data.var
  }, [])`

`<SunEditor setContents={initialContent()}  onChange={onChange}/>`

**Comment by mkhstar** [comment]
hi @proggrkim  the reason why `onChange` and `setContents` must use different variables is that when the `setContents` value changes the editor is re-rendered so when `onChange` updates the same variable, it will cause the editor to re-render and result in issues like the editor loosing focus and the cursor setting to the start of the editor.
Please use `setContents` to set the initial content of the editor. Or the setContents could be any variable other than the one that could cause the editor to re-render.

**Comment by valentinchobadzhakov** [comment]
Hi, i am having some issue with the SunEditor. I am typing some text in the editor, then click on the the cancel button. When i enter the sunEditor again the text value that i have not saved appears in the text editor.

       state = {
       text: "",
       newText: ""
        }

       cancelButtonAction= () => {
       const { areAnnotationsInEditMode } = this.state;
       this.setState({ areAnnotationsInEditMode: !areAnnotationsInEditMode });
       };

        <SunEditor
          setContents={this.state.text}
          hide={!areAnnotationsInEditMode}
          onChange={content => {
            this.setState({ newText: content });
          }}
            <ButtonCancel
              handleClick={() => {
                cancelButtonAction();
              }}
            />
        />
