### ISSUE TITLE
cursor backs to beginning when `setContents` value change.

### ISSUE THREAD

**Issue by wxjzeke** [mkhstar/suneditor-react#33]
example: 
```tsx
const Editor = (props: {
  value: string
  onChange: (value: string) => void
}) => {
  const { value, onChange } = props

  return (
    <SunEditor
      setOptions={{ mode: 'balloon-always', minHeight: 'auto' }}
      setContents={value}
      onChange={onChange}
    />
  )
}

const App = () => {
  const [value, setValue] = useState('')
  return <Editor value={value} onChange={content => setValue(content)} />
}
```

every time I enter something , then the cursor back to start.

**Comment by mkhstar** [comment]
This could at the suneditor @JiHong88 the setContents function always puts the cursor at the start of the editor

**Comment by JiHong88** [comment]
@wxjzeke 
The "setcontents" function does not specify the position of the cursor because it changes the entire contents of the editor.

**Comment by srinivasjay** [comment]
Is there any alternative solution for this. I am also facing the same probelm.

**Comment by JiHong88** [comment]
@wxjzeke @srinivasjay 
How are you using "setcontents"?

**Comment by wxjzeke** [comment]
@JiHong88 
Hi ~
Just like the example https://github.com/mkhstar/suneditor-react/issues/33#issue-588200892 above.

Since every time the `props.value` changes, it's going to cause a call here https://github.com/mkhstar/suneditor-react/blob/master/SunEditor.js#L112
and then 
https://github.com/JiHong88/SunEditor/blob/master/src/lib/core.js#L3995.

May be `createRange()` change the cursor position? Just my guess。😄

**Comment by wxjzeke** [comment]
@srinivasjay 
may be the alternative solution.
```ts
const Editor = (props: {
  value: string
  onChange: (value: string) => void
}) => {
  const { value, onChange } = props
 
 // keep the value by useState
  const initialValue = useState(value)

  return (
    <SunEditor
      setOptions={{ mode: 'balloon-always', minHeight: 'auto' }}
      setContents={initialValue} // this value will not change
      onChange={onChange}
    />
  )
}

const App = () => {
  const [value, setValue] = useState('')
  return <Editor value={value} onChange={content => setValue(content)} />
}
```

**Comment by JiHong88** [comment]
Hi @wxjzeke 
I'm sorry for the late reply.
The "setContents" method is not concerned with cursor position.
You can position the cursor at the end by calling [core.focusEdge](http://suneditor.com/sample/html/out/document-editor.html#focusEdge) after "setContents".

@mkhstar Is it possible to use the "core" methods in "suneditor-react"?

**Comment by mkhstar** [comment]
I didn't expose core in suneditor-react because it could easily lead to issues in react

**Comment by mkhstar** [comment]
But i could use core.focusEdge everytime setContents changes

**Comment by mkhstar** [comment]
I will update suneditor-react soon thanks

**Comment by bilalkosker** [comment]
It is not completely related with upper code part but I solved by keeping extra current value in my project.

`export interface RichTextEditorProps {
  value: string;
  onChange: (value: string) => void;
}

interface RichTextEditorState {
  initialValue: string;
  currentValue: string;
}

export class RichTextEditor extends React.Component<RichTextEditorProps, RichTextEditorState> {
  constructor(props: RichTextEditorProps) {
    super(props);
    this.state = {
      initialValue: this.props.value,
      currentValue: this.props.value
    };
  }

  componentDidUpdate(prevProps: RichTextEditorProps): void {
    if (prevProps.value !== this.props.value && this.state.currentValue !== this.props.value) {
      this.setState({initialValue: this.props.value});
    }
  }

  private onChange = (value: string) => {
    this.setState({currentValue: value}, () => {
      this.props.onChange(value);
    });
  };

  public render(): any {
    const {initialValue} = this.state;
    const {value} = this.props;

    return (
    <SunEditor
      onChange={this.onChange}
      setContents={initialValue}
      setOptions={options}/>
    );
  }
}`
(It is only added for showing my solution so the code is not perfect)

**Comment by bilalkosker** [comment]
I added currentValue state and set it before call props.onchange. 
Then I compare props.value and currentstate value in componentdidupdate then if it they are not equal we can set the new value as initial value because it should be changed by another action.

**Comment by mkhstar** [comment]
Fixed in version 2.9.0

**Comment by bilalkosker** [comment]
I think it is not been fixed. Now the cursor does not go back to beginning but lost current cursor position while writing and wait click or double click to continue. You should kept last cursor position and if the data changed itself focus and go the cursor position. If the value changed by props you will go start position.

**Comment by hteinlinaung1423** [comment]
> I think it is not been fixed. Now the cursor does not go back to beginning but lost current cursor position while writing and then waits for click or double click to continue. You should kept last cursor position and if the data changed itself focus and go the cursor position. If the value changed by props you will go start position.

I am also getting the same problem. Really appreciate for your effort. @mkhstar
