### ISSUE TITLE
There are multiple modules with names that only differ in casing. This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.

### ISSUE THREAD

**Issue by NishilSB** [mkhstar/suneditor-react#337]
**Describe the bug**
After udating to React 18 and  webpack-dev-server 4.15.1, iam getting this error on starting the project.
"suneditor-react": "^3.5.0",

when i use "webpack-dev-server": "^3.11.2", it is working fine

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic

**Related repository**
- [x] [suneditor](https://github.com/JiHong88/SunEditor)
- [ ] This repository

**To Reproduce**
update to react 18 and webpack-dev-server 4.15.1 and try to compile the project

**Expected behavior**
app should compile successfully 

**Screenshots**
![image](https://github.com/mkhstar/suneditor-react/assets/18629343/2ecf5471-e530-46dd-b678-5d2df57a2747)

**Code Sandbox Demo**
A code sandbox demo to demonstrate the problem to convince us of the issue

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome 
 - Version "suneditor-react": "^3.5.0",

**Additional context**

**Comment by mkhstar** [comment]
This must be a problem with your webpack setup, when i check the dist, it has on SunEditor.js
