### ISSUE TITLE
Image manager (file browser)

### ISSUE THREAD

**Issue by mrezaei8** [mkhstar/suneditor-react#34]
Hi, Thank you for your project,
how can i create Image manager (file browser) in suneditor?

@JiHong88

**Comment by JiHong88** [comment]
Hi @mrezaei8 
Please refer to the this issue. [#270](https://github.com/JiHong88/SunEditor/issues/270)

**Comment by mrezaei8** [comment]
> 
> 
> Hi @mrezaei8
> Please refer to the this issue. [#270](https://github.com/JiHong88/SunEditor/issues/270)

thanks , but this not good example for suneditor-react , it's node js project , i need reactjs for topic

**Comment by JiHong88** [comment]
An image gallery will be added in the next version.
And you can create your own [custom plugin](http://suneditor.com/sample/html/customPlugins.html) and use it.
