### ISSUE TITLE
Suneditor fails to execute on NextJS 14

### ISSUE THREAD

**Issue by tnnquang** [mkhstar/suneditor-react#340]
I am trying to use Suneditor-React but it crashes on NextJS version as described below

## Version
Sunedtior-React: 3.6.1
Suneditor: 2.45.1
NextJS: 14.0.1 and 14.0.2, using App Router

## Additional context
This is Suneditor's error message
![suneditor error](https://github.com/mkhstar/suneditor-react/assets/108243005/03beb928-4073-4231-86da-c97e06a396c1)
My code config
![import](https://github.com/mkhstar/suneditor-react/assets/108243005/46082f44-d3e6-45e6-882e-4836a3f29140)
![2](https://github.com/mkhstar/suneditor-react/assets/108243005/294c3f7a-09b7-4e0d-acea-a10146fbd78e)
![3](https://github.com/mkhstar/suneditor-react/assets/108243005/8e17bffe-a57d-4eb1-86e5-69f219463069)

**Comment by arasrezaei** [comment]
same here

**Comment by uusa35** [comment]
any updates same here

**Comment by nukrobzero** [comment]
hello, now i can fix by edit function "getSelectionNode" in path \node_modules\suneditor\src\lib\core.js line 1163  use can try.
![Screenshot 2023-11-12 193134](https://github.com/mkhstar/suneditor-react/assets/15253486/4b113bd5-ff43-4ec9-8673-80f7e9a55338)

**Comment by arasrezaei** [comment]
for those who have problems:
In your package.json file change the suneditor source link to:

git+https://github.com/arasrezaei/suneditor.git

Then do yarn or npm

**Comment by quang13** [comment]
> for those who have problems: In your package.json file change the suneditor source link to:
> 
> git+https://github.com/arasrezaei/suneditor.git
> 
> Then do yarn or npm

Thank you, this helped me solve this problem.

**Comment by tnnquang** [comment]
Thank you everyone for your help. Your method @arasrezaei helped me solve this error

**Comment by miran248** [comment]
@arasrezaei Any chance you could submit a pr to the upstream library?
