### ISSUE TITLE
Failed to load resource: net::ERR_INVALID_URL on setContents

### ISSUE THREAD

**Issue by siezyj** [mkhstar/suneditor-react#35]
Hi! 

I'm using SunEditor(SE) on my React app. I'm saving content from SE to my database as Base64. When I'm getting it from data base and passing to editor via setContents everything works fine on Firefox but on other browsers I got "Failed to load resource: net::ERR_INVALID_URL " and images won't display.

When I try inspect html code of SE on broken browser I see html tag <img src="myImgBas64Code> and I can copy it and paste to browser and image is displaying correctly. So html tag is created via editor without errors . 
`<SunEditor
        ref={editorRef}
        disable={isReadOnly}
        showToolbar={!isReadOnly}
        onChange={handleChange}
        placeholder="Please type here..."
        setContents={scriptDescription}
      />`

**Comment by mkhstar** [comment]
hi @siezyj can you explain the problem more clearly.
