### ISSUE TITLE
 Wordwrap problem for Persian letters

### ISSUE THREAD

**Issue by 1mehdiii** [mkhstar/suneditor-react#36]
Hi, a problem I encountered, for Persian letters, when it reaches the end of the line, it goes from the middle of the word to the next line, is there a solution to this problem?
![suneditor](https://user-images.githubusercontent.com/30597923/78682213-f2e1c800-7902-11ea-906e-bce720dd3f8e.JPG)

**Comment by mrezaei8** [comment]
salam bayad style content ro dasti RTL bedi

**Comment by 1mehdiii** [comment]
@mrezaei8 
defaultStyle: "word-break: unset;" ezafe kardam doros shod :)
Thanks :)

**Comment by mkhstar** [comment]
hi @mrezaei8 does this solve the problem
