### ISSUE TITLE
Issue with Alignment changes 

### ISSUE THREAD

**Issue by Bharadwaj627** [mkhstar/suneditor-react#38]
Hi, I have encountered a problem while changing the alignment of text, we have changeElement method in utils but that was not in this.utils oject
![image](https://user-images.githubusercontent.com/28941055/78866408-ee312700-7a5c-11ea-9720-a0c5ed54a587.png)

![image](https://user-images.githubusercontent.com/28941055/78866469-10c34000-7a5d-11ea-9858-b4c0cb06d1bc.png)

**Comment by mkhstar** [comment]
hi @Bharadwaj627  can you please be more clear. Can you share the code while using suneditor-react?

**Comment by Bharadwaj627** [comment]
Hi @mkhstar , Below is the code while i'm using sun editor

import React from 'react';

import SunEditor from 'suneditor-react';
import 'suneditor/dist/css/suneditor.min.css';
import plugins from 'suneditor/src/plugins'
import {font,align,blockquote,fontColor,fontSize,formatBlock,hiliteColor,horizontalRule,textStyle,table,paragraphStyle,list,lineHeight,link} from 'suneditor/src/plugins'

export class HTMLEditor extends React.PureComponent {
    constructor(props) {
        super(props);
        this.state = {
            cmpKey:this.props.cmpKey
        }
        this.props.value=this.props.value||"";
        this.timeout = null;
        this.handleChange = this.handleChange.bind(this)
        
    }
    
    handleChange (content){
        if(this.timeout){
            clearTimeout(this.timeout);
        } 
                                       
        this.timeout = setTimeout(()=> {
            if(!(this.props.value === content)&&this.props.onChange)
            this.props.onChange(this.state.cmpKey,content);
        },500)
    } 
    render() {
       return (
        <SunEditor onChange={this.handleChange} 
        setOptions={{
        plugins:[font,align,blockquote,fontColor,fontSize,formatBlock,hiliteColor,horizontalRule,textStyle,table,paragraphStyle,list,lineHeight,link],
        height:200,
        buttonList: [
            ['undo', 'redo'],
            'font', 'fontSize', 'formatBlock',
            ['paragraphStyle', 'blockquote'],
            ['bold', 'underline', 'italic', 'strike', 'subscript', 'superscript'],
            ['fontColor', 'hiliteColor', 'textStyle'],
            'removeFormat',
            ['outdent', 'indent'],
            ['align', 'horizontalRule', 'list', 'lineHeight'],
            ['table', 'link'],
            ['fullScreen', 'showBlocks', 'codeView'],
            ['preview', 'print', 'save', 'template']
        ]}}
        />
       )
    }
}
