### ISSUE TITLE
Does it work with next.js for SSR?

### ISSUE THREAD

**Issue by kaloraat** [mkhstar/suneditor-react#4]
Not an issue, just wanted to know if it works with next.js for SSR.

**Comment by kaloraat** [comment]
Not an issue, just wanted to know if it works with next.js for SSR.

**Comment by mkhstar** [comment]
Hi,
I have tested it and it does work. Because next.js works with react under the hood and suneditor-react is a react component

**Comment by roker15** [comment]
> I have tested it and it does work.

It only works when SSR=false

```
const SunEditor = dynamic(() => import("suneditor-react"), {
  ssr: false,
});
```
So how to use with `getserversideProps`?

**Comment by sashapetrovska** [comment]
> Hi, I have tested it and it does work. Because next.js works with react under the hood and suneditor-react is a react component

no it doesn't, it won't render in the server, only renders in the client.
