### ISSUE TITLE
using insertHtml in return <suneditor/> (React js)

### ISSUE THREAD

**Issue by mrezaei8** [mkhstar/suneditor-react#40]
Hi @JiHong88  ,
How using insertHtml via function in this code? or update suneditor after updated state?
Thanks ,
   <SunEditor 
      
      // appendContents={this.state.appendContent}
      lang="fa"  
      autoFocus={true} 
      setOptions={{
        mode: 'classic',
        minHeight: '400px',
        maxWidth:'100%',
        colorList: null,
        buttonList:  [
          ['undo', 'redo', 'font', 'fontSize', 'formatBlock'],
          ['bold', 'underline', 'italic', 'strike', 'subscript', 'superscript', 'removeFormat'],
         
          ['fontColor', 'hiliteColor', 'outdent', 'indent', 'align', 'horizontalRule', 'list', 'table'],
          ['link', 'image', 'video', 'fullScreen', 'showBlocks', 'codeView', 'preview', 'print' ,'template']
      ],
        }}
         
         onImageUploadBefore={this.handleImageUploadBefore}
        onImageUpload={this.handleImageUpload}
        onChange={this.handelonChange}
        insertHTML={this.state.appendContent}

      />

**Comment by mkhstar** [comment]
insertHTML prop Inserts an HTML element or HTML string or plain string at the current cursor position
