### ISSUE TITLE
Uncaught TypeError: this.src.renderToString is not a function

### ISSUE THREAD

**Issue by trungtvq** [mkhstar/suneditor-react#41]
use:
`import SunEditor, { katex } from 'suneditor-react';`
```
setOptions={{
                    height: 200,
                    katex: { // Custom option
                        src: katex,
                        options: {
                            throwOnError: true,
                        }
                      },
```
result when work with math (just simple add 1 character to modal:
```
Uncaught TypeError: this.src.renderToString is not a function
    at Object.<anonymous> (main.js:1784)
    at Object._renderMathExp (main.js:1881)
(anonymous) @ main.js:1784
_renderMathExp @ main.js:1881
```

**Comment by mkhstar** [comment]
Hi @trungtvq `katex` is not exported from suneditor-react. Please install `katex` separately from npm to be able to use it.

**Comment by trungtvq** [comment]
![image](https://user-images.githubusercontent.com/40919061/79068453-25b80180-7cf1-11ea-9cae-1273b8a36caf.png)
Hi @mkhstar i use `npm i katex` then `import katex from 'katex'` but i did not get result as expectation. Can you help me figure out what did i do wrong? Thank for your help!

**Comment by mkhstar** [comment]
What error are getting again @trungtvq

**Comment by mkhstar** [comment]
I hope u didnt forget to import the css file from katex like below
`import 'katex/dist/katex.min.css'`

**Comment by trungtvq** [comment]
it worked perfectly after `import 'katex/dist/katex.min.css'`. Thank for your work.
