### ISSUE TITLE
Adding name attribute to SunEditor React prop

### ISSUE THREAD

**Issue by RakaDoank** [mkhstar/suneditor-react#43]
I can't get any content value in my backend (Express) because there is no attribute name from the textarea/text input.

I tried add name attribute to the prop, like
`<SunEditor name='content'/>`

But still there is no such a "content" in my backend.

I was used Jodit Editor React before. I can easily add name attribute to the prop.
But in SunEditor, there is no actual textarea/text input with a name attribute if i really add a name prop.

**Comment by mkhstar** [comment]
Hi thanks for. you suggestion. I added this feature in version 2.10.0

**Comment by kyds3k** [comment]
@mkhstar - I'm having a problem with using the editor in my `react-hook-form` code. I'm adding the `name` attribute, but I still get this error:

`Field is missing 'name' attribute `

Any ideas?
