### ISSUE TITLE
Removing all table markup when you try to delete selected text in table cell

### ISSUE THREAD

**Issue by VadymMatiash** [mkhstar/suneditor-react#47]
There is a strange issue. When you select text in table cell and press "Backspace" to delete it, all table markup remove, but while you select text and press another key, all is OK, it replace selected text with letter

**Comment by mkhstar** [comment]
i am not encountering this issue @VadymMatiash can you paste the code that reproduced this.

**Comment by VadymMatiash** [comment]
"suneditor-react": "^2.8.0"

**Comment by VadymMatiash** [comment]
Version
"suneditor-react": "^2.8.0",

Editor component: 
import React from 'react'
import SunEditor from 'suneditor-react';
import 'suneditor/dist/css/suneditor.min.css';

const ReactSummernote = React.forwardRef((props, ref) => {

    const {
        value,
        onChange
    } = props
    return <SunEditor
        ref={ref}
        config={{
            readonly: false
        }}
        setOptions={{
            font : [
                'Arial',
                'Helvetica',
                'Times New Roman',
                'Verdana',
                'Courier New',
            ],
            buttonList: [
                    ['undo', 'redo', 'font', 'fontSize', 'formatBlock'],
                ['bold', 'underline', 'italic', 'strike', 'subscript', 'superscript', 'removeFormat'],
            ['fontColor', 'hiliteColor', 'outdent', 'indent', 'align', 'horizontalRule', 'list', 'table'],
            ['link', 'image', 'video', 'fullScreen', 'showBlocks', 'codeView', 'preview', 'print']
            ]
        }}
        theme="snow"
        setContents={value}
        onChange={onChange}
        fullPage={true}
    />
})

export default ReactSummernote

**Comment by mkhstar** [comment]
@VadymMatiash i am still not encountering this problem 
could you verify that the problem still persists in the latest versions.
Also you could share a demo on code sandbox
