### ISSUE TITLE
Buttons in toolbar continue work after disable editor.

### ISSUE THREAD

**Issue by bilalkosker** [mkhstar/suneditor-react#50]
The editor is disabled here but editor button clicks work.

![Screenshot 2020-04-23 at 11 01 07](https://user-images.githubusercontent.com/16794339/80074335-aaa4e580-8551-11ea-85f2-eb586832b4b3.png)

**Comment by mkhstar** [comment]
hi setting `disable={true}` only disables the editing area of the editor. To disable the toolbar use the prop `enableToolbar={false}`
