### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by kristofferlund** [mkhstar/suneditor-react#51]
Hi!

I just noticed that SunEditor implemented TypeScript support. Ref: https://github.com/JiHong88/SunEditor/issues/287 

Is this something that could be implemented in here as well?  
When i import as referred to in the documentation: `import SunEditor from "suneditor-react";`, I get this error:
`TS7016: Could not find a declaration file for module 'suneditor-react'.`

It works if I surpress it, but with warnings.

**Comment by mkhstar** [comment]
Hi @wxjzeke 
isn't there a declaration file for suneditor-react?

**Comment by wxjzeke** [comment]
Hi @kristofferlund
There is TypeScript support. The declaration file is in `suneditor-react/index.d.ts`.
And in my typescript project, there are no errors  or warnings reported about `import SunEditor from "suneditor-react"`. 
How is your tsconfig.json configured?

**Comment by kristofferlund** [comment]
Thanks for getting back to me!

Here is my tsconfig:

```
{
  "compilerOptions": {
    "allowJs": true,
      "lib": ["dom", "dom.iterable", "esnext"],
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react",
    "module": "esnext",
    "moduleResolution": "node",
    "outDir": "./dist/",
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "es5",
    "paths": {
      "@globalComponents": ["src/components"],
      "@tariffDucks": ["src/CustomsTariff/redux"],
      "@tariffComponents": ["src/CustomsTariff/components"],
      "@context": ["src/context"],
      "@utils": ["src/utils/"],
      "@views": ["src/views/"]
    }
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "include": [
    "src"
  ]
}
```

**Comment by wxjzeke** [comment]
@kristofferlund 
I think remove "node_modules" from  the `exclude` field in your tsconfig  would be ok. 

For more your can refer to the document here https://www.typescriptlang.org/docs/handbook/module-resolution.html

**Comment by kristofferlund** [comment]
Thanks for the til @wxjzeke, but this did not solve my problem.

It seems the problem was fixed here though: https://github.com/mkhstar/suneditor-react/commit/923a6db96e81647cee59df65900b2fec81cdabc0 

I see now that I should have added the full error message:
TS7016: Could not find a declaration file for module 'suneditor-react'. '...\node_modules\suneditor-react\dist\main.js' implicitly has an 'any' type.

Anyways, thanks!
