### ISSUE TITLE
lang props doesnot change language?

### ISSUE THREAD

**Issue by majidkarimizadeh** [mkhstar/suneditor-react#52]
hi...neither string nor object wont change language...?

**Comment by mkhstar** [comment]
Hi @majidkarimizadeh ,
Thanks for notifying me. Fixed in version 2.11.0

**Comment by LeThanhTung17** [comment]
@mkhstar I'm trying to add the button in addTagsWhitelist: 'button' and attributesWhitelist: 'type', to the editor but it is always deleted from the editor.  Please help me 😥

**Comment by mkhstar** [comment]
@LeThanhTung17  what is always deleted from the editor, could it be that you added it to the whitelist? can you post the example code you are using?

**Comment by LeThanhTung17** [comment]
`<SunEditor
                        setContents={currentTour ? currentTour.description : ""}
                        placeholder="Please type here..."
                        onChange={this.handleChange}
                        setOptions={{
                          buttonList: buttonList.complex,
                          formats: [
                            "label",
                            "button",
                            "select",
                            "option",
                            "input",
                            "//",
                            "pre",
                          ],
                          addTagsWhitelist:
                            "mark|canvas|label|button|select|option|input|//",
                          attributesWhitelist:
                            "contenteditable|colspan|rowspan|target|href|src|class|type|controls",
                        }}
                      />`
this is my code using SunEditor, when i using code writing mode in SunEditor and I added 1 button , but when I submitted, the button disapear or change to <p> tag.

**Comment by mkhstar** [comment]
hi @LeThanhTung17 
According to the line below from the core suneditor package

https://github.com/JiHong88/SunEditor/blob/d55134dc191b12ce05dcfbcbe509d822285189c1/src/plugins/submenu/formatBlock.js#L49

the strings passed to the formats array must contain the the ones in the defaultFormat else you have to use the custom format like the one below for every format
```javascript

[{
                    tag: 'div', // Tag name
                    name: 'Custom div' || null, // default: tag name
                    command: 'replace' || 'range' || 'free', // default: "replace"
                    class: '__se__format__replace_xxx' || '__se__format__range_xxx' || '__se__format__free_xxx'
                    // Class names must always begin with "__se__format__(replace, range, free)_"
}]
Hi @JiHong88 is this the intended purpose? If it is can it be stated in the documentation
```

**Comment by JiHong88** [comment]
Hi, @mkhstar @LeThanhTung17 
Yeah, It's intended purpose.
Format is a special tag that means a line in the editor.
Different actions are performed based on this line in the core object.
Tags such as buttons and labels are difficult to use as format tags.
See the example for creating a custom button.[customPlugins](http://suneditor.com/sample/html/customPlugins.html)

**Comment by LeThanhTung17** [comment]
oh, i got it!! thanks for your support, it's really helpful for me and
someone else.

Vào Th 5, 14 thg 5, 2020 vào lúc 11:51 JiHong.Lee <
notifications@github.com> đã viết:
