### ISSUE TITLE
plugin.fileTags[tag].toLowerCase is not a function When adding "Image" Or 'video' in buttonList

### ISSUE THREAD

**Issue by amehta1605** [mkhstar/suneditor-react#54]
Hello,
I am using simple installation and trying to add Image and Video. but when I add 'Image' Or 'video'
 in button list, I got this error 
`plugin.fileTags[tag].toLowerCase is not a function`
 and it crash the page, my editor configurations are simple 

```
Import SunEditor, {buttonList} from 'suneditor-react';
import 'suneditor/dist/css/suneditor.min.css';

<SunEditor  setOptions={{  buttonList: [
		['image', 'fontSize', 'formatBlock', 'bold', 'underline', 'italic', 'strike', 'fontColor', 'hiliteColor', 'outdent', 'indent', 'align', 'horizontalRule', 'list', 'table', 'link', 'fullScreen', 'showBlocks', 'codeView'], ], }} 
onChange={this.onEditorChanges.bind(this)} setContents={this.state.content} />
```

am I missing something or Its known bug? Please help.

**Comment by mkhstar** [comment]
hi @amehta1605,
please which version are you using

**Comment by mkhstar** [comment]
i tried to replicate the error with your code but didn't get any issue.

**Comment by mkhstar** [comment]
If you are using the latest version, please try to replicate the error at codesandbox

**Comment by amehta1605** [comment]
Version : 

"suneditor-react": "^2.11.0"

 Do I need to install anything else to work image/video?

**Comment by mkhstar** [comment]
Hi @amehta1605 
No you do not need anything else. Can you replicate the error at codesandbox please?

**Comment by amehta1605** [comment]
Hi @mkhstar , 
hmm, I can't replicate it on codesandbox, its working there. But on my setup.

**Comment by amehta1605** [comment]
Thanks @mkhstar , I found the issue and fixed in my project.

**Comment by magdi14** [comment]
@amehta1605  could you please share what was wrong ??
