### ISSUE TITLE
Updating the value of height in setOptions prop

### ISSUE THREAD

**Issue by peter-chow** [mkhstar/suneditor-react#55]
Hi,

It appears that changes to setOptions aren't applied once the component is mounted.  For example, if height is initially set to 250 and is then changed to 500, the height of the component stays at 250.

**Comment by mkhstar** [comment]
Hi @peter-chow,
The setOptions prop is used to set the initial settings of the editor. I would like to implement this feature but it could impact on the performance of the editor because every time the component updates I would need to make a shallow comparison of the previous setOptions prop and the current setOptions prop to decide on whether to call the setOptions of the core suneditor package or not. Alternatively, I could just call the setOptions props whenever there is a prop update (worse option)

**Comment by mkhstar** [comment]
In future I could implement this feature. But I would add another prop called dynamicSetOptions. When the user explicitly set it to true, The shallow comparison will be made else the default setOptions will remain

**Comment by peter-chow** [comment]
Another approach would be to promote height as another prop like width and apply updates to the options based on changes to it.

**Comment by mkhstar** [comment]
Right now the setOptions prop overides other properties. After the next release I will promote the height and width property as you mentioned

**Comment by peter-chow** [comment]
Awesome, thanks @mkhstar!  I'll check it out.

**Comment by peter-chow** [comment]
Hi @mkhstar,

It looks like height hasn't been added as a prop yet - the logic to handle it is there, but it's not defined as a prop.

**Comment by mkhstar** [comment]
Thanks for your feedback @peter-chow 
I have realized the same problem. @JiHong88 can you explain to us how the height property works for setOptions?

**Comment by JiHong88** [comment]
@mkhstar 
Currently code is below:
```javascript
function (options) {
  let optionStyle = '';
  if (options.height) optionStyle += 'height:' + options.height + ';';
  if (options.minHeight) optionStyle += 'min-height:' + options.minHeight + ';';
  if (options.maxHeight) optionStyle += 'max-height:' + options.maxHeight + ';';
  return optionStyle;
}
```
https://github.com/JiHong88/SunEditor/blob/master/src/lib/util.js#L1645

returned style is applied wysiwyg div.
`wysiwyg.cssText = optionStyle`
https://github.com/JiHong88/SunEditor/blob/master/src/lib/constructor.js#L347

After the editor is loaded, combine "defaultStyle" and "optionStyle" and reapplied.
(options style) + `defaultStyle`
This will cause "defaultStyle" will take precedence then "optionStyle".

**Comment by mkhstar** [comment]
@JiHong88 ,
It seems the height styles are not applied to the editor.

**Comment by JiHong88** [comment]
Isn't "defaultStyle" defined?
"defaultStyle" takes precedence.
```javascript
const editor = suneditor.create('id', {
 default: 'height:500px;'
})
editor.setOptions({height:200})
```
: height === 500px

**Comment by mkhstar** [comment]
@JiHong88 default style was not called

**Comment by JiHong88** [comment]
@mkhstar This issue is occur when using the "iframe" option?

**Comment by JiHong88** [comment]
@mkhstar @peter-chow 
The [2.30.7](https://github.com/JiHong88/SunEditor/releases/tag/2.30.7) version has been updated.
Fixed style-related issues.
Thank you.

**Comment by mkhstar** [comment]
Hi @JiHong88 ,
It is now working but i have realized that it is not accepting percentages

**Comment by JiHong88** [comment]
@mkhstar Can you give an example?

**Comment by mkhstar** [comment]
@JiHong88 if the height's value cannot be provided in percentage then i think this issue is now fixed. @peter-chow please can you check on it again in the latest version

**Comment by peter-chow** [comment]
@mkhstar,  it looks like the TypeScript definition hasn't added the new Height prop.

**Comment by mkhstar** [comment]
Hi @peter-chow sorry for the late reply. I just fixed it in the new releases

**Comment by peter-chow** [comment]
Thanks @mkhstar - it's working now.  One thing I've noticed is that the height doesn't include the toolbar.  Is there anyway to make the height the total height (including the toolbar)?  

This is probably a question for @JiHong88.

**Comment by JiHong88** [comment]
@peter-chow 
The height of the toolbar is variable depending on the count and size of the buttons.
