### ISSUE TITLE
Parameter 'errorMessage' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by ryisamu** [mkhstar/suneditor-react#56]
Hi,

I just tried to add the editor based on the Readme's Getting Started section but I ran into this error with the typescript definition file.

```
C:/Codes/Repos/Common UI/Web/node_modules/suneditor-react/index.d.ts
(41,27): Parameter 'errorMessage' implicitly has an 'any' type.
```

I'm using the latest version, any idea how should I fix this?

**Comment by mkhstar** [comment]
Hi @ryisamu just fixed it in version 2.11.1

**Comment by ryisamu** [comment]
Hi @mkhstar thanks for the fix but now there's a different error that came up.

```
C:/Codes/Repos/Common UI/Web/node_modules/suneditor-react/index.d.ts
(69,3): Exports and export assignments are not permitted in module augmentations.
```

Just to be clear, I have not started doing anything yet, just adding it into a page.

**Comment by mkhstar** [comment]
@wxjzeke do you have any idea about this issue?

**Comment by wxjzeke** [comment]
Hi @mkhstar
Can you show the code ?

**Comment by wxjzeke** [comment]
Hi @ryisamu 
Can you show the code ?

**Comment by wxjzeke** [comment]
@mkhstar 
 The imports should be inside of the declared module. Same issue here:
 https://github.com/react-native-community/react-native-linear-gradient/pull/357

Set `"skipLibCheck": true` in tsconfig.json could avoid the error: `Exports and export assignments are not permitted in module augmentations` @ryisamu 

And I'v made a pr https://github.com/mkhstar/suneditor-react/pull/63, this should fix the error then.

**Comment by mkhstar** [comment]
Hi @ryisamu 
Can you confirm it on the latest version? 2.11.2

**Comment by mkhstar** [comment]
Thanks @wxjzeke

**Comment by ryisamu** [comment]
Thanks @wxjzeke and @mkhstar , I just tried 2.11.3 and things are working after I fixed the following errors but that's due to my team's lint rules that's applied.

C:/Codes/Repos/Common UI/Web/node_modules/suneditor-react/types/SetOptions.ts
(1,26): interface name must start with a capitalized I

C:/Codes/Repos/Common UI/Web/node_modules/suneditor-react/types/SetOptions.ts
(2,21): Array type using 'Array<T>' is forbidden for simple types. Use 'T[]' instead.

C:/Codes/Repos/Common UI/Web/node_modules/suneditor-react/types/SetOptions.ts
(62,73): file should end with a newline

If you are alright for me to make changes base on these rules, I'll create a pull request.

**Comment by wxjzeke** [comment]
Hi @ryisamu 
Everybody may apply different rules, you should configure your lint skip `node_modules`.

**Comment by ryisamu** [comment]
Got it, will do that then, thanks.
