### ISSUE TITLE
Loosing focus on initial typing in Internet Explorer 11

### ISSUE THREAD

**Issue by Mikco11** [mkhstar/suneditor-react#58]
Hello, i am using **suneditor-react package version 2.11.1**.
When i want to type something to empty editor in **Internet Explorer 11.3247** I click into editor area but then it immediately loses focus.
I have to be typing something and at the same time i have to click on editor to get some text in it or just click on editor and the be very quickly type something.
Once it has some value in it i can type more text, edit, etc. normally.

I am providing empty string from Redux to setContents property as a initial value.

**Comment by mkhstar** [comment]
Hi @Mikco11 can you please post the code you are using. Also you could confirm if the issue still persists in version 2.11.3

**Comment by ryisamu** [comment]
I just tested and confirmed this is happening still in 2.11.3 for me. I have to click any of the tool button and then click back to the editor area before I can type. But I do see error appearing in the console.

For example, when I click on Bold, I saw this error:
```
SCRIPT5007: Unable to get property 'textContent' of undefined or null reference
bundle.js (175346,41)
```

After that, I am able to type in the area.

**Comment by trembacz** [comment]
@mkhstar Yes, this exists in 2.11.3 I was able to replicate this too.

@Mikco11 just like I've posted it here: https://github.com/JiHong88/SunEditor/issues/377#issuecomment-635209383 I've had the same issue and fixed this by creating default range again in onLoad handler
```// fix issue with losing focus on IE 11
if (editorRef.current.editor.core.util.isIE) {
  editorRef.current.editor.core._createDefaultRange();
}

**Comment by mkhstar** [comment]
@Mikco11 ,
sorry for the late reply i just missed that. I have added that and it will be fixed in the latest release. I will give you a feedback when it is ready
