### ISSUE TITLE
Unknown edit feature in disabled editor

### ISSUE THREAD

**Issue by Mikco11** [mkhstar/suneditor-react#59]
Hello,

I amusing editor just for displaying content without ability to edit it.
Property _disable_ is set to _true_ .
When i go with my mouse just slightly over the top image this feature appears.
See attached screenshot. 
What does it do ? Why is it shown in "disabled mode" ?

I should mention that i add that red image/logo to HTML string in backend based on business logic.
Also i couldnt manage to align the logo to the right even when I wrapped it in `div` and set `text-align: right`. When i inspected editor it somehow wrapped the image with `<figure>` element so that probably caused not aligning. I found out that suneditor completely ignores any element i wrap around img and it wraps it into own div and then figure element.

Inspecting editor in browser:
`<div class="se-component se-image-container __se__float-none" contenteditable="false"><figure style="margin: 0px;"><img alt="logo"  data-proportion="true" data-align="none" data-index="2" data-file-name="0nIb402rh8NCVV8FwLoffCw2f8Bl23zA2fzE74AAAAASUVORK5CYII=" data-file-size="0" data-origin="," data-size="," data-rotate="" data-rotatex="" data-rotatey="" data-percentage="auto,auto" style="" origin-size="133,55"></figure></div>`

String i get from DB and set it in setContents:
` <div style="text-align: right;"><img alt='logo'  src='base64data'/></div>`

![unknown_feature_suneditor](https://user-images.githubusercontent.com/43450691/82348252-e1f39e80-99f8-11ea-93aa-a0f4bda266bc.png)

 suneditor-react version:  2.11.1

**Comment by mkhstar** [comment]
Hi @Mikco11 I would be very grateful if you post a demo on codesandbox. Or you could post the code you are using for the Suneditor component. So that I can verify it very easily

**Comment by Mikco11** [comment]
Look like @JiHong88 added it and fixed it for milestone 2.30.0 [here](https://github.com/JiHong88/SunEditor/issues/376)

**Comment by mkhstar** [comment]
@Mikco11  it seems the version 2.30.0 has not been posted yet to npm. As soon as it is updated, i will sync it.

**Comment by JiHong88** [comment]
@Mikco11 Version 2.30.0 has not been completed.
I'll let you know when it's released

**Comment by mkhstar** [comment]
Hi @Mikco11,
Can you confirm that the latest release has fixed this bug
