### ISSUE TITLE
editor value

### ISSUE THREAD

**Issue by duncanokeyo** [mkhstar/suneditor-react#6]
am tryint to set the initial content of the editor using 

` <SunEditor
                                setContents={vendor_agreement}
                                setOptions={{
                                    height: 200,
                                    buttonList: buttonList.complex
                                }}
                                onChange={(content) => (
                                    this.setVendorAgreement(content)
                                )}></SunEditor>
`

but its showing blank yet vendor_agreement is not empty string

**Comment by mkhstar** [comment]
Hi can you cross check your work again and give a feedback. Because i tested setContents and it is working

**Comment by mkhstar** [comment]
Or maybe you can show me a demo using an online sandbox

**Comment by camiriveron** [comment]
I'm having the same issue when the content is coming from the server and getting it from redux's state. 

So originally it grabs the reducer `initialState` value which is empty, but then when the actual content arrives from the server, even if the `prop` gets updated, the editor content remains blank.

**Comment by mkhstar** [comment]
Thanks Dear @camiriveron .
This is the perfect explanation to the problem. I will try to solve it later.
But for now you can get around it by rendering the editor as soon as you have the actual content.
A pseudo code below
```javascript
{actualContent.length ? <SunEditor />: null}

```

**Comment by mkhstar** [comment]
I just fixed this problem in version 2.4.0. Thanks a lot
