### ISSUE TITLE
How can i handle the image base64 to server url?

### ISSUE THREAD

**Issue by yoojeen126** [mkhstar/suneditor-react#61]
I dont want the content image with base64, because its affect to database size too large,
So i wanna base64 to change server url.
I try react-quill but it's  no module for set image size  before image upload(submit).

**Comment by JiHong88** [comment]
You can use the [onImageUploadBefore](http://suneditor.com/sample/html/out/document-user.html#onImageUploadBefore) event.

**Comment by mkhstar** [comment]
@yoojeen126  The onImageUploadBefore event is availble in suneditor-react prop onImageUploadBefore (The same name is used for the prop)

**Comment by mylastore** [comment]
> i can upload the image with onImageUploadBefore event.
> but when i return the url, the editor still uses the base64 encoded image for src attribute.
> 
> how can i do something which the returned url gets into the src attribute ?!

Same here, Why can they just set an example on the documentation. Is a misery...  The naming for the functions are so confusing. handleImageUpload, handleImageUploadBefore, handleImageUploadBefore all sound like you are uploading images to a server. Name should be something like this: insertImageToEditor, beforeInsertingImageToEditor, handleEditorImage something along those lines.. I been trying to figure this out for about 3days.

**Comment by JiHong88** [comment]
@mylastore @MehdiAghighi 
I'll improved the name of the function in version 3.0.0.
You can simply set `imageUploadUrl` option to upload to the server.

Please refer to the link below for how to use "ImageUploadBefore".
https://github.com/JiHong88/SunEditor/issues/414#issuecomment-725249439
http://suneditor.com/sample/html/out/document-user.html#onImageUploadBefore

If you can't implement it or if there is something that needs to be improved, please leave an issue in [SunEditor](https://github.com/JiHong88/SunEditor/issues)

Thank you.
