### ISSUE TITLE
Even if autoFocus is false suneditor receives focus for a moment and then looses it

### ISSUE THREAD

**Issue by VladyslavGoloshchapov** [mkhstar/suneditor-react#65]
I was expecting that sueditor would not receive focus if autoFocus is false.
However what actually happens is following:
1) suneditor receives focus
2) then it checks value of autoFocus
3) if autofocus is false, suneditor blurs

This is particulary bad if I have long page (with scrolling) and suneditor instance is on the bottom - user is being automatically scrolled to suneditor.

Unfortunately I will have to most likely stop using this great library because of this bug.

**Comment by VladyslavGoloshchapov** [comment]
are there any workarounds for this ?

**Comment by mkhstar** [comment]
Hi @VladyslavGoloshchapov,
Do you have setContents in your props?

**Comment by VladyslavGoloshchapov** [comment]
Yes, I do have setContents

**Comment by mkhstar** [comment]
Hi @VladyslavGoloshchapov,
Thanks for the feedback. This has been a problem for the core suneditor package. When one of the above props are used, it causes the editor to focus. @JiHong88 can this be fixed. @VladyslavGoloshchapov if you like you can open an issue at the core sun editor package about the editor focusing after using setContents appendContents or insertHTML

**Comment by JiHong88** [comment]
@mkhstar "setContents" and "appendContents" do not give focus.
However, when there is no "selection" information, focus is given.
Are you using "setContents" to initialize data?

**Comment by JiHong88** [comment]
@mkhstar @VladyslavGoloshchapov 
Even if there is no "selection" information, it seems to be correct not to give focus.
This can be solved simply.
It will be applied in the next version.

**Comment by VladyslavGoloshchapov** [comment]
hi @JiHong88 
yes I am using setContents.

Could you please elaborate on "selection" information? I don`t really understand.
Also do you support main SunEditor package?

**Comment by JiHong88** [comment]
Hi, @VladyslavGoloshchapov 
Yeah, I'm support SunEditor package.
"selection" information is mean the `window.getSelection()` object.
The current problem is, if the editor has never had focus,  then give to focus in order to create a "selection" object.
I'll fix it in the next version.

**Comment by JiHong88** [comment]
@mkhstar @VladyslavGoloshchapov 
I'll release the 2.30.0 version to this week.

**Comment by VladyslavGoloshchapov** [comment]
nice!
I think I will be able to hold sun editor then!
@mkhstar  will you be able to release new version for react with new fix ?

**Comment by mkhstar** [comment]
@VladyslavGoloshchapov 
Yes when the core suneditor packages is updated

**Comment by VladyslavGoloshchapov** [comment]
thanks

**Comment by VladyslavGoloshchapov** [comment]
hi @JiHong88 !

are you still planning to release 2.3.0.0?

**Comment by JiHong88** [comment]
Hi @VladyslavGoloshchapov 
I'm sorry, the work is delayed than I thought, and it will be released this week.

**Comment by VladyslavGoloshchapov** [comment]
hi @mkhstar 
new version of SunEditor was released yesterday.

**Comment by VladyslavGoloshchapov** [comment]
verified, fixed


Thank you all!!
