### ISSUE TITLE
Default Style State Issue 

### ISSUE THREAD

**Issue by sawanmakwana** [mkhstar/suneditor-react#66]
Hi @mkhstar @JiHong88,
I was working with default properties... As we discussed earlier default property is working but I got stuck with one scenario. (with Ref to #25 )
![Screenshot from 2020-05-28 20-03-06](https://user-images.githubusercontent.com/45915871/83374668-ea30de00-a3e9-11ea-80e5-7009eb9734d3.png)

Here, You can see that I have given default font-size and font-family from the state; like it is variable and it can change from anywhere at any time. In this case, it is not changing (properties remain the same as of initial render)
It is there anything that you can do, then it would be a great help!

**Comment by JiHong88** [comment]
@sawanmakwana @mkhstar 
There is a function to change the default style. [setDefaultStyle](http://suneditor.com/sample/html/out/document-user.html#setDefaultStyle)

**Comment by sawanmakwana** [comment]
Hi @JiHong88 ,
I have tried with setDefaultStyle property also but it is also giving the same output
          
![Screenshot from 2020-06-01 14-17-12](https://user-images.githubusercontent.com/45915871/83392556-e9f90880-a412-11ea-8470-1bec80a24321.png)
It is setting property from an initial state, rather than updated one

**Comment by JiHong88** [comment]
@sawanmakwana 
This project is not under my control.
I don't know if "setDefaultStyle" is called automatically because I don't know about React well.

**Comment by mkhstar** [comment]
@sawanmakwana I will make the `setDefaultStyle` prop dynamic in the next release. I will inform you when it is released

**Comment by mkhstar** [comment]
This will help it to react to the changes of the string you pass to it

**Comment by sawanmakwana** [comment]
Sorry for inconvinent.. @JiHong88 

Thanks a lot!
@mkhstar

**Comment by sawanmakwana** [comment]
hi @mkhstar ,
Yes, it's working. Thank you so much!
