### ISSUE TITLE
Passing escaped html inside setContents doesn't work properly

### ISSUE THREAD

**Issue by Reflex-Gravity** [mkhstar/suneditor-react#70]
When an escaped html string is passed into `setContents`, it doesn't unescape the html while rendering. Hence, all URLs are broken and renders the escaped HTML.

Is there any other way to insert content which is an escaped html?

For eg:

This is an escaped html string:
`<br><p><br /><img src=\"/static/icons/favi.png\" />`

When it renders it becomes:
`"<p><br></p><img src="\&quot;/static/icons/favi.png\&quot;">`

The escape characters are escaped again.

**Comment by mkhstar** [comment]
Hi @Reflex-Gravity if you need this feature you can open an issue at the core suneditor package
