### ISSUE TITLE
에디터 테이블 셀안에 shift+한글 입력시 한글 입력이 되지 않음

### ISSUE THREAD

**Issue by hongku** [mkhstar/suneditor-react#71]
안녕하세요~ @JiHong88 
에디터 내에서 테이블을 생성 후 테이블 셀안에서 shift + 한글 입력시
shift 에 shortcut 기능으로 문자 입력이 되지 않는 문제가 있어요~
keyboard shortcut 기능을 끌 수 있는 방법이 있나요?

**Comment by JiHong88** [comment]
@hongku SunEditor 이슈는 메인 프로젝트에 등록해주세요.
이 프로젝트는 제가 관리하고 있지 않습니다.
그리고 문의 하신 내용은 수정되었고 다음 버전부터 적용됩니다.

**Comment by hongku** [comment]
@JiHong88 
감사합니다
