### ISSUE TITLE
How to use the core object?

### ISSUE THREAD

**Issue by hajeonghun** [mkhstar/suneditor-react#76]
Hi, @mkhstar 

I want to use core object in onChange or onInput function in React.
(JS Code -> core.context.element.wysiwygFrame.offsetHeight )

And I want to get the height of the editor through the core object.

Can you add a core object to the onInput or onChange function?

If not, is there another way?

**Comment by trembacz** [comment]
Hi @hajeonghun, there is another way, you can use ref, with that you will have access to the core object.

Try something like that:
```
import React, {useRef} from 'react';

const editorRef = useRef(null);
const onChangeHandler = value => onValueChange(value, editorRef);

<SunEditor
    name={name}
    ref={editorRef}
    ...
    onChange={onChangeHandler}
/>```

**Comment by andreferreiravntrs** [comment]
> 
> 
> Hi @hajeonghun, there is another way, you can use ref, with that you will have access to the core object.
> 
> Try something like that:
> 
> ```
> import React, {useRef} from 'react';
> 
> const editorRef = useRef(null);
> const onChangeHandler = value => onValueChange(value, editorRef);
> 
> <SunEditor
>     name={name}
>     ref={editorRef}
>     ...
>     onChange={onChangeHandler}
> />
> ```

Property 'ref' does not exist on type 'IntrinsicAttributes & SunEditorReactProps & { children?: ReactNode; }'
