### ISSUE TITLE
[Bug] deleted image (Uncaught TypeError: Cannot read property '0' of undefined)

### ISSUE THREAD

**Issue by hajeonghun** [mkhstar/suneditor-react#78]
Hi,

The current version is 2.12.1

The following message appears when deleting an image.

Uncaught TypeError: Cannot read property '0' of undefined
Uncaught TypeError: Cannot read property '1' of undefined

**Comment by mkhstar** [comment]
@JiHong88  has this bug been fixed in version 2.30.1

**Comment by hajeonghun** [comment]
> @JiHong88 has this bug been fixed in version 2.30.1

@mkhstar I know from suneditor solved in 2.30.1.

But I am writing the suneditor-react library.

Is there a solution?

**Comment by mkhstar** [comment]
Alright then i ll add that in the next release

**Comment by JiHong88** [comment]
@mkhstar Current version has a bug.
I will release a next version today.

**Comment by hajeonghun** [comment]
> Alright then i ll add that in the next release

Thanks, I always use it well

**Comment by mkhstar** [comment]
I just updated the version @hajeonghun. If the issue still persists reopen. Thanks

**Comment by hajeonghun** [comment]
Hi, @mkhstar @JiHong88 

I updated to 2.12.2. 

There is no error when deleting the image, but the following error occurs when inserting the first image.

`Uncaught TypeError: Cannot read property 'nodeType' of null
    at Object.getOffset (main.js:12122)
    at Object.call_controller_resize (main.js:1563)
    at Object.select (main.js:6268)
    at Object.callPlugin (main.js:14540)
    at Object.<anonymous> (main.js:15377)`
