### ISSUE TITLE
[Bug] Uncaught TypeError: Cannot read property 'nodeType' of null

### ISSUE THREAD

**Issue by hajeonghun** [mkhstar/suneditor-react#79]
Hi, @mkhstar @JiHong88 

I updated to 2.12.2. 

There is no error when deleting the image, but the following error occurs when inserting the first image.

Uncaught TypeError: Cannot read property 'nodeType' of null
    at Object.getOffset (main.js:12122)
    at Object.call_controller_resize (main.js:1563)
    at Object.select (main.js:6268)
    at Object.callPlugin (main.js:14540)
    at Object.<anonymous> (main.js:15377)

_Originally posted by @hajeonghun in https://github.com/mkhstar/suneditor-react/issues/78#issuecomment-647198571_

**Comment by JiHong88** [comment]
Hi,
This issue will be resolved in the main package.
https://github.com/JiHong88/SunEditor/issues/410

**Comment by JiHong88** [comment]
@mkhstar The [2.30.5](https://github.com/JiHong88/SunEditor/releases/tag/2.30.5) version has been updated.
Thank you. : )

**Comment by mkhstar** [comment]
Hi @hajeonghun this issue should be fixed in suneditor-react version 2.12.3. Reopen this issue if it doesn't
