### ISSUE TITLE
Style tag shown in editor

### ISSUE THREAD

**Issue by sowmiyaseshadriii** [mkhstar/suneditor-react#8]
Hi,
thanks for the package,
I have implemented the editor as per the docs, but in editor shows the style tag,

```
import React from "react";
import SunEditor from 'suneditor-react';
import 'suneditor/dist/css/suneditor.min.css';

class Editor extends React.PureComponent {
constructor(){
super(props);
this.state={
content = `
   <!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<style>
.textstyle{
padding: 20px;
text-align: center;
}
</style>
<body>
  <p class="textstyle">Test Content</p>
</body>
</html>
`
}
}

render(){
  return (
   <SunEditor setContents={this.state.content} />
 );
}

```
![image](https://user-images.githubusercontent.com/17636011/71457200-ca144780-27d7-11ea-9073-02cc16a71a6b.png)

**Comment by mkhstar** [comment]
Hi @sowmiyaseshadriii,
I am sorry style tags are not supported in this editor. Because it can cause a lot of harm to the global css and so on. If you want to use styles then I will recommend `inline styles`. Like below:
```html
<p style="padding: 20px; text-align: center;"> Test Content </p>

```

**Comment by sowmiyaseshadriii** [comment]
Hi @mkhstar , since I have media query in my scenario, is there any possible way to hide the style in view, thanks

**Comment by JiHong88** [comment]
Hi @sowmiyaseshadriii, @mkhstar 
The [fullPage]() option lets you use style tags. [example](http://suneditor.com/sample/html/examples.html#CodeMirror)

**Comment by mkhstar** [comment]
@JiHong88 can you clarify how to use the fullPage option

**Comment by JiHong88** [comment]
@mkhstar 
If use the "fullPage" option
The editor is created as an iframe and can use HTML, HEAD, BODY tags, and DOCTYPE declarations.

**Comment by mkhstar** [comment]
is it when you set it to true?

**Comment by JiHong88** [comment]
Yes, default value is false.
And if "fullPage" is true, then the "iframe" option is also true.

**Comment by mkhstar** [comment]
when set to true I get an error, does it need any dependency

**Comment by matteocollina** [comment]
Hello, I found the same problem. In my options I have`fullPage: true` but when I set html content with `<style>...</style>` the editor removes it so all styles are not applied.

**Comment by JiHong88** [comment]
You must be use the [setIframeContents](http://suneditor.com/sample/html/out/document-editor.html#setIframeContents)
