### ISSUE TITLE
TypeScript setOptions error

### ISSUE THREAD

**Issue by RicardoGaefke** [mkhstar/suneditor-react#80]
Hi,
I am pretty sure this is really simple but when using setOptions `icons` is marked as mandatory.

Can it be optional just like others?

Thank you very much.

**Comment by mkhstar** [comment]
@RicardoGaefke,
Thanks for notifying me I just fixed it in version 2.12.4. Reopen this issue if the problem still persists

**Comment by RicardoGaefke** [comment]
> @RicardoGaefke,
> Thanks for notifying me I just fixed it in version 2.12.4. Reopen this issue if the problem still persists

Thank you very much. It worked like a charm. ❤️

**Comment by mkhstar** [comment]
Thanks
