### ISSUE TITLE
setContents wont work

### ISSUE THREAD

**Issue by AMessina2** [mkhstar/suneditor-react#82]
Hi, I just started using this library and I'm trying to use the prop setContents, but It just won't work.

I've tried to set the contents on the example ("My contents") and when I load it its blank.

This is how I'm using it:

`
              <SunEditor 
                setOptions={{
                  height: 300,
                  buttonList: buttonList.complex 
                }} 
                setContents="My contents"
                lang="es"
                />`

And It's empty:

![image](https://user-images.githubusercontent.com/55154238/86445929-81ec5980-bd13-11ea-91d0-0557cfc95176.png)

The HTML is also empty:

![image](https://user-images.githubusercontent.com/55154238/86445967-8e70b200-bd13-11ea-8d30-c4cc91769158.png)

I'm probably doing something wrong, I would appreciate some help.

Thank you!

**Comment by AMessina2** [comment]
I just found the solution.

I passed a "name" prop and It worked, somehow.

Thank you anyways.

I will close it

**Comment by mkhstar** [comment]
Hi @AMessina2,
Thanks for notifying me on this issue. I think this a problem to do with the latest version of the core suneditor package.
@JiHong88 setContents, appendContents and other important function are not working. I am giving a link to a demo at codepen below.
[https://codepen.io/mkhstar/pen/wvMpXMZ?editors=1111](https://codepen.io/mkhstar/pen/wvMpXMZ?editors=1111)

**Comment by mkhstar** [comment]
@AMessina2 
The name prop makes it work because it set the contents of the text area under the hood

**Comment by JiHong88** [comment]
If you want to use "setContents" to initialize the contents of the editor, it is better to use it inside the "onload" function.
The editor is not completely initialized until "onload" is called.
Even if the setting was possible in the previous version, using an option such as "iframe" would not work properly and it was not a safe operation.

**Comment by mkhstar** [comment]
This is a big breaking change I wish you had stated it in the release not

**Comment by JiHong88** [comment]
Yeah, It's my mistake. :(
I didn't think many people would initialize the editor with the "setContents" function.

**Comment by JiHong88** [comment]
As before, if you don't use the "iframe" option, you can fix it to use "setContents" right away.
However, this is an unstable behavior and there is a difference between using and not using "iframe".
If you use "setContents" for initialization, you will also need to call "this.history.reset(true)".

I am confused what to do.
Another way is to add the "initHTML" option.

**Comment by mkhstar** [comment]
ok bro I will fix that in suneditor-react

**Comment by mkhstar** [comment]
Hi @AMessina2,
I just fixed that in version 2.12.5 you don't need to use the name prop.
The name prop is useful when you want to send it with a form without using `setContents`. Refer to the documentation to learn more.
Reopen this issue if the issue still persists. Thanks

**Comment by JiHong88** [comment]
@mkhstar 
I'll add the "value" option.
You can input an initial value for this option.

**Comment by JiHong88** [comment]
@mkhstar The [2.31.0](https://github.com/JiHong88/SunEditor/releases/tag/2.31.0) version has been updated.
Thank you.
