### ISSUE TITLE
Issue with expansion/reduction icons

### ISSUE THREAD

**Issue by gponimansky** [mkhstar/suneditor-react#83]
Under setOptions.icons, all icons are working such as print and preview etc, however there is a strange behaviour with full-screen icons:
- expansion
- reduction

1. As you can see the fullscreen icon has been changed and is showing the correct behaviour. However when I click it to go to the reduction icon.
![Screenshot1_2020-07-06](https://user-images.githubusercontent.com/7742170/86636311-22f04400-bfa2-11ea-827f-563663aeab28.png)
2. The reduction icon that I overwrote is not there. This behaviour gets stranger when I click on the reduction icon.
![Screenshot2_2020-07-06](https://user-images.githubusercontent.com/7742170/86636396-3ac7c800-bfa2-11ea-985f-802473c113d5.png)
3. Now the fullscreen icon has changed to its default.
![Screenshot3_2020-07-06](https://user-images.githubusercontent.com/7742170/86636507-5c28b400-bfa2-11ea-841a-ea108edb77dd.png)

Not sure if it has to do with suneditor-react or needs to be moved to suneditor itself.

**Comment by mkhstar** [comment]
Hi @gponimansky, 
You can open this issue at the core suneditor package
