### ISSUE TITLE
after uploading image on my server, how can i add image into contents using imageurl returns?

### ISSUE THREAD

**Issue by wonjeongpark-THEHRDer** [mkhstar/suneditor-react#84]
Hi, there.
thank you for supporting a wonderful editor in Pure React.

I tried to upload a image to my server before add image using a function in handleImageUploadBefore.
it returns a image`s url but i cannot find how to add image into contents in one function.
Not using another function or directly using file, how can i add it to contents?

=
이미지를 파일로 직접 올리지 않고
handleImageUploadBefore를 이용해서 직저 업로드 되기 전에
이미지 파일을 디비에 저장하고 리턴되는 url값을 이용해서 바로 contents에 이미지를 추가하는 방법을 알고 싶습니다.
 const response = {
                    // "errorMessage": "insert error message",
                    "result": [ { "url":`${fireBaseUrl}`, "name": `${fileName}`, "size": `${fileSize}` }, ]
                }
              core.plugins.image.imageUploadUrl(response);
이 방법도 시도했지만 제일 아래에 image가 undefinded라고하네요.
```
ex)
handleImageUploadBefore(files, info, core, uploadHandler){
...
       // upload a image into my server
            .then(imgUrl=> {
               // I wanna add image into contents using imgUrl returns in HERE!
            })
            .catch(err=>console.log('에러 ='+err))
        })
    }
```
thank you for taking time on me.

**Comment by JiHong88** [comment]
여기 참고할만한 링크 입니다.
https://github.com/JiHong88/SunEditor/issues/414#issuecomment-649715918

**Comment by mkhstar** [comment]
@wonjeongpark-THEHRDer 
You can access the core object by attaching a ref to the Suneditor component

**Comment by JiHong88** [comment]
@wonjeongpark-THEHRDer @mkhstar 
You can do it without a core object in the latest [version](https://github.com/JiHong88/SunEditor/releases)
