### ISSUE TITLE
onChange is not retaining css property in html output

### ISSUE THREAD

**Issue by sawanmakwana** [mkhstar/suneditor-react#86]
Hello,
I am using this editor in my application to get formatted HTML output which can be displayed with the help of iframe.
But the property/styles applied to my text are not reflecting in onChange output and hence I end up getting default basic HTML.
Is this the correct approach? @mkhstar 
I have attached ss of use case

![Screenshot from 2020-07-14 10-57-22](https://user-images.githubusercontent.com/45915871/87387794-10d55d80-c5c1-11ea-9b41-3a228fdf8e68.png)
![Screenshot from 2020-07-14 10-57-33](https://user-images.githubusercontent.com/45915871/87387805-1763d500-c5c1-11ea-8b99-17372a0fac9d.png)

![Screenshot from 2020-07-14 11-09-36](https://user-images.githubusercontent.com/45915871/87388496-91488e00-c5c2-11ea-889e-a6265e76f644.png)

**Comment by mkhstar** [comment]
Hi @sawanmakwana you could ask this in the main suneditor package

**Comment by sawanmakwana** [comment]
ok. I will post same on the main editor package.

**Comment by mkhstar** [comment]
Thanks
