### ISSUE TITLE
setContents is not working

### ISSUE THREAD

**Issue by hongku** [mkhstar/suneditor-react#89]
hello @mkhstar 
I tried to use the updated version 2.13.0 this time.
But the setContents props don't seem to work.

live code here..
https://codesandbox.io/s/test-suneditor-pzufo

I used the same way I used to work.
However, the initial content is not inserted.

What am I doing wrong?

**Comment by mkhstar** [comment]
Hi @hongku 
Thanks for drawing my attention on this. I just fixed it in a minor update version 2.13.1
[See this issue on why it was not working](https://github.com/JiHong88/SunEditor/issues/446#issue-663526215)

**Comment by mkhstar** [comment]
Reopen this issue if you encounter any problem

**Comment by hongku** [comment]
hi @mkhstar 
I tried to install an updated version (2.13.1).
An installation error occurs..

```
❯ npm view suneditor-react

suneditor-react@2.13.0 | MIT | deps: 2 | versions: 59
A React Component for Suneditor
https://github.com/mkhstar/suneditor-react#readme

keywords: editor, wysiwyg, suneditor, text-editor, word, react

dist
.tarball: http://nexus.woowa.in/content/groups/npm-all/suneditor-react/-/suneditor-react-2.13.0.tgz
.shasum: e99880a1d6cee1cebe14d8a5ec42789d7ddcaded
.integrity: sha512-OlpdcGxfLuRahOyCBM/ba4o4cZB8VFs8JDVvqw6vXoNJyx1ROqA+UBDwdkKkYF3gRAQBcszX6FUT6Jw5xUTI9w==
.unpackedSize: 1.0 MB

dependencies:
prop-types: ^15.7.2 suneditor: ^2.32.0  

maintainers:
- npm-upload <kusimusah@gmail.com>

dist-tags:
alpha: 2.6.5    latest: 2.13.0  

published yesterday by npm-upload <kusimusah@gmail.com>
```
However, 2.13.1 is posted on the npm homepage.
Can you check it?
