### ISSUE TITLE
Performing image upload

### ISSUE THREAD

**Issue by felipemegale** [mkhstar/suneditor-react#92]
Hi!
I'm having a little trouble in setting image upload.

What I want to do is: upon choosing an image, upload it to a file server and use that URL as the src attribute on the generated img tag.

I tried using onImageUploadBefore but I didn't get it right. Also, I didn't find anything useful for me on the docs here nor on Suneditor's docs.

**Comment by SorinGabriel02** [comment]
This problem is discussed here: https://github.com/JiHong88/SunEditor/issues/414#issuecomment-649715918

**Comment by felipemegale** [comment]
Thanks, will definately look into it.
