### ISSUE TITLE
setContents if  contains 'img' element, suneditor will crash.

### ISSUE THREAD

**Issue by JinHe-PerkinElmer** [mkhstar/suneditor-react#93]
I am using "suneditor-react": "^2.13.1", when i setContents with a HTML fragment requested from the background(It's a string composed of html tags), which contains  several 'img' elements.
And I debug this according the error msg 'Cannot read property 'replaceChild' of null'; the message thrown by main.js (main.js:6789) update_image function, in transform section:
`if (isNewContainer) {
        var existElement = this.util.isRangeFormatElement(contextImage._element.parentNode) || 
        this.util.isWysiwygDiv(contextImage._element.parentNode) ? contextImage._element : 
        /^A$/i.test(contextImage._element.parentNode.nodeName) ? contextImage._element.parentNode : 
       this.util.getFormatElement(contextImage._element) || contextImage._element;
        existElement.parentNode.replaceChild(container, existElement);
        imageEl = container.querySelector('img');
        contextImage._element = imageEl;
        contextImage._cover = cover;
        contextImage._container = container;
} // transform`

Under some unknown conditions, existElement.parentNode is null, so editor is crashed. What should i do?
Can you give some advice or help,  thank you very much. @JiHong88  and anybody else...

**Comment by JinHe-PerkinElmer** [comment]
Through multiple tests, I found that the same parent node contains multiple img tags, editor will crash.

**Comment by JiHong88** [comment]
Hi @JinHe-PerkinElmer 
Please show the HTML structure to inserted.

**Comment by JinHe-PerkinElmer** [comment]
> Hi @JinHe-PerkinElmer
> Please show the HTML structure to inserted.

Just like this: `<p><img src="http://github.com/img1.png" />    <img src="http://github.com/img2.png" /></p>`

**Comment by JiHong88** [comment]
@JinHe-PerkinElmer 
Images are treated like format lines.
Please change HTML structure like this:
`<img src="http://github.com/img1.png" /> <img src="http://github.com/img2.png" />`

**Comment by JinHe-PerkinElmer** [comment]
> @JinHe-PerkinElmer
> Images are treated like format lines.
> Please change HTML structure like this:
> `<img src="http://github.com/img1.png" /> <img src="http://github.com/img2.png" />`

@JiHong88, The bad news is that the old pages are generated by customers, which is not guaranteed. So, I'm trying another library for the time being, thank you all the same.
