### ISSUE TITLE
TypeError: this._iframeAutoHeight is not a function at Object._resourcesStateChange

### ISSUE THREAD

**Issue by SorinGabriel02** [mkhstar/suneditor-react#94]
I'm getting this error in React.
`TypeError: this._iframeAutoHeight is not a function at Object._resourcesStateChange` if i'm switching to another page before `<Suneditor />` components are completely rendered on the page...
Is there a way to cancel the `<Suneditor />` render if an user navigates away prematurely?
This error appears when a list of `<Suneditor />`  components is being rendered and the component unmounts. Here is my code:
```import React, { useReducer, useEffect, useContext, useRef } from "react";
import { NavLink } from "react-router-dom";
import SunEditor from "suneditor-react";

import { AppContext } from "../context/appContext";
import useHttpReq from "../hooks/useHttpReq";
import Loading from "../components/Loading";
import Backdrop from "../components/Backdrop";

import { newsBtn, editContainer, notFound } from "./Noutati.module.scss";
import "suneditor/dist/css/suneditor.min.css";

const initialState = {
  isLoading: false,
};

function postsReducer(state, action) {
  switch (action.type) {
    case "fetch":
      return {
        ...state,
        isLoading: action.payload,
      };
    default:
      return state;
  }
}

function Noutati(props) {
  const ref = useRef(null);
  const { isAdmin } = useContext(AppContext);
  const [state, dispatch] = useReducer(postsReducer, initialState);
  const [posts, err, makeReq, cancelReq] = useHttpReq();

  const setOptionsObj = {
    height: "65.5vh",
    mode: "balloon",
    resizingBar: false,
  };

  const postsList =
    posts &&
    posts
      .sort((a, b) => {
        // sort the posts by creation date last to first
        const aCreatedAt = Date.parse(a.createdAt);
        const bCreatedAt = Date.parse(b.createdAt);
        return bCreatedAt - aCreatedAt;
      })
      .map((post) => (
        <section key={post.id} className={editContainer}>
          <NavLink
            style={{ textDecoration: "none" }}
            to={`/noutati/${post._id}`}
          >
            <SunEditor
              ref={ref}
              showToolbar={false}
              enableToolbar={false}
              setContents={post.content}
              disable={true}
              setDefaultStyle={
                "background-color: rgb(240, 240, 230); overflow-x: hidden; overflow-y: hidden;"
              }
              setOptions={setOptionsObj}
            />
          </NavLink>
        </section>
      ));

  // get post on page load
  useEffect(() => {
    dispatch({ type: "fetch", payload: true });
    makeReq("get", "/posts");
  }, [makeReq]);

  // when a response arrives isLoading = false
  useEffect(() => {
    if (posts || err) dispatch({ type: "fetch", payload: false });
  }, [posts, err]);

  // cancel request if one is active on component dismount
  useEffect(() => {
    return () => {
      cancelReq &&
        cancelReq.cancel("component dismounts, api is being canceled");
    };
  }, [cancelReq]);

  if (state.isLoading)
    return (
      <div>
        <Backdrop />
        <Loading />
      </div>
    );

  return (
    <div>
      {isAdmin && posts && (
        <NavLink to="/postNou">
          <button className={newsBtn}>Publică articol</button>
        </NavLink>
      )}
      {postsList && !postsList.length ? (
        <h1 className={notFound}>
          Eroare 404 <br /> Momentan nu a fost găsit nici un articol.
        </h1>
      ) : (
        <main>{postsList}</main>
      )}
    </div>
  );
}

export default Noutati;
```

**Comment by mkhstar** [comment]
Hi @SorinGabriel02 can you post the complete project on platforms like code sandbox. Because you are importing local modules. Sorry for the late reply

**Comment by SorinGabriel02** [comment]
Thanks for the reply, code used is in this repo: https://github.com/SorinGabriel02/teachers-spa

**Comment by n-rogozny** [comment]
I have the same problem. Is there some kind of solution

**Comment by SorinGabriel02** [comment]
I would say we need a way to cancel content loading into the editor if the need arises.

**Comment by mkhstar** [comment]
Hi @SorinGabriel02 
Please can you check on the latest version. If the problem persists please mention it. Thanks

**Comment by ozizhakGT** [comment]
Hi, I also have this bug 
I using "suneditor-react": "2.13.2"

I notes that it happened every time the component re-render

is anybody has a solution? :/

**Comment by karthik-js** [comment]
@mkhstar With 2.14.2 same issue. any solution?

**Comment by mkhstar** [comment]
Hi everyone
with the ``ref`` of the suneditor you could destroy the editor before navigating away
Eg. below:

```js
editorRef.current.editor.destroy();
```
You can check the readme if you need to know how to obtain the ref of the editor.

**Comment by MakiMarc** [comment]
You are using `setContents` to set the content. Use `defaultValue` instead and the error should not appear anymore.

Two-way binding should not be used. This is because the `setContents` statement triggers the onChange event. If you want to set the initial value of the editor, use the `defaultValue` prop.

**Comment by roker15** [comment]
> 

editor!.current!.destroy() is not a function

**Comment by roker15** [comment]
> Hi everyone with the `ref` of the suneditor you could destroy the editor before navigating away Eg. below:
> 
> ```js
> editorRef.current.editor.destroy();
> ```
> 
> You can check the readme if you need to know how to obtain the ref of the editor.

another error ---
editor!.current!.destroy() is not a function

**Comment by roker15** [comment]
> ```js
> editorRef.current.editor.destroy();
> ```

This issue was not visible in recent version. But After updating to React 18, Nextjs 12 and lastest version of suneditor and suneditor-react. This issue is again in picture and my production app is crashing. please help it's urgent.

I can't destroy using `editorRef.current.editor.destroy()` because there is not `editor `object in `editorRef.current` . However there is destroy function in `editorRef.current` and I am able to use something like `editor.current?.destroy()` 

`editor.current?.destroy()` this also compiles but during production time again when it shows `TypeError: editor.current.destroy is not a function`

**Comment by fatimaFaibrik** [comment]
Hello, 
I have the same issue and tried any solutions I could find in this issue and the #1037 but I have still this error message : this._iframeAutoHeight is not a function.
Any news since these 27 days ?

**Comment by jahanzaib88** [comment]
i am having the same issue. can anybody please help ? i am using  "suneditor-react": "^3.6.1", version

**Comment by profy-app** [comment]
I followed @MakiMarc suggestion and it worked.

**Comment by jaydeep-pipaliya** [comment]
Facing same issue , is there any solutions ?

**Comment by BitBender72** [comment]
Hi @jaydeep-pipaliya , @jahanzaib88,  @SorinGabriel02, @mkhstar 

suneditor-react: ^3.6.1
Typescript

I was able to solve the problem by creating a custom component using suneditor-react as follows.

`import React, { useRef, useEffect, useState } from 'react';
import SunEditor, { buttonList } from 'suneditor-react';
import SunEditorCore from 'suneditor/src/lib/core';
import plugins from 'suneditor/src/plugins';

import { en } from 'suneditor/src/lang';
import 'suneditor/dist/css/suneditor.min.css';
import 'katex/dist/katex.min.css';
import 'codemirror/mode/htmlmixed/htmlmixed';
import 'codemirror/lib/codemirror.css';

const RichTextEditor: React.FC<{
  name: string;
  onChange: (value: string) => void;
  value: string;
}> = ({ name, onChange, value }) => {
  const editor = useRef<SunEditorCore>();
  const [content, setContent] = useState('');
  const getSunEditorInstance = (sunEditor: SunEditorCore) => {
    editor.current = sunEditor;
  };
  const options = {
    plugins: plugins,
    // Uncomment to enable CodeMirror and LaTeX support
    // codeMirror: {
    //   src: CodeMirror,
    //   options: {
    //     indentWithTabs: true,
    //     tabSize: 2,
    //   },
    // },
    // katex: katex,
    lang: en,
    buttonList: [
      [
        'font',
        'fontSize',
        'formatBlock',
        'bold',
        'underline',
        'italic',
        'paragraphStyle',
        'blockquote',
        'strike',
        'subscript',
        'superscript',
        'fontColor',
        'hiliteColor',
        'textStyle',
        'removeFormat',
        'undo',
        'redo',
        'outdent',
        'indent',
        'align',
        'horizontalRule',
        'list',
        'lineHeight',
        'table',
        'link',
        'image',
        'fullScreen',
        'showBlocks',
        'codeView',
        'preview',
      ],
    ],
  };

  useEffect(() => {
    if (value) {
      setContent(value);
    }
  }, [value]);

  return (
    <SunEditor
      name={name}
      lang="en"
      setDefaultStyle="font-family: Arial; font-size: 14px;"
      setOptions={options}
      onChange={onChange}
      getSunEditorInstance={getSunEditorInstance}
      setContents={content}
      height="350px"
    />
  );
};

export default RichTextEditor;
`

How to use:
`<RichTextEditor name="Editor" onChange={(data) => setContent(data)} value={content} />`

I hope this helps you.
Sincerely,
