### ISSUE TITLE
How to set z-index 0 for editor?

### ISSUE THREAD

**Issue by png-prakash** [mkhstar/suneditor-react#96]
I need to set z-index 0 for this editor.

![sample](https://user-images.githubusercontent.com/61315943/90513671-a09c9780-e17d-11ea-8ec3-1f0462c6609b.png)

![Sampl2](https://user-images.githubusercontent.com/61315943/90531052-355dc000-e193-11ea-866a-2d3e92228674.png)

**Comment by mkhstar** [comment]
Hi @png-prakash can you open this issue at the core suneditor repo?
