### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scrollTop' of null

### ISSUE THREAD

**Issue by wordsire** [mkhstar/suneditor-react#99]
I have implemented your amazing HTML editor in reactjs project. My use case is to use this editor in a form to capture question text and their choices to add a test question into the system. Katex is also a major part of our project, since half of the questions consist of mathematics and chemistry.

Now, I have a single re-usable component for SunEditor. What I am doing is, in my "add question" form I have six editors imported from the same re-usable component. Everything is working fine except for Katex equations. When I'm adding latex equations using the tool in all the fields, an error is getting thrown up randomly. Sometimes after two, or three or four additions.

![image](https://user-images.githubusercontent.com/40787109/90820964-d09b9480-e34f-11ea-8f12-f052df78b0ff.png)

**Comment by rikinshah23** [comment]
I have the same issue.

**Comment by mkhstar** [comment]
Hi @wordsire 
Please can you include a demo for me to test it out. Sorry for replying late
